### ISSUE TITLE
needed patch for eperm issues

### ISSUE THREAD

**Issue by earonesty** [facebook/metro#1001]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `metro-file-map@0.73.9` for the project I'm working on.

Windows frequently gets EPERM issues when building.   This seems to fix the problem.   Watcher keeps running.   

Here is the diff that solved my problem.   Possibly emitting a change event for locked-files would be better?  Not sure, tbh.

```diff
diff --git a/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro-file-map/src/watchers/NodeWatcher.js b/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro-file-map/src/watchers/NodeWatcher.js
index 69666ba..bfb8565 100644
--- a/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro-file-map/src/watchers/NodeWatcher.js
+++ b/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro-file-map/src/watchers/NodeWatcher.js
@@ -241,7 +241,14 @@ module.exports = class NodeWatcher extends EventEmitter {
     const relativePath = path.join(path.relative(this.root, dir), file);
     const registered = this._registered(fullPath);
     try {
-      const stat = await fsPromises.lstat(fullPath);
+      let stat
+      try {
+        stat = await fsPromises.lstat(fullPath);
+      } catch (e) {
+        if (e.code == 'EPERM')
+            return;
+        throw e;
+      }
       if (stat.isDirectory()) {
         // win32 emits usless change events on dirs.
         if (event === "change") {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by robhogan** [comment]
Hmm, thanks for the report and patch @earonesty! Do you know what circumstances you see EPERM triggered? (Eg additions and/or modifications, certain file types?). How often do you run into it? 

I’m partly wondering whether we can catch this with Windows integration tests, or maybe if we understand the cause a bit better, whether there’s another solution like backoff/retry.

**Comment by earonesty** [comment]
building a native RN app on windows.  very frequently happens when using https://shopify.github.io/react-native-skia/

**Comment by LXGaming** [comment]
I've repeatedly encountered this issue while live editing code, my assumption is that JetBrains WebStorm is creating temporary files when saving and it's these files causing this issue.

I created the following patch with patch-package and haven't had issue since, my concern with this patch is I'm not sure if the path in question is suppose to be unregistered. This patch differs from the one in the initial post in that it uses the existing error handler instead of creating a nested one.
```diff
diff --git a/node_modules/metro-file-map/src/watchers/NodeWatcher.js b/node_modules/metro-file-map/src/watchers/NodeWatcher.js
index 69666ba..4a25a90 100644
--- a/node_modules/metro-file-map/src/watchers/NodeWatcher.js
+++ b/node_modules/metro-file-map/src/watchers/NodeWatcher.js
@@ -313,7 +313,9 @@ module.exports = class NodeWatcher extends EventEmitter {
       if (
         (error === null || error === void 0 ? void 0 : error.code) !== "ENOENT"
       ) {
-        this.emit("error", error);
+        if (!isIgnorableFileError(error)) {
+          this.emit("error", error);
+        }
         return;
       }
       this._unregister(fullPath);
```

**Comment by earonesty** [comment]
nope, that looks right

**Comment by robhogan** [comment]
Many thanks folks - patched in https://github.com/facebook/metro/pull/1007
