### ISSUE TITLE
Metro disconnect when the emulator network is Off

### ISSUE THREAD

**Issue by saif-o99** [facebook/metro#1049]
Sorry im reopening this here, i posted this on RN github but that guy closed the issue without clear explanation. it was weird.
https://github.com/facebook/react-native/issues/38579
so i had to add it here hopping to get a clear explanation of why it wasn't happening before the upgrade if this is the normal scenario.

Thanks...

**Comment by Xmaxer** [comment]
Same issue on RN 0.72.4, I didn't have this issue on 0.66.3 but that was a long time ago at this point. I just now noticed it after re-testing something without network connectivity.
