### ISSUE TITLE
Feature: do not hit cache if transform is affected by env variables

### ISSUE THREAD

**Issue by slorber** [facebook/metro#105]
I have a file in my app which for the same input, can lead to different outputs, according to an environment variable and a babel plugin.

```javascript
import codegen from 'babel-plugin-codegen/macro';

export const isExpoDetached = !!process.env.EXPO_DETACHED;

console.debug(`isExpoDetached? => ${isExpoDetached}`);

codegen`
if (process.env.EXPO_DETACHED) {
  module.exports =
    "export { default as Intercom } from 'react-native-intercom';" +
    "export { default as OneSignal } from 'react-native-onesignal';";
} else {
  module.exports =
    'export const Intercom = undefined;' +
    'export const OneSignal = undefined;';
}
`;
```

**What is the current behavior?**

These 2 produce the same output (unwanted)

```
EXPO_DETACHED=true react-native bundle --entry-file node_modules/expo/AppEntry.js --bundle-output test.txt
react-native bundle --entry-file node_modules/expo/AppEntry.js --bundle-output test2.txt
```

These 2 produce different outputs (wanted)

```
EXPO_DETACHED=true react-native bundle --entry-file node_modules/expo/AppEntry.js --bundle-output test.txt --reset-cache
react-native bundle --entry-file node_modules/expo/AppEntry.js --bundle-output test2.txt  --reset-cache
```

**What is the expected behavior?**

These 2 should produce different outputs without requiring `--reset-cache` option.

```
EXPO_DETACHED=true react-native bundle --entry-file node_modules/expo/AppEntry.js --bundle-output test.txt
react-native bundle --entry-file node_modules/expo/AppEntry.js --bundle-output test2.txt
```

--------------------

I don't know exactly how this can be solved.

Maybe we can list as packager options which environment variables do affect the build, so that metro can infer a new `cacheVersion` if any environment variable has changed?

Maybe we could add a hint in a specific file to say to Metro to never cache this specific file?

**Comment by rafeca** [comment]
if you define a custom transformer, you can define a `getCacheKey()` function to invalidate the cache results.

In case you're not using a custom transformer, you can create a custom one that just redirects the transformation to the standard transformer, but overrides the cache key by adding your ENV variable

**Comment by slorber** [comment]
Thanks

As I'm using Expo I'll have to check how I can provide a custom transformer. If you have any hint on how to do that with Expo don't hesitate :)

**Comment by rafeca** [comment]
@slorber: I'm not very familiar on how to customize the transformer from expo, but I'm sure it's possible. I'm closing this issue, feel free to reopen if using the `getCacheKey()` method does not work for you

**Comment by slorber** [comment]
Hi @rafeca sorry to come back 2 years later on this issue :D 

Is `getCacheKey` documented anywhere? 

Tried to look at example transformers online like the typescript one, the default one but was not able to understand how to do what you suggest here:

> In case you're not using a custom transformer, you can create a custom one that just redirects the transformation to the standard transformer, but overrides the cache key by adding your ENV variable

As far as I understand the cache key is global for the transformer. What I want is to be able to disable the cache for specific files only (for example, the ones that are filename.noCache.js or whatever file pattern)
