### ISSUE TITLE
Trying to use `unstable_enableSymlinks: true` in yarn workspace monorepo with `react-native: 0.72.3`

### ISSUE THREAD

**Issue by cbdeveloper** [facebook/metro#1053]
**Do you want to request a *feature* or report a *bug*?** 

possilbe bug

**What is the current behavior?** 

Metro does not seem to be following my symlinked package (yarn workspace monorepo) even though I've activated the `unstable_enableSymlinks: true` option in the config.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

I've created a repo to reproduce the issue:

https://github.com/cbdeveloper/rep-react-native-072-symlinks-monorepo

**What is the expected behavior?**

This repo is a reproducible example of a GitHub issue.

# To reproduce it

- Clone the repo
- `yarn install`
- `cd apps/myapp`
- `yarn run android`

See the [metro.config.js](./apps/myapp/metro.config.js) file, and toggle between options 1 and 2.

```
const config = {
  // OPTION 1 - DOES NOT WORK
  // resolver: {
  //   unstable_enableSymlinks: true,
  // },

  // OPTION 2 - WORKS
  watchFolders: [
    path.resolve(__dirname, './node_modules/@my-app/foo')
  ]
};
```

## Monorepo structure

This is the intended project structure:

- apps
  - Deployable applications
- packages
  - Shared packages

Apps should be able to import and build code from the shared packages.

## nohoist

this project workspace is using `"nohoist": [ "**" ]`, as I had some errors when trying to `yarn run android` without it.

##  `unstable_enableSymlinks` issue

After reading the following article, I was under the impression that the only thing I had to do was to add `resolver: { unstable_enableSymlinks: true }` to my Metro config and everything would work.

[React Native 0.72 - Symlink Support, Better Errors, and more](https://reactnative.dev/blog/2023/06/21/0.72-metro-package-exports-symlinks#enabling-beta-features)

This is the import I'm making in `App.tsx`:

```
import { FOO } from '@my-app/foo';
```

Note: `@my-app/foo` is listed as a dependency of `myapp` and I can correctly see the symlink on `myapp` `node_modules` added by the yarn workspace.

Unfortunately, when I tried that, I got the following error:

> error: Error: Unable to resolve module @my-app/foo from /apps/myapp/App.tsx: @my-app/foo could not be found within the project or in these directories:
  node_modules
  ../../node_modules

Meaning Metro it's not following symlinks correctly.

The weird thing is that if I remove the `unstable_enableSymlinks` resolve config and simply add the path as a watch folder, it works.

This works:

```
watchFolders: [
  path.resolve(__dirname, './node_modules/@my-app/foo')
]
```

This does not work:

```
resolver: {
  unstable_enableSymlinks: true,
}
```

**Questions:**

- Am I doing some wrong here?
- I also tried it with `projectRoot: path.resolve(__dirname, '../..'),` and I got the same error.
- Is there any documentation on the `unstable_enableSymlinks` config? I didn't find anything on [metro docs](https://facebook.github.io/metro/docs/local-development).

Thank you

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

```
MacOS Ventura 13.5
node v16.17.1
yarn 1.22.19
"react": "18.2.0",
"react-native": "0.72.3",
"metro-core": "0.76.7" (installed by react-native)
```

**Comment by robhogan** [comment]
Hi @cbdeveloper - sorry for not getting to this sooner.
 - [`unstable_enableSymlinks` is now documented.](https://facebook.github.io/metro/docs/configuration/#unstable_enablesymlinks-experimental)
 - It is still necessary for all of your source to be watched (`watchFolders` or `projectRoot`) to be able to resolve it. Enabling symlinks will mean that Metro traverses symlinks during module resolution within watched folders, it's not a mechanism for resolving files outside watched folders.

The reason your Option 2 works on its own is through [Haste (global) package resolution](https://facebook.github.io/metro/docs/resolution#resolve_haste), where any `package.json` outside `node_modules` is considered "global" and may be resolved from anywhere. This is a non-standard legacy behaviour and will be disabled by default from RN 0.79 (where symlink support is also enabled by default).
