### ISSUE TITLE
RuntimeError: abort(Error: EPERM: operation not permitted, lstat '~App.js'). Build with -s ASSERTIONS=1 for more info.

### ISSUE THREAD

**Issue by kriit24** [facebook/metro#1056]
Last few days i get very often error: RuntimeError: abort(Error: EPERM: operation not permitted, lstat 'App.js~'). Build with -s ASSERTIONS=1 for more info.

It just aborts with that error.

metro version 0.7.0
"react": "18.2.0",

**Comment by robhogan** [comment]
This looks like a duplicate of https://github.com/facebook/metro/issues/1001, which was fixed in Metro 0.76.7+.
