### ISSUE TITLE
Publish properly version 0.78.0

### ISSUE THREAD

**Issue by Romick2005** [facebook/metro#1057]
```npm outdated:```

![image](https://github.com/facebook/metro/assets/17779660/00dfe91f-65c5-4583-ad3d-f256151b5a14)

**Comment by huntie** [comment]
Done ✅ This was related to yesterday's 0.76.8 hotfix — where the `latest` pointer couldn't be retargeted at `0.78.0` because this package was removed after `0.77.0` (now set).
