### ISSUE TITLE
Metro not supporting the  `satisfies`  operator (TypeScript 4.9)

### ISSUE THREAD

**Issue by JDMathew** [facebook/metro#1065]
**Bug**

I'm running react native 0.72.3. When adding satisfies keyword to a type it causes bundle compilation failure. The error is a bit nondescript:

` ERROR  [Error: Exception in HostFunction: Compiling JS failed: 20:5:')' expected at end of parenthesized expression Buffer size 4754 starts with: 5f5f642866756e6374696f6e2028676c]`

To repoduce just add `satisfies` to any type.

```
"react-native": "0.72.3",
"@react-native/metro-config": "^0.72.9",
"metro-react-native-babel-preset": "0.76.7",
```

Metro version from RN: "version": "0.76.7",

node:  v16.15.1

**Comment by JDMathew** [comment]
I believe the issue is with the version of `@babel/plugin-transform-typescript` which is a  dependency of `metro-react-native-babel-preset` in `metro`

**Comment by anthonyespirat** [comment]
upgrade `metro-react-native-babel-preset` to 0.77 seem to fix the issue for me

**Comment by robhogan** [comment]
Can you still reproduce after deleting any package lock file and reinstalling `node_modules`?

It looks like `satisfies` support is present in newer Babel, and you should get the newest Babel packages by reinstalling (Metro doesn't pin to an older version).

**Comment by JDMathew** [comment]
@robhogan thanks this fixes the issue.
