### ISSUE TITLE
unstable_enablePackageExports doesn't work with local packages

### ISSUE THREAD

**Issue by adamdebono** [facebook/metro#1073]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The new `unstable_enablePackageExports` resolver configuration doesn't with npm "workspaces". In my testing I have found this applies to any package that uses a symlink, including `npm link`ed packages.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

https://github.com/adamdebono/metro-packages-bug

It uses npm, but you can observe the error with the following:

```sh
$ npm install
$ npx metro get-dependencies app/src/index.js
```

**What is the expected behavior?**

In the sample project, I have a root package, with two sub-packages setup using NPM workspaces. The result of this is a shared `node_modules` folder, which includes symlinks to both packages. The package named "app" depends on the package named "module", with the latter utilising the "export" key in it's package.json.

I have enabled both package exports and symlinks in the config:

```js
module.exports = {
  "resolver": {
    "unstable_enableSymlinks": true,
    "unstable_enablePackageExports": true
  }
}
```

When running the script using Node, it successfully compiles the import and runs the script.

```sh
$ node app/src/index.js
Hello, World!
```

When attempting to bundle the project with Metro, it fails resolving the module.
```sh
$ npx metro get-dependencies app/src/index.js
Error: While resolving module `test-module/module`, the Haste package `test-module` was found. However the module `module` could not be found within the package. Indeed, none of these files exist:

  * `/test/module/module(.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)`
  * `/test/module/module/index(.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)`
    at resolveHasteName (/Users/debono/Developer/test/node_modules/metro-resolver/src/resolve.js:218:9)
    at Object.resolve (/Users/debono/Developer/test/node_modules/metro-resolver/src/resolve.js:92:20)
    at ModuleResolver.resolveDependency (/Users/debono/Developer/test/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:86:31)
    at DependencyGraph.resolveDependency (/Users/debono/Developer/test/node_modules/metro/src/node-haste/DependencyGraph.js:282:43)
    at Object.resolve (/Users/debono/Developer/test/node_modules/metro/src/lib/transformHelpers.js:170:21)
    at Graph._resolveDependencies (/Users/debono/Developer/test/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule (/Users/debono/Developer/test/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._traverseDependenciesForSingleFile (/Users/debono/Developer/test/node_modules/metro/src/DeltaBundler/Graph.js:249:5)
    at async Promise.all (index 0)
```

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

Node: 18.17.1
NPM: 9.6.7
Metro: 0.78.1
OS: macOS 13.5 (ARM)

**Comment by robhogan** [comment]
Hi @adamdebono - thanks for the report and repro. 

It looks like what's happening here is that `test-module` is being resolved as a [Haste ("global") package](https://facebook.github.io/metro/docs/resolution#resolvehastepackage-string--string), which takes precedence over Node-style resolution and does not support package exports, only simple subpath resolution:

https://github.com/facebook/metro/blob/cf7aa7749e58aa5ecee11a6db1c90ef36ab45f3b/packages/metro-resolver/src/resolve.js#L208-L209

We're phasing out Haste packages even at Meta, and AFAIK they're basically unused by the community (except unknowingly, like this) so I wouldn't be confident we'll add `package.json#exports` support for them in the near future. Instead, you'd be better off disabling Haste and using standard Node resolution via symlinks (as, I guess, you intended anyway).

From Metro 0.79.0, Haste packages are disabled by default, and we'll have an [`enableGlobalPackages`](https://facebook.github.io/metro/docs/configuration#enableglobalpackages) flag. Unfortunately in previous versions it's not quite so straightforward to disable them, but you can still effectively do so with a custom resolver that stubs out `resolveHastePackage`:

```js
module.exports = {
  resolver: {
    unstable_enableSymlinks: true,
    unstable_enablePackageExports: true,
    resolveRequest: (context, moduleName, platform) =>
      context.resolveRequest(
        { ...context, resolveHastePackage: () => null },
        moduleName,
        platform,
      ),
  },
};
```

HTH

**Comment by adamdebono** [comment]
Thanks @robhogan for the info. I've updated to 0.79.0 and it's now working for me. As someone new to the world of javascript bundlers, I'm sure you can understand this was very confusing for me so I'm happy to hear that this has been resolved by default in the latest version.

**Comment by robhogan** [comment]
You wouldn't have to be new to bundlers to find Haste packages surprising - they're very weird and afaik unique in the ecosystem, but we needed stable symlink support before we could switch them off. Glad that's done now and 0.79.0 is working for you :)

**Comment by robhogan** [comment]
You wouldn't have to be new to bundlers to find Haste packages surprising - they're very weird and afaik unique in the ecosystem, but we needed stable symlink support before we could switch them off. Glad that's done now and 0.79.0 is working for you :)
