### ISSUE TITLE
Generated source map includes assets data

### ISSUE THREAD

**Issue by janicduplessis** [facebook/metro#109]
I noticed my app's source maps size was huge (over 100mb) recently and managed to track it down to a video asset that has its whole content included in the source map file.

**What is the current behavior?**

require'ing a video asset causes its whole binary content to be embedded in the bundle source map.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

https://github.com/janicduplessis/metrobug, yarn test -> notice .map file size.

**What is the expected behavior?**

Source map should not include binary assets

**Metro version**
0.24.1

**Comment by rafeca** [comment]
Thanks for reporting! I've been able to reproduce it, I'm going to send a fix soon

Happy new year btw! 🎉

**Comment by janicduplessis** [comment]
👍 Happy new year to you and the metro team!
