### ISSUE TITLE
Can't debug app anymore on xcode 15

### ISSUE THREAD

**Issue by dejawho** [facebook/metro#1110]
Hi,
I'm on metro 0.76.8, react native 0.72.5 and I'm trying to setup the sample project from React Native Cli Quickstart.
When I run the project with yarn ios it is actually builded and run on the connected iPhone, but I don't get which metro is using, the app doesn't seem to get any change that is made (even if I reload it from the debug menu on the device) and I don't get any error message. During the build process a console with metro is opened but it seems completely detached from the app. Where I can find the metro used by the app?

**Comment by Colemartindale** [comment]
I am having a similar issue.
I am using apple silicon M1 Chip
I am using RN 0.72.5
Metro 0.76.8
I set the port in my package.json when I run on IOS Simulator like so
```
    "ios": "react-native run-ios --port 8088 --simulator='iPhone 15'",
```
I ensure that all RN default ports of 8081 have been switched to 8088.

but I constantly get the warning:
"warn No apps connected. Sending "reload" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB."

I have tried resetting the cache, resetting watchman, deleting the build, dependencies and reinstalling. Also restarting my computer.

Here is what my Metro.config.js looks like:

```
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
@type {import('metro-config').MetroConfig}
 */
const config = {
  server: { port: 8088, },
};
module.exports = mergeConfig(getDefaultConfig(__dirname), config);
```

Any suggestions would be greatly appreciated

**Comment by mmilvydas112** [comment]
Having same issue. Sonoma 14, XCode 15, working on android Emulator and real device fine, iOS working on Simulator, but not on real device. Keep getting same thing:
"warn No apps connected. Sending "reload" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB."

Tried fresh project, doesn't help and issue persists

**Comment by ysfzrn** [comment]
I am having a similar issue too. Did you find any solution ?

**Comment by ysfzrn** [comment]
I updated my node.js version with nvm and my problem resolved

**Comment by kocendavid** [comment]
@ysfzrn What version are you currently at?

**Comment by ysfzrn** [comment]
There are several projects I'm working on 
Minimum versions "react-native": "0.72.5",, "@react-native/metro-config": "0.72.11",
Highest versions "react-native": "0.73.1",, "@react-native/metro-config": "^0.73.2",

But versions are not so important. I think using the same network and updating node.js is critical.

**Comment by kocendavid** [comment]
@ysfzrn sorry I didnt express myself fully. I meant node version. But I have the latest so I dont think thats a problem also my phone and pc are connected with cable.

**Comment by ysfzrn** [comment]
@kocendavid  Even if connected with a cable, the computer and the phone, should be on the same local network.

Additionally, I set the Node version with NVM. I usually use the latest version. Have you tried installing NVM? Because as I mentioned above, my issue was resolved after using NVM.

**Comment by Koxx3** [comment]
I have the same issue with : 
- react native latest (0.73.x)
- sonoma VM (with bridge network, so, yes it's on the same network)
- xcode 15.2
- iphone 10 in IOS 16.7.5

I can acces metro url from iphone safari.
It loads datas but it stays stuck after "building 100%" and doesn't attach the metro logger.

I've updated node, no change.

Any idea ?

**Comment by divyegd** [comment]
@Koxx3 What version of Node did you update to?
