### ISSUE TITLE
Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found

### ISSUE THREAD

**Issue by liuyunqiang** [facebook/metro#1121]
Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found

**Comment by MuhammadMahrash** [comment]
I have also the same issue arriving.
Is someone fix this issue??

**Comment by vagnerlandio** [comment]
I have the same problem, I believe it is related to react-native-flipper

**Comment by torrrrzz** [comment]
Hi anyone solve the problem? I have the same problem

**Comment by matifriaz** [comment]
Hi, I am also getting this error on Xcode 15 and React native 0.73.3. Did anyone fix this?
