### ISSUE TITLE
Clicking Learn More on metro site gives 404

### ISSUE THREAD

**Issue by codypearce** [facebook/metro#114]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Go to https://facebook.github.io/metro/ and click "Learn more", you will be redirected to https://facebook.github.io/metro/docs/en/snapshot-testing.html which sends a 404

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

**What is the expected behavior?**
No
**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

**Comment by rafeca** [comment]
Thanks for reporting! The website still needs some work :)

We should point the "Get started" link to https://facebook.github.io/metro/docs/en/getting-started.html and the "Learn more" to https://facebook.github.io/metro/docs/en/api.html

Do you want to send a PR for it? 😃 The relevant code is in https://github.com/facebook/metro/blob/master/website/pages/en/index.js
