### ISSUE TITLE
Property "watcher.unstable_workerThreads" shows warning message when running Metro

### ISSUE THREAD

**Issue by krisisav** [facebook/metro#1143]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When running Metro, this warning appears in Terminal:
`Unknown option "watcher.unstable_workerThreads" with value false was found. This is probably a typing mistake. Fixing it will remove this message.`

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
Upgraded `@react-native/metro-config` dependency to latest version: 0.73.2
Ran `npm install` (and `pod install` for iOS project)
Ran Metro via `npm run react-native start`

**What is the expected behavior?**
No warnings

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
metro.config.js:
```
const path = require("path");

const { getDefaultConfig, mergeConfig } = require("@react-native/metro-config");
const defaultSourceExts = require("metro-config/src/defaults/defaults").sourceExts;
const defaultAssetExts = require("metro-config/src/defaults/defaults").assetExts;

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import("metro-config").MetroConfig}
 */

const sharedFolderPath = path.resolve(__dirname, "../shared");

module.exports = mergeConfig(getDefaultConfig(__dirname), {
  transformer: {
    babelTransformerPath: require.resolve("react-native-svg-transformer"),
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
  resolver: {
    assetExts: defaultAssetExts.filter((ext) => ext !== "svg"),
    sourceExts: [...defaultSourceExts, "svg"],
  },
  watchFolders: [sharedFolderPath],
  projectRoot: path.resolve(__dirname),
  server: {
    port: 8901,
  },
});
```

npm v9.6.7
node v20.0.3
MacOS Sonoma v14.0

**Comment by robhogan** [comment]
Hi @krisisav 

> Upgraded @react-native/metro-config dependency to latest version: 0.73.2

You don't mention your React Native version but this looks like the problem - the config you're referring to is new, and not yet available in the version of Metro used by any stable release of `react-native`. Apologies for the confusion. Please use a version with a minor matching whatever version of `react-native` you're using, or let us know if you *are* on a 0.73 RC.

CC @huntie for process follow-ups next half:
 - These packages shouldn't be tagged `latest` and shouldn't have stable releases before 0.73 final (12k downloads of [`@react-native/metro-config`](https://www.npmjs.com/package/@react-native/metro-config?activeTab=versions) **0.74.0** is must be causing issues for folks somewhere).
 - More generally, if we don't want folks to use `@react-native/foo@^0.X.0` with `react-native@^0.Y.0`, we should be enforcing that with a runtime check and/or `peerDependencies`.

**Comment by krisisav** [comment]
Thank you for the fast response @robhogan 
Indeed, we are using `react-native` v0.72.7
Seems good to note here though: before our latest dependency upgrades, we used to have `react-native` v0.72.5 in combination with `@react-native/metro-config` v0.73.2 (so no major updates were applied)

**Comment by robhogan** [comment]
> We used to have react-native v0.72.5 in combination with @react-native/metro-config v0.73.2 (so no major updates were applied)

Indeed, YMMV when using non-matching versions - 0.73.x isn't guaranteed to be compatible with 0.72.y, but might happen to be compatible for some patch versions, particularly early ones close to the cut. 

In general with React Native you should ensure that any `@react-native/*` dependencies are aligned with `react-native` in their minor (middle) version - that's the context in which they're developed and tested.
