### ISSUE TITLE
[Question]: Why is Metro hot update not affected by project size, as always fast

### ISSUE THREAD

**Issue by SnowingFox** [facebook/metro#1149]
So sorry to create a issue to ask question, but this question has been bothering me for a long time. 
I searched a lot of information but couldn't find the answer.

I just want to know why metro hot refresh is so fast not affected by project size, is Metro implement a bundle less technology by utilizing the features of browser esmodules like Vite?

**Comment by robhogan** [comment]
Hey @SnowingFox - sorry for not getting to this sooner - this is a nice question to be asked!

Metro is designed to work for very large codebases - eg about 200,000 JS files at Meta. We *don't* use ESM, but when a file is changed we bundle only the changed part of the graph and deliver that (the "delta bundle") to the client, which then applies the module changes using React's Fast Refresh capability.

You can read more about it (mostly from a client perspective) here: https://reactnative.dev/docs/fast-refresh

If you'd like a bit more insight into what Metro itself is doing, using a recent Metro version and starting with `DEBUG=Metro:* yarn start` will show you how it responds to changes and the number of added, modified, removed modules it's delivering to the client.

HTH - closing this issue for housekeeping but feel free to ask follow ups :)
