### ISSUE TITLE
error: bundling failed: SyntaxError: Unexpected reserved type (any, string, func, Boolean )

### ISSUE THREAD

**Issue by sundardsTechMind** [facebook/metro#1153]
<img width="1440" alt="error2" src="https://github.com/facebook/metro/assets/37631010/2fa4695d-e8dd-4e41-8c1b-f9464e1d8864">

File Name : AuthSignUpContainer.js:

I'm using This Package 

import PropTypes from 'prop-types';

error: bundling failed: SyntaxError: Unexpected reserved type any. (14)
error: bundling failed: SyntaxError: Unexpected reserved type func. (16)

13 | type Props = {

14 | AuthSignUpReducer: PropTypes.any,
| ^
15 | authSignUpReset: PropTypes.func,
16 | authSignUpDismissMessages: PropTypes.func,
17 | };

can anyone help me ASAP.

Thanks in advance.

**Comment by robhogan** [comment]
Hi @sundardsTechMind  - `propTypes` are for runtime checks, they're not Flow/TypeScript types (you can't use them within `type Foo = { ... }`). 

See https://legacy.reactjs.org/docs/typechecking-with-proptypes.html for how to use them, and try StackOverflow if you have further questions. 

Closing as this isn't a Metro issue.
