### ISSUE TITLE
Metro on Windows: Cannot start server in new window because no terminal app was specified

### ISSUE THREAD

**Issue by feng-yu-healthbank** [facebook/metro#1160]
**Do you want to request a *feature* or report a *bug*?**

Report a *bug*

It's originally raised in StackOverflow https://stackoverflow.com/questions/77684266/react-native-error-cannot-start-server-in-new-window-because-no-terminal-app-wa/77688826

**What is the current behavior?**

When launching Metro on **Windows**, it gets "error Cannot start server in new window because no terminal app was specified".

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

It's really just a fresh react-native project using the standard init.

```powershell
npx react-native@latest init AwesomeProject && cd ./AwesomeProject && npm run android
```

If you don't like to run it yourself, I have created a repo for you. No customization whatsoever, just a fresh react-native project.

https://github.com/feng-yu-healthbank/AwesomeProject

Please note the error is specific to Windows.

**What is the expected behavior?**

The empty project launches into an Android emulator by `npm run android`.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

It's a fresh official react-native sample project. No customization is applied.

Metro version
```
"metro": "^0.80.0"
```

metro config: 
```
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);
```

npx react-native info
```
System:
  OS: Windows 11 10.0.22621
  CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700K
  Memory: 27.55 GB / 63.77 GB
Binaries:
  Node:
    version: 20.10.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 9.7.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman:
    version: 20231008.002904.0
    path: C:\ProgramData\chocolatey\bin\watchman.EXE
SDKs:
  Android SDK:
    Android NDK: 22.1.7171670
  Windows SDK:
    AllowAllTrustedApps: Disabled
    Versions:
      - 10.0.19041.0
IDEs:
  Android Studio: AI-231.9392.1.2311.11076708
  Visual Studio: Not Found
Languages:
  Java: 17.0.9
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.1
    wanted: 0.73.1
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

![image](https://github.com/facebook/metro/assets/125230892/62629e9b-61e5-409d-9dfd-730bd24ea0dd)

**Comment by huntie** [comment]
Hey @feng-yu-healthbank, could you reopen this issue under https://github.com/react-native-community/cli? The `run-android` command and the `--terminal` option is part of that project, not in Metro.
