### ISSUE TITLE
Could not determine the dependecies of task ' :react-native-safe-area-context:generateDebugRFile' 


### ISSUE THREAD

**Issue by iamodreck** [facebook/metro#1162]
I had  just finished down loading packages related to navigation and on trying to reload my project, i got stuck on this and couldn't even find any possible solution on Google
Anybody got a clue?

**Comment by robhogan** [comment]
That looks like Android build output, referring to a Gradle task. Metro only deals with the JavaScript build.

You might get some help raising this on https://github.com/facebook/react-native , but please do follow the issue template and share as much information as you can. Try to reproduce the error in a minimal project you can open source.
