### ISSUE TITLE
Absolute Paths [global packages] are not working in React Native 0.73.1

### ISSUE THREAD

**Issue by prateekuttreja2020** [facebook/metro#1166]
### Description

Absolute Paths are not working in React Native 0.73.1

Error: undefined Unable to resolve module utility from /Users/apple/sample/App.tsx: utility could not be found within the project or in these directories:

### Steps to reproduce

1) Install Application
2) Notice Crash

### React Native Version

0.73.1

### Affected Platforms

Runtime - Android, Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 13.4.1
  CPU: (8) arm64 Apple M1
  Memory: 175.92 MB / 16.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9014738
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/local/opt/openjdk@17/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.1
    wanted: 0.73.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
Error: undefined Unable to resolve module utility from /Users/apple/sample/App.tsx: utility could not be found within the project or in these directories:
```

### Reproducer

https://github.com/prateekuttreja2020/sample

### Screenshots and Videos

![Simulator Screenshot - iPhone 14 Pro - 2024-01-05 at 17 50 34](https://github.com/facebook/react-native/assets/65911005/15394709-a3c5-40e3-a840-6b547ba3be17)

**Comment by robhogan** [comment]
Hi @prateekuttreja2020 - what you're describing there is known as a "global package" in Metro. Global package resolution is indeed disabled by default now, as a breaking change in Metro 0.79+ (React Native 0.73+). 

We felt it was rarely used, non-standard and more often led to confusion or issues with conflicts - it's also not natively understood by the likes of TypeScript, Jest or Node.js.

The **recommended** approach now that Metro supports symlink resolution is to make packages like your `utility` a [workspace](https://classic.yarnpkg.com/lang/en/docs/workspaces/). For example, if you're using Yarn v1, add `"workspaces": [ "src/utility" ]` to your root `package.json`, and run `yarn`. That creates a symlink at `node_modules/utility` to `../src/utility`, which Metro can follow as of React Native 0.73.

If you do still want to use global packages, you can enable it by setting [`resolver.enableGlobalPackages: true`](https://metrobundler.dev/docs/configuration/#enableglobalpackages) in your Metro config.

```js
// metro.config.js

const config = {
  resolver: {
    enableGlobalPackages: true,
    // ...
  },
  // ...
}
```

**Comment by sasweb** [comment]
@robhogan I am not that much into details about how metro works. But AFAIK know in previous RN versions we needed only to set paths in tsconfig.json to make absolute imports (aka aliases) work. Do I understand correct that this is not working anymore due to metro changes?

**Comment by robhogan** [comment]
Hi @sasweb - sorry for the delay. Metro itself(*) doesn't read `tsconfig.json`, and never has. If it appeared to work that way it was only because there was some overlap in certain setups between Metro global packages and TS `paths`, but they're really completely different mechanisms and never intended to mimic each other - there were always lots of cases where `tsconfig.json#paths` would work in TypeScript but not Metro.

(*) Expo CLI *does* support [`tsconfig.json#paths`](https://docs.expo.dev/guides/typescript/#path-aliases) via a custom resolver - that should still work, and is a much better solution than `enableGlobalPackages`. I'd still recommend using `workspaces` if possible though - that should work with zero config for every tool.

**Comment by AdrishS-AW** [comment]
Same issue, happened after upgrading from version 0.76.5 to version 0.78.3

Workspaces not working for me either
