### ISSUE TITLE
Cannot Conect Metro

### ISSUE THREAD

**Issue by Tasawar110110** [facebook/metro#1168]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

**What is the expected behavior?**

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

**Comment by Tasawar110110** [comment]
Slove my Issue

**Comment by robhogan** [comment]
Issue template ignored and there's no information here - closing.
