### ISSUE TITLE
web document link not correct

### ISSUE THREAD

**Issue by X-W-W** [facebook/metro#1171]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

ctrl K in https://metrobundler.dev/ link not correct

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

**What is the expected behavior?**

for example,
ctrl K search anything in docs, the url will be https://metrobundler.dev/metro/docs/***
but url should be  https://metrobundler.dev/docs/***

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

**Comment by robhogan** [comment]
Thanks for flagging this - we're following up with Algolia to get that changed.

**Comment by robhogan** [comment]
Now fixed, thanks again!
