### ISSUE TITLE
How to work with metro

### ISSUE THREAD

**Issue by jeremylbq** [facebook/metro#120]
I just don't how to work with metro after read the webSite and doc.

so , it's there anyone who can tell mw how to use it?how can i make a bundle by metro?

and,hope the update of metro-website

**Comment by rafeca** [comment]
Closing this, I hope that the test repo helps you

**Comment by wangliguang** [comment]
@rafeca   Can you provide a RN sample?  I run yarn build in my RN project and it always have troulbe. 
`Error: Expected path `/Users/wangliguang/Desktop/github/metroBoundleTest/index.js` to be relative to one of the project roots`

**thank you very much**

this my package.json:

<img width="1076" alt="2018-07-04 10 42 22" src="https://user-images.githubusercontent.com/11457074/42254001-0f03c18c-7f77-11e8-8718-6b3f6ea48528.png">
