### ISSUE TITLE
No matching version found for ob1@0.80.5

### ISSUE THREAD

**Issue by pandaCure** [facebook/metro#1200]

**Comment by robhogan** [comment]
This sounds like it might be related to [this week's release](https://github.com/facebook/metro/releases/tag/v0.80.5), but I don't see any issue with [`ob1@0.80.5` on npm](https://www.npmjs.com/package/ob1/v/0.80.5), and there's no other information here to go on.

I'm going to assume it was something transient - maybe a mirroring delay somewhere - and close. Please open a new issue with more information if you run into this again.
