### ISSUE TITLE
[Help Wanted] Need help with the blocklist option to exclude a folder from metro build

### ISSUE THREAD

**Issue by HardikGaur** [facebook/metro#1247]
**Do you want to request a *feature* or report a *bug*?**
I need some help with the blocklist option in resolver.

**What is the current behavior?**
I have a nonProdOptions folder that I want exclude from metro build for production version of the app. For this I am trying to use the blocklist option to exclude it from the build. But when I run the app and click on the button that leads to these screens, I am still able to go to that folder.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
Not a bug

**What is the expected behavior?**
The folder should be excluded and if we try to navigate to it it should throw error

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

Metro config: 
```
const { getDefaultConfig, mergeConfig } = require("@react-native/metro-config");
const exclusionList = require("metro-config/src/defaults/exclusionList");
require("@dotenvx/dotenvx").config();
const getconfig = () => {
  const modulesToBeExcluded = process.env.MODULE_EXCLUSION_LIST;
  const listOfExcludedModules = modulesToBeExcluded.split("|");
  console.log(listOfExcludedModules); //[ '*/nonProdOptions/.*' ]
]
  return {
    resolver: {
      blackListRE: exclusionList(listOfExcludedModules),
      blockList: exclusionList(listOfExcludedModules),
    },
  };
};

module.exports = mergeConfig(getDefaultConfig(__dirname), getconfig());
```
I am using dotenv to read from env file. This is the env variable defining the path to be excluded
`MODULE_EXCLUSION_LIST=*/nonProdOptions/.*`

node: v21.7.0
yarn : 1.22.19
metro: 0.76.8
macos: 14.4.1 (23E224)

If I am doing anything wrong any help will be appreciated. Thanks

**Comment by aleksamrakovic** [comment]
@HardikGaur did you happen to make it work? 
For me blockList doesnt actually work when i try like this

`resolver: {
    blockList: new RegExp(/\/__mocks__\/.*/),
  },`
