### ISSUE TITLE
"server.runInspectorProxy" warning after update to version "0.73.6" #233

### ISSUE THREAD

**Issue by fkazemi5236** [facebook/metro#1255]
I updated a React Native app to this version
"react-native": "0.73.6"
Everything works properly and there is no problem in running the program. But a warning is displayed in metro and because of this error, it does not allow me to create an app bundle :(

please help me to fix this issue
![Capture](https://github.com/facebook/metro/assets/46262018/d5b62319-20f9-48be-9636-2ce219e28c20)

**Comment by robhogan** [comment]
This looks like a Metro version mismatch - could you run `yarn why metro-config` and let us know the output?

**Comment by fkazemi5236** [comment]
> This looks like a Metro version mismatch - could you run `yarn why metro-config` and let us know the output?

Yes, Sure

`yarn why metro-config
yarn why v1.22.19
[1/4] Why do we have the module "metro-config"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "metro-config@0.80.8"
info Has been hoisted to "metro-config"
info Reasons this module exists
   - Hoisted from "metro#metro-config"
   - Hoisted from "react-native#@react-native#community-cli-plugin#metro-config"
info Disk size without dependencies: "108KB"
info Disk size with unique dependencies: "3.85MB"
info Disk size with transitive dependencies: "38.26MB"
info Number of shared dependencies: 141
=> Found "@react-native/metro-config#metro-config@0.76.9"
info Reasons this module exists
   - "@react-native#metro-config" depends on it
   - Hoisted from "@react-native#metro-config#metro-config#metro#metro-config"
Done in 14.27s.`

**Comment by fkazemi5236** [comment]
I fix this issue with this solution:

1. create a blank and new react-native-app with `npx react-native@latest init my-project`
2. check `package.json` file
3. Adapt part `devDependencies `of this file to your project and update the versions
