### ISSUE TITLE
React Native is not building since metro 0.24.5 has been released

### ISSUE THREAD

**Issue by SMJ93** [facebook/metro#126]
Since version `0.24.5` has been released we have been unable to run our react-native project on iOS and Android:

```
 BUNDLE  [android, dev] ./index.android.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

error: bundling failed: Error: invalid value for dynamic deps behavior: `null`
    at getDynamicDepsBehavior (/Users/user/Documents/app/applications/apps/product-mobile/node_modules/metro/src/JSTransformer/worker/index.js:185:13)
    at postTransform (/Users/user/Documents/app/applications/apps/product-mobile/node_modules/metro/src/JSTransformer/worker/index.js:131:26)
    at Object.transformCode [as transform] (/Users/user/Documents/app/applications/apps/product-mobile/node_modules/metro/src/JSTransformer/worker/index.js:251:17)
    at execMethod (/Users/user/Documents/app/applications/apps/product-mobile/node_modules/jest-worker/build/child.js:92:29)
    at process.on (/Users/user/Documents/app/applications/apps/product-mobile/node_modules/jest-worker/build/child.js:42:7)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at process.nextTick (internal/child_process.js:755:12)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
```

We reverted back to `0.24.4` and the app bundled as expected. 

Environment:

-  "react-native": "0.52.0"
-  "react": "16.2.0"

Let me know if you need any more details.

**Comment by rafeca** [comment]
Thanks for reporting! I'm looking into it

**Comment by thomasobrien99** [comment]
I am having the same issue. Thanks for the quick response!

**Comment by rafeca** [comment]
Sorry folks! This has been caused because we added a new config parameter to allow dynamic requires. But this new param is not handled by RN v0.52 and makes metro fail.

I'm going to publish a v0.24.6 version to fix that asap

**Comment by rafeca** [comment]
Version v0.24.6 published! Thanks for reporting it so fast 😄

**Comment by Danrrodrigues** [comment]
Thank you, I found the right time, I was having this error since yesterday.

**Comment by simlmx** [comment]
I had a similar error with `0.24.7`. Moving back to `0.24.6` fixed it.

**Comment by Harish-Hk** [comment]
Metro Bundler ready.

Loading dependency graph...
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)


i get this and the emulator screen shows nothing but "Loading from 10.0.2.2:8081" and nothing else...what do i do???
![screenshot_1526553174](https://user-images.githubusercontent.com/28500085/40235472-0103d88e-5ac8-11e8-90d1-6482b2cf7876.png)

**Comment by SMJ93** [comment]
@Harish-Hk delete the app from your simulator, run `git clean -xfd` (this removed all .gitignore files) from your project root before running your project again.

I've had this problem in the past and cleaning the project / simulator has fixed it for me!

**Comment by FrenchBully** [comment]
I'm still seeing this issue. None of the solutions above helped. 
Running Mojave 10.14, Xcode 10, React Native 0.57.3

<img width="380" alt="screen shot 2018-10-25 at 10 59 51 pm" src="https://user-images.githubusercontent.com/5194698/47547371-084b6980-d8aa-11e8-89c4-e4d62af70068.png">
<img width="560" alt="screen shot 2018-10-25 at 11 00 16 pm" src="https://user-images.githubusercontent.com/5194698/47547520-9c1d3580-d8aa-11e8-9d6e-530b9811adfe.png">

**Comment by sukhwinder-559** [comment]
ENOENT: no such file or directory, scandir '/Users/sukhwindersingh/iCloud Drive (Archive)/Documents/Project/assets'
Failed building JavaScript bundle.


this is the error i am getting please help me out here. 
earlier i was able ti run my same project but all of a sudden it stopped working. 

https://www.heypasteit.com/clip/0IT7NR﻿ 

this is my code for firebase authentication

used: firebase react-navigation native-base
![Screenshot 2019-09-09 at 3 48 14 PM](https://user-images.githubusercontent.com/32087224/64523611-4f9fe480-d31a-11e9-9e41-e731bcbc5b8f.png)

**Comment by Clarence0110** [comment]
Hello everybody, I am a total beginner in React-native. I am facing this issue now , I stuck at BUNDLE [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1) on window , and the emulator just keep on displaying loading from 10.0.2.2:8081... without displaying any thing . Please help me with this problem. I get stuck for one week already
![Screenshot_1575452106](https://user-images.githubusercontent.com/58074344/70131763-d405c780-16bd-11ea-88f5-aa0a91ee935a.png)
