### ISSUE TITLE
axios failed to load when enablePackageExports is true in monorepo

### ISSUE THREAD

**Issue by zgid123** [facebook/metro#1272]
**Do you want to request a *feature* or report a *bug*?**

I just wanna ask a solution, but there is no discussion in this project

**What is the current behavior?**

I am using expo monorepo, I create a custom metro config and enable package exports

```js
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

config.resolver.unstable_enablePackageExports = true;

module.exports = config;
```

When start the project, react-native will raise

```sh
The package at "node_modules/axios/dist/node/axios.cjs" attempted to import the Node standard library module "url".
It failed because the native React runtime does not include the Node standard library.
```

If I remove the `enablePackageExports`, it won't raise the error.

I tried to install the package `url`, but it will raise same error but for package `http`. This new error cannot be fixed even I install it

```sh
yarn add http
```

**What is the expected behavior?**

can use axios or is there any way to make `enablePackageExports` skip `axios` package only

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

node: v20.3.1
yarn: 4.2.2
metro: 0.80.9 (tried to install this one to know if it fixes the problem or not)

**Comment by danilaplee** [comment]
same problem here

**Comment by zgid123** [comment]
@danilaplee use this one

```js
config.resolver.unstable_conditionNames = [
  'browser',
  'require',
  'react-native',
]
```

**Comment by lxfaur** [comment]
Had the same problem:

```
The package at "node_modules\axios\dist\node\axios.cjs" attempted to import the Node standard library module "url".
It failed because the native React runtime does not include the Node standard library.
Learn more: https://docs.expo.dev/workflow/using-libraries/#using-third-party-libraries
  3 |
  4 | const FormData$1 = require('form-data');
> 5 | const url = require('url');
    |                      ^
  6 | const proxyFromEnv = require('proxy-from-env');
  7 | const http = require('http');
  8 | const https = require('https');
```

I noticed this problem only appeared after upgrading `typescript` from `5.1.3` to the latest version `5.9.3`.
Upgraded to 5.9.3 using `npx expo install typescript --dev` after upgrading `expo` from 50 to 54.

Reverted back and issue went away.
