### ISSUE TITLE
Metro choosing "import" over "react-native" package.json export when using unstable_enablePackageExports

### ISSUE THREAD

**Issue by sdcooke** [facebook/metro#1278]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

With:
- `unstable_enablePackageExports = true`
- `unstable_conditionNames = ["require", "import"]` (the default for Expo)
- `unstable_conditionsByPlatform` set to the default which includes `"react-native"` for iOS/Android

If a third party package has exports in its package.json that include both `"import"` and `"react-native"`, metro is choosing `"import"`. Changing `unstable_conditionNames` to `["react-native", "require", "import"]` does not change anything. Removing `"import"` fixes the import.

I discovered this whilst using `tamagui` (https://github.com/tamagui/tamagui/issues/2670) and am currently using the workaround:

```javascript
config.resolver.resolveRequest = (context, moduleName, platform) => {
  if (moduleName.startsWith("@tamagui/")) {
    return context.resolveRequest(
      {
        ...context,
        unstable_conditionNames: config.resolver.unstable_conditionNames.filter((condition) => condition !== "import"),
      },
      moduleName,
      platform,
    );
  }
  return context.resolveRequest(context, moduleName, platform);
};
```

which is similar to something metro does internally https://github.com/facebook/metro/blob/6856d00cfdddc1dd5ed9ab35249fe7ca1610ca75/packages/metro-resolver/src/resolve.js#L265

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

Use `npm create tamagui`, update metro.config.js with `config.resolver.unstable_enablePackageExports = true`, and running will produce the following logs:

```
warning: The package .../node_modules/@tamagui/create-theme contains an invalid package.json configuration. Consider raising this issue with the package maintainer(s).
Reason: The resolution for ".../node_modules/@tamagui/create-theme" defined in "exports" is .../node_modules/@tamagui/create-theme/dist/esm/index.mjs, however this file does not exist. Falling back to file-based resolution.
```

I have no managed to replicate the full import issue outside of my private repo but I think this illustrates the issue.

**What is the expected behavior?**

`"react-native"` should be chosen over `"import"` - OR it should be possible to order `unstable_conditionNames` and `unstable_conditionsByPlatform` to prioritise which export is chosen. Currently I think the order is lost because metro combines these options using a Set.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

This is the metro.config.js that `npm create tamagui` uses https://github.com/tamagui/starter-free/blob/main/apps/expo/metro.config.js - adding `config.resolver.unstable_enablePackageExports = true` is enough to get the logged warnings.

**Comment by robhogan** [comment]
Hi @sdcooke, thanks for opening this. Maybe counter intuitively, there is no ordering to asserted conditions - it's up to the package to list its exports in order and the first satisfied condition is the one used.

`@tamagui/constants/package.json` has:

```json
    ".": {
      "types": "./types/index.d.ts",
      "import": "./dist/esm/index.mjs",
      "require": "./dist/cjs/index.js",
      "react-native": "./dist/cjs/index.native.js"
    },
```

Metro is following the spec by choosing the first match, which is `import`. `react-native` will need to be moved higher up if that's the intention. See https://nodejs.org/api/packages.html#conditional-exports and in particular:

> Within the ["exports"](https://nodejs.org/api/packages.html#exports) object, key order is significant. During condition matching, earlier entries have higher priority and take precedence over later entries. The general rule is that conditions should be from most specific to least specific in object order.

**Comment by sdcooke** [comment]
Thanks @robhogan - that's actually a more elegant solution to the problem anyway - thank you for your response. Hopefully this issue will help anyone searching in future.
