### ISSUE TITLE
0.80.10 is not released on npm

### ISSUE THREAD

**Issue by efstathiosntonas** [facebook/metro#1313]
Yesterday 0.80.10 was released in [releases](https://github.com/facebook/metro/releases/tag/v0.80.10) pages but it's still not available on npm registry

**Comment by huntie** [comment]
Great catch! On it 🔧

**Comment by huntie** [comment]
I was a bit trigger happy yesterday and published the release before the bump commit (https://github.com/facebook/metro/commit/053764952127f46a9d078535dcedde7d8dc54ec2) had landed on `main`. Should now be deploying.

<img width="551" alt="image" src="https://github.com/user-attachments/assets/486d5e72-842b-41ed-a3e9-008fd9bf7a31">
