### ISSUE TITLE
Metro config warning has URL that gives a 404

### ISSUE THREAD

**Issue by leiflinse-trivector** [facebook/metro#1324]
**Do you want to request a *feature* or report a *bug*?**
Bug report

**What is the current behavior?**

```
=================================================================================================
warn From React Native 0.73, your project's Metro config should extend '@react-native/metro-config'
warn or it will fail to build. Please copy the template at:
warn https://github.com/facebook/react-native/blob/main/packages/react-native/template/metro.config.js
warn This warning will be removed in future (https://github.com/facebook/metro/issues/1018).

debug Reading Metro config from C:\path\to\project\metro.config.js
warn =================================================================================================
```

Opening the link https://github.com/facebook/react-native/blob/main/packages/react-native/template/metro.config.js gives a 404.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

```
cd android
gradlew assembleRelease
```

The warning message with the exact same link can also be observed in https://github.com/facebook/metro/issues/1018

**What is the expected behavior?**

Not to get a 404, but the actual example config that is referenced from the warning message

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
```
                Welcome to Metro v0.80.8
              Fast - Scalable - Integrated
```

**Comment by robhogan** [comment]
Thanks for letting us know and sorry about the bad link - that file moved to here:

https://github.com/react-native-community/template/blob/main/template/metro.config.js

CC @blakef for the broken link (emitted by RN rather than Metro, I think)
