### ISSUE TITLE
Missing LICENSE file in the repo of ver 1.9.2 and 2.0.0

### ISSUE THREAD

**Issue by itsuki-murata** [facebook/metro#1332]
Currently I'm using babel-preset-react-native version 1.9.2 and 2.0.0, but can't find a LICENSE file in the repo of ver 1.9.2 and 2.0.0.
Could you add the LICENSE file in the repo of ver 1.9.2 and 2.0.0?
Or is it possible to use the LICENSE file of the latest version as the license for ver 1.9.2 and 2.0.0?
Thanks in advance.

**Comment by robhogan** [comment]
Hi @itsuki-murata - do you have a link to what you're looking at? We've never published those version numbers for any Metro or React Native package.

**Comment by robhogan** [comment]
Ah I see, you must be referring to https://www.npmjs.com/package/babel-preset-react-native

That's been deprecated for many years, and we don't maintain it. Please use `@react-native/babel-preset` for RN >= 0.73, or `metro-react-native-babel-preset` for older versions.

**Comment by itsuki-murata** [comment]
Thank you for your reply.
I understand, I'll consider using metro-react-native-babel-preset or @react-native/babel-preset.
Thank you.
