### ISSUE TITLE
Wrong Platform.select on release build when using quotes on object keys

### ISSUE THREAD

**Issue by brunolemos** [facebook/metro#134]
Original issue reported on react-native repo: https://github.com/facebook/react-native/issues/17852

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`Platform.select({ 'ios': 1, default: 'default' })`
returns `ios` on debug build and `default` on release build.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const select1 = Platform.select({ ios: 'ios', default: 'default' })
const select2 = Platform.select({ 'ios': 'ios', default: 'default' })
const select3 = Platform.select({ 'ios': 'ios', 'default': 'default' })

alert(`OS: ${Platform.OS}, 1: ${select1}, 2: ${select2}, 3: ${select3}`)
// result on debug:   OS: ios, 1: ios, 2: ios, 3: ios
// result on release: OS: ios, 1: ios, 2: default, 3: undefined
```

**What is the expected behavior?**
`Platform.select({ 'ios': 1 })` work the same as `Platform.select({ ios: 1 })`.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
react-native 0.52.2
metro 0.24.7

**Comment by Panda-ref** [comment]
Same with dynamic properties
```
const PLATFORM_IOS =  "ios";
const PLATFORM_ANDROID = "android";
const value = Platform.select({
  [PLATFORM_IOS]: "ios-value",
  [PLATFORM_ANDROID]: "android-value"
});

// value transpiled to "void 0" in prod.js
```

**Comment by varungupta85** [comment]
I hope this issue only affects `Platform.select` calls and nothing else. I have dynamic properties at various places in my code.

**Comment by rafeca** [comment]
This only affects Platform.select indeed
