### ISSUE TITLE
No bundle URL present.  Make sure you're running a packager server or have included a .jsbundle file in your application bundle.

### ISSUE THREAD

**Issue by LukasB-DEV** [facebook/metro#1353]
### Description

I Upgraded my React Native Projekt from 0.74.5 to 0.75.2 and now I am not able to run the App on a real IOS Device. In Simulator all works fine. On my IPhone, build with XCode, I get this error:
![image](https://github.com/user-attachments/assets/be89a207-5029-47e6-a111-e5cf3c4b6f6d)

I already tried things from https://github.com/facebook/react-native/issues/26331#issuecomment-551065731 and added the Build step but this has not worked for me. 

### Steps to reproduce

1. Install React Native 0.74.5
2. Upgrade it to 0.75.2
3. try to run it on reals iPhone with XCode

### React Native Version

0.75.2

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.5
  CPU: "(8) x64 AMD Ryzen 7 5700X 8-Core Processor             "
  Memory: 798.54 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: /usr/local/opt/node@20/bin/node
  Yarn: Not Found
  npm:
    version: 10.8.2
    path: /usr/local/opt/node@20/bin/npm
  Watchman:
    version: 2024.08.26.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.2
    wanted: 0.75.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.
```

### Reproducer

[Repro](https://github.com/LukasB-DEV/failedprjekt)

**Comment by cortinico** [comment]
Passing over to the Metro team

**Comment by vchan023** [comment]
This may not be the fix for you but I was dealing with a similar issue, where metro would not see my real iPhone but worked with my simulator. I tried adding:

Privacy - Local Network Usage Description

to my info.plist to resolve another issue with local devices permissions pop up not appearing, and on the next 'yarn ios' metro successfully connected.

**Comment by cipolleschi** [comment]
Yes, it is related.
If you deny connection to local networks on your device, it will start not connecting to Metro server running locally.
Even if you go to settings and allow for network connection, it won't work right away.

The only solution seems to be:
1. enable local networks from the settings
2. **restart your phone**

I ended up in that scenario and restarting the phone solved it.
Apparently, [it is an iOS bug](https://stackoverflow.com/a/78458892/1117492).

**Comment by LukasB-DEV** [comment]
I have set Local network Usage Discription:
![image](https://github.com/user-attachments/assets/a0451101-8769-4090-aafd-1ad6352fac7a)

Local Networks from iPhone Settings are enabled but still the error. Or anything else i need to do?

**Comment by iliapnmrv** [comment]
@cipolleschi Hey! Do you have any ideas why can't I see setting `Local Network`? I think it is the reason in my case and probably in others. It is definitely debug build, not release

**Comment by iliapnmrv** [comment]
So solution for me was 
`Build Phases` -> `Bundle React Native code and images` -> disable `Run script: For install builds only` 
it was enabled on my side for some reason :(

**Comment by Gunndroid** [comment]
> So solution for me was `Build Phases` -> `Bundle React Native code and images` -> disable `Run script: For install builds only` it was enabled on my side for some reason :(

Thank you for this, actually gave up on a project for 2 weeks because I couldn't figure it out, working now because of this solution!

**Comment by AndrArajo** [comment]
I've had this problem for a few weeks and I've found the solution. For my project, the issue stemmed from how "Debug" was configured in the project.pbxproj file. The system was interpreting the debug mode as Release because GCC_PREPROCESSOR_DEFINITIONS was set with DEBUG=0, when it should have been DEBUG=1. I can search for the problem in this section.

GCC_PREPROCESSOR_DEFINITIONS = (
	"DEBUG=1",
	"$(inherited)",
);

**Comment by Alexufo** [comment]
@cipolleschi
 it also may need "Required background modes" at Plist and check "Remote notification" in Sign&Capabilites

**Comment by alainib** [comment]
> `Build Phases` -> `Bundle React Native code and images` -> disable `Run script: For install builds only`

it's look to work for me thanks a lot
be sure to use same wifi on mac & iphone ( like one on 2.5ghz and other on 5ghz dont work )

**Comment by alainib** [comment]
i still get this error times to times without knowing why. I tested all previous answer. 
even this who worked before 

>  Build Phases -> Bundle React Native code and images -> disable Run script: For install builds only


i need to restart the iphone & mac. change wifi and clean tmp folder and restart process to make it work

**Comment by atornatore** [comment]
For me it happened after updating Mac OS to Sequoia so I'm not sure it's an iOS issue.
I confirm no problems with simulators

**Comment by QasimRRizvi** [comment]
For anyone still searching for a solution

I've faced the same issue while running on a real iPhone. I was using react-native 0.72.7

The following fix worked for me.

In `AppDelegate.mm` file I updated following code

`return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];`
with this code

`return [NSURL URLWithString:@"http://192.168.x.x:8081/index.bundle?platform=ios"];`
Replace IP address with your IP address

**Comment by kyoung-jnn** [comment]
<img width="467" alt="Image" src="https://github.com/user-attachments/assets/396d85cc-cc69-4b8f-a6cb-3c521de9a7a9" />

In my case, add `export ENTRY_FILE='index.ts'` in **Bundle React Native code and images** and fix this issue

**Comment by alainib** [comment]
i get this issu since 2 days and now way to fix it
macos get update 
xcode too

not sur why i get it ( i tried many solutions but nothing worked )

@kyoung-jnn  i have this in "bundle react native code and images"
```
if [[ -f "$PODS_ROOT/../.xcode.env" ]]; then
  source "$PODS_ROOT/../.xcode.env"
fi
if [[ -f "$PODS_ROOT/../.xcode.env.local" ]]; then
  source "$PODS_ROOT/../.xcode.env.local"
fi

# The project root by default is one level up from the ios directory
export PROJECT_ROOT="$PROJECT_DIR"/..

if [[ "$CONFIGURATION" = *Debug* ]]; then
  export SKIP_BUNDLING=1
fi
if [[ -z "$ENTRY_FILE" ]]; then
  # Set the entry JS file using the bundler's entry resolution.
  export ENTRY_FILE="$("$NODE_BINARY" -e "require('expo/scripts/resolveAppEntry')" "$PROJECT_ROOT" ios absolute | tail -n 1)"
fi

if [[ -z "$CLI_PATH" ]]; then
  # Use Expo CLI
  export CLI_PATH="$("$NODE_BINARY" --print "require.resolve('@expo/cli')")"
fi
if [[ -z "$BUNDLE_COMMAND" ]]; then
  # Default Expo CLI command for bundling
  export BUNDLE_COMMAND="export:embed"
fi

`"$NODE_BINARY" --print "require('path').dirname(require.resolve('react-native/package.json')) + '/scripts/react-native-xcode.sh'"`
```

how to fix thanks ?

**Comment by cipolleschi** [comment]
Turn off your phone and turn it on again. I don't know why, this is probably an issue in iOS itself.

**Comment by alainib** [comment]
i ended even restarting the mac and iphone to make it work

**Comment by Asscher** [comment]
I'm having the same issue where a real phone doesnt work

this fixed it for me 
#https://github.com/facebook/metro/issues/1353#issuecomment-2559441300

**Comment by Asscher** [comment]
> For anyone still searching for a solution
> 
> I've faced the same issue while running on a real iPhone. I was using react-native 0.72.7
> 
> The following fix worked for me.
> 
> In `AppDelegate.mm` file I updated following code
> 
> `return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];` with this code
> 
> `return [NSURL URLWithString:@"http://192.168.x.x:8081/index.bundle?platform=ios"];` Replace IP address with your IP address

Having the same issue with a real device, this fixed it for me but is a workaround not permanent solution

**Comment by anujkumar09062001** [comment]
Update your physical ios device software to latest version.

**Comment by hari-mohan-choudhary** [comment]
No script URL provided. Make sure the packager is running or you have embedded a JS bundle in your application bundle.

unsanitizedScriptURLString = (null)
not able to fix this bug

**Comment by Shahrukh0396** [comment]
@hari-mohan-choudhary i am facing this exact error previously it was working fine and now i am facing this error have you able to resolve this?

**Comment by hari-mohan-choudhary** [comment]
@Shahrukh0396 Yes, I just replaced 'localhost' with the IP address (127.0.0.1), and it's working fine.

**Comment by SUBTAIN-ALI** [comment]
In my React Native project, I’m using:

```
"react": "18.2.0",
"react-native": "0.71.0"
```
To fix the issue, I modified the Build Phases > Bundle React Native code and images script in Xcode. Initially, it was set to:
```
export PATH=/opt/homebrew/bin:$PATH
export NODE_BINARY=node../node_modules/react-native/scripts/react-native-xcode.sh
```
I changed it to:

```
export PATH=/opt/homebrew/bin:$PATH
cd "$PROJECT_DIR/.."
export NODE_BINARY=node
./node_modules/react-native/scripts/react-native-xcode.sh
```

**Comment by flikQ** [comment]
Fro me this is occurring on release builds.

**Comment by jsamchineme** [comment]
I'm getting this issue on release builds as well.

**Comment by cipolleschi** [comment]
@flikQ @jsamchineme 

Release builds do not connect to metro by design. For release builds, we build the bytecode of JS and we ship the JS code as a resource inside the APK or the IPA. This is what your users expect: you should not allow them to connect to a bundler when they starts their app.

If you need to connect to metro to use fast refresh, build in debug mode.

**Comment by mtnt** [comment]
@cortinico you are right, however, the issue appears with release builds (I did it via xcode-project-archive).

[This](https://github.com/facebook/metro/issues/1353#issuecomment-2809972422) fix is about release build and I don`t know but mb it relates to typescript?

**Comment by cipolleschi** [comment]
I think the error you have in release is a different one.
If this is happening on an iOs device, you can try to build for Release using Xcode? In that way, Xcode should pause the app when it crashes and you should be able to see why it is crashing.

Btw I'm Cipolleschi, not Cortinico... 😅

**Comment by mtnt** [comment]
@cipolleschi omg, I`m sorry

I will try your idea later (about in a week, I guess). But I should tell that when I dug into the issue (at debug) I found a string "cant find index.js" or something like this. Thats why I decided to change `index.ts` to `index.js`. And this fixed the issue at production build.

**Comment by v-Cx** [comment]
For those who still have this problem. I've been having the same problem for a long time and I think it could possibly be the internet. Also “I don't know if it's possible but if you have filter/hide my ip on your phone” this could possibly have an effect.

When the problem was happening, the situation was as follows:
- Macbook connected to wifi (home wifi)
- Phone connected to wifi (home wifi) + phone connected to computer via usb

Here's what I did to solve the problem;
- I activated the personal access point from my iPhone
- I connected to my phone's internet from my Macbook

_At the moment_ the my bundle problem is solved.

**Comment by a-rostami** [comment]
@v-Cx is absolutely right. for me the problem was AP isolation was on for my modem settings that both my phone and mac was connected.

**Comment by Buddhaa97** [comment]
> So solution for me was `Build Phases` -> `Bundle React Native code and images` -> disable `Run script: For install builds only` it was enabled on my side for some reason :(

This worked!
Thanks

**Comment by barman47** [comment]
@Buddhaa97 worked for me as well. I've had this issue for about a week now.
