### ISSUE TITLE
React Native external permissions are not working  Please allow these permissions."

### ISSUE THREAD

**Issue by RuqayyaDbits** [facebook/metro#1362]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

**What is the expected behavior?**

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

**Comment by RuqayyaDbits** [comment]
React Native external permissions are not working for Mia. Please allow these permissions."
![619bb45b-720f-4ca4-a8e2-aff921293a75](https://github.com/user-attachments/assets/bbb854ea-9961-4ab4-ba62-9b194745c558)

**Comment by robhogan** [comment]
I don’t know what Mia is but this definitely doesn’t sound like a Metro issue, and the issue template has been ignored anyway. Closing.
