### ISSUE TITLE
Extranal Storage Premission Denied

### ISSUE THREAD

**Issue by RuqayyaDbits** [facebook/metro#1363]
Hi,
I have implemented external storage permissions in React Native, but I'm facing an issue where the storage permission is being denied. I've also tried using an older version of React Native. I think this might be a problem with the bechand. I have tried it on different laptops, but the issue persists. Please help me resolve this.
![619bb45b-720f-4ca4-a8e2-aff921293a75](https://github.com/user-attachments/assets/2e3af59e-e6be-410f-881c-856e905aab89)

**Comment by robhogan** [comment]
This isn’t anything to do with Metro, which is the JS bundler. 

You can try opening an issue in React Native but **you’ll need to provide a reproducible example and explain in detail what it is you’re doing** - there isn’t enough information here for anyone to help you.
