### ISSUE TITLE
Encountered issues when creating using the template, suspecting dependency conflicts

### ISSUE THREAD

**Issue by lapse12** [facebook/metro#1384]
**Describe the bug**
I strictly followed the document for the project initialization, but... As shown in the figures, "Disconnected from Metro (1001: "Stream end encountered")."

**Reproduction**
repo: https://github.com/lapse12/reproduction-of-nativewind-bug.git

I'd tried the following templates:

Create Expo Stack template:
`npx create-expo-stack@latest --nativewind --expo-router`(which in create-expo-stack branch)
and another which is `npx create-expo-app@latest`(which in main branch)

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
node: v20.14.0
npm: 10.7.0
OS: MacOS 15.1 Beta

**Comment by robhogan** [comment]
Hi @lapse12 - thanks for the report and repro repo.

> As shown in the figures, 

Did you mean to include screenshots, maybe? A few more details would be helpful, like a full stack trace if you have one, which platform you’re building for and whether you see this in a simulator/emulator or physical device.

**Comment by lapse12** [comment]
Thanks for your reply,
here is the figure.

<img width="375" alt="image" src="https://github.com/user-attachments/assets/1ff4a0b0-751b-4cfa-bcf1-a9030679ea19">

**Comment by lapse12** [comment]
I found that this issue does not occur after using the latest version of `npx create-expo-stack@latest`.
