### ISSUE TITLE
unknown command 'start'

### ISSUE THREAD

**Issue by virajdoshi11** [facebook/metro#1394]
**Do you want to request a *feature* or report a *bug*?**
Yes, I want to report a bug

**What is the current behavior?**
When I try to run my app with the command `npm start` or `npx react-native run-android` I get the error: `unknown command 'start'` or `unknown command 'run-android'`

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
I initially had some other settings in the `metro.config.js` and `babel.config.js` file which I have commented out and restored the default settings but it still shows the above error. So, the project is mostly the same project when downloaded the first time with the command `npx react-native init <project_name>`

my repository - https://github.com/virajdoshi11/Investigo

**What is the expected behavior?**
Run the code

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
This is my metro.config.js file:
```js
// import { getDefaultConfig, mergeConfig } from '@react-native/metro-config';

// /**
//  * Metro configuration
//  * https://reactnative.dev/docs/metro
//  *
//  * @type {import('metro-config').MetroConfig}
//  */

// const defaultConfig = getDefaultConfig(__dirname);

// const {
//   resolver: { sourceExts, assetExts },
// } = getDefaultConfig(__dirname);

// const config = {
//   transformer: {
//     getTransformOptions: async () => ({
//       transform:  {
//         experimentalImportSupport: false,
//         inlineRequires: true
//       },
//     }),
//     babelTransformerPath: require.resolve('react-native-svg-transformer'),
//   },
//   resolver: {
//     assetExts: assetExts.filter(ext => ext !== 'svg'),
//     sourceExts: [...sourceExts, 'svg']
//   }
// }

// export default mergeConfig(defaultConfig, config);

import { getDefaultConfig, mergeConfig } from '@react-native/metro-config';

/**
 * Metro configuration
 * https://reactnative.dev/docs/metro
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {};

export default mergeConfig(getDefaultConfig(__dirname), config);
```
The commented out code was my previous settings but it still doesn't work with the default ones.

Node version: `v22.11.0` (Have also tried with node version `20.10.0`)
NPM version: `10.9.0`

**Comment by robhogan** [comment]
Hi @virajdoshi11. Those aren’t Metro commands, I think you probably want to file this over at https://github.com/react-native-community/cli

**Comment by virajdoshi11** [comment]
Hi @robhogan , I apologize for opening this issue here. I'll delete it
