### ISSUE TITLE
Inline sourceMappingURL not generated

### ISSUE THREAD

**Issue by max-mironov** [facebook/metro#147]
Hi, noticed that latest version of MetroBundler doesn't add inlined sourceMappingURL at the bottom.
E.g. when running with `RN0.54` which uses `Metro 0.28.0` it doesn't generate it.

When hitting `http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false`
it produce the output but with no `sourceMappingURL` at the bottom.

Compare to RN0.53 which uses `Metro 0.24.7` it generate the following bottomline:
`//# sourceMappingURL=http://localhost:8081/index.map?platform=ios&dev=true&minify=false`

Is it desired behavior or something has changed in recent versions of metro bundler?

BTW seems that sourcemaps are available by hitting e.g. the following URL:
`http://localhost:8081/index.map?platform=ios&dev=true&minify=true&inlineSourceMap=false`
but where are the `sourceMappingURL` at the end?

I'm asking this because VSCode react-native extension relies on this logic [here](https://github.com/Microsoft/vscode-react-native/blob/6eeec3c0610e032491c57fe0fc3426016e5177ed/src/debugger/sourceMap.ts#L131), so would be good if there will be an option to generate it.

Thanks in advance for looking at!

**Comment by rafeca** [comment]
Thanks for reporting! This was fixed by 2b32b08b13e879c2d4f8f53299c2048653fc62e9, but we haven't released a new version of metro yet, I'm going to release 0.29.0 very soon

**Comment by max-mironov** [comment]
Thanks, looking forward for new release!

**Comment by rafeca** [comment]
Released 0.29.0 :)

**Comment by max-mironov** [comment]
Yay, much appreciated! 👍

**Comment by jdeanwaite** [comment]
Is there anyway to force react-native to use a specific version of metro?
