### ISSUE TITLE
Minification can break code (but cannot be disabled?)

### ISSUE THREAD

**Issue by haggholm** [facebook/metro#154]
In `metro`@0.24.7 (`react-native`@0.53.3), `src/JSTransformer/worker/minify.js`, and presumably in the latest version in `metro-minify-uglify`, the setting `mangle:{toplevel:true}` is passed to `uglify-es`. Unfortunately, this can break code—we have some stuff that breaks if certain React component names are mangled. Our web version uses a blacklist via `mangle:{reserved}`; with `metro`, we have to patch the transformer to stop breaking our app.

It would be great if uglify options could be configured for the transformer.

**Comment by ozalexo** [comment]
Workaround

We get it worked with additional NPM package "patch-package". On each install it applies the following patch:
```
patch-package
--- a/node_modules/metro-minify-uglify/src.real/minifier.js
+++ b/node_modules/metro-minify-uglify/src.real/minifier.js
@@ -34,7 +34,11 @@ function withSourceMap(

 function minify(inputCode: string, inputMap: ?BabelSourceMap) {
   const result = uglify.minify(inputCode, {
-    mangle: {toplevel: false},
+    mangle: {
+      toplevel: true,
+      safari10: true,
+      reserved: ["BigInteger", "ECPair", "Point"],
+    },
     output: {
       ascii_only: true,
       quote_style: 3,
--- a/node_modules/metro-minify-uglify/src/minifier.js
+++ b/node_modules/metro-minify-uglify/src/minifier.js
@@ -34,7 +34,11 @@ filename)

 function minify(inputCode, inputMap) {
   const result = uglify.minify(inputCode, {
-    mangle: { toplevel: false },
+    mangle: {
+      toplevel: true,
+      safari10: true,
+      reserved: ["BigInteger", "ECPair", "Point"],
+    },
     output: {
       ascii_only: true,
       quote_style: 3,
--- a/node_modules/metro-minify-uglify/src/minifier.js.flow
+++ b/node_modules/metro-minify-uglify/src/minifier.js.flow
@@ -34,7 +34,11 @@ function withSourceMap(

 function minify(inputCode: string, inputMap: ?BabelSourceMap) {
   const result = uglify.minify(inputCode, {
-    mangle: {toplevel: false},
+    mangle: {
+      toplevel: true,
+      safari10: true,
+      reserved: ["BigInteger", "ECPair", "Point"],
+    },
     output: {
       ascii_only: true,
       quote_style: 3,
```

**Comment by rafeca** [comment]
Hi! We recently added the `minifierConfig` config param in the transformer, which allows you to exactly do that 😄

**Comment by Overtorment** [comment]
Hey @rafeca, adding "metro" configuration to my package.json didnt help. Added:

```
  "metro": {
    "minifierConfig": {
      "mangle": {
        "toplevel": true,
        "reserved": [
          "BigInteger",
          "ECPair",
          "Point"
        ]
      }
    }
  },
```

But manually patching uglify-es/lib/minify.js metro-minify-uglify/src/minifier.js helps.

**Comment by ozalexo** [comment]
> Hey @rafeca, adding "metro" configuration to my package.json didnt help. Added:

According to the [docs](https://facebook.github.io/metro/docs/en/configuration) `minifierConfig` is Transformer option. Have you tried something like this?
```
"metro": {
  "transformer": {
    "minifierConfig": {
      "mangle": {
        "toplevel": true,
        "reserved": [
        "BigInteger",
        "ECPair",
        "Point"
        ]
      }
    }
  }
},
```

**Comment by skurgansky-sugarcrm** [comment]
using typeorm with react-native-sqlite-storage to build offline app. As i see it minifier.js brakes my code. I have error in release but no in dev mode. When i retured _ref from minify func i didn't have error either.

**Comment by skurgansky-sugarcrm** [comment]
I set to metro.config.js this code to avoid my mangle problem.

```
minifierConfig: {
      keep_classnames: true,
      keep_fnames: true,
      toplevel: false,
      compress: {
        toplevel: false,
        keep_classnames: true,
        keep_fnames: true,
      },
      mangle: {
        toplevel: false,
        builtins: false,
        keep_classnames: true,
        keep_fnames: true,
        properties: {
          keep_quoted: true,
        }
      },
    }
```

**Comment by chiaraperino** [comment]
@skurgansky-sugarcrm I have the same error in typeorm but I don't understand how you have resolve the issue.

I have added inside project metro.config.js file with:

```
module.exports = {
  metro: {
    transformer: {
      minifierConfig: {
        mangle: false,
      },
    },
  },
};
```

and inside app.json in expo obj:

```
"packagerOpts": {
      "config": "./metro.config.js",
      "projectRoots": ""
 }
```

but doesn't work.

Can you help me?

Thanks
Chiara

**Comment by skurgansky-sugarcrm** [comment]
@chiaraperino 
you can't turn off mangle. don't even try.
try to do this:
1) `yarn add -dev metro-minify-terser`
2) add to metro.config.js these lines:
```
minifierPath: 'metro-minify-terser',
    minifierConfig: {
      // https://www.npmjs.com/package/terser#mangle-options
      ecma: 8,
      keep_classnames: true,
      keep_fnames: true,
      module: true,
      mangle: {
        module: true,
        keep_classnames: true,
        keep_fnames: true,
      }
    }
```

worked for me. The problem was in metro-minify-uglify. it works over uglify-es when the latter works over terser.

**Comment by chiaraperino** [comment]
@skurgansky-sugarcrm thank you for your answer but I have another problem :(

I install metro-minify-terser ("metro-minify-terser": "^0.53.1") but, when I build the bundle, I have the error: 

node_modules/expo/AppEntry.js: minify.withSourceMap is not a function. (/node_modules/metro/src/JSTransformer/worker.js)

Have you encontered the same problem?

```
//metro.config.js
module.exports = {
  transformer: {
    minifierPath: 'metro-minify-terser',
    minifierConfig: {
      ecma: 8,
      keep_classnames: true,
      keep_fnames: true,
      module: true,
      mangle: {
        module: true,
        keep_classnames: true,
        keep_fnames: true,
      },
    },
  },
};
```

**Comment by skurgansky-sugarcrm** [comment]
nope. check if you use same version of metro packages: 0.53.1

**Comment by jrr** [comment]
For anyone happening upon this thread and feeling optimistic about the `metro-minify-terser` workaround above, note that the package was [removed](https://github.com/facebook/metro/commit/c97d0a4778a1311a41e7ce6a6f82e46ae8de001e) from this repo. If it happens to still work you probably shouldn't rely on it.

**Comment by skurgansky-sugarcrm** [comment]
How does it gonna work later ?

**Comment by Arlen22** [comment]
Put this in webpack.config.js in your project root directory. 

```
const createExpoWebpackConfigAsync = module.parent.require('@expo/webpack-config');

module.exports = async function(env, argv) {

  const config = await createExpoWebpackConfigAsync(env, argv);
  debugger;
  config.devtool = "source-map";
  return config;
}
```

**Comment by macfanatic** [comment]
This forum link solved it for me thankfully, with expo and typeorm.

https://forums.expo.io/t/change-minifierconfig-for-minify-uglify/36460/2

**Comment by chrisbobbe** [comment]
> For anyone happening upon this thread and feeling optimistic about the `metro-minify-terser` workaround above, note that the package was [removed](https://github.com/facebook/metro/commit/c97d0a4778a1311a41e7ce6a6f82e46ae8de001e) from this repo. If it happens to still work you probably shouldn't rely on it.

Looks like it was brought back: ccb735305a1e8822dd8dafb105170b21134b4cc0
