### ISSUE TITLE
Dependency Issue- Fresh NPM installs are not compatible with node 6

### ISSUE THREAD

**Issue by thomasobrien99** [facebook/metro#158]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Fresh NPM installs are not compatible with node 6

**If the current behavior is a bug, please provide the steps to reproduce.**

1. rm -rf node_modules
2. npm i
3. build project

-> ERROR unexpected token '**' (from ~babel/traverse)

This line https://github.com/facebook/metro/blob/master/packages/metro/package.json#L45 requires  `"@babel/traverse": "^7.0.0-beta"`. Version `"7.0.0-beta.43`" Is experiencing this issue: https://github.com/babel/babel/issues/7654

This may be the wrong place to open an issue, but I'm wondering if `metro` should be relying on `"babel": "^7.0.0-beta"` as this could happen again. This comment seems to indicate it is not recommended https://github.com/babel/babel/issues/7654#issuecomment-378020154.

**Comment by rafeca** [comment]
@qfox what do you think about upgrading the beta version of babel? Is it feasible? Another option as @thomasobrien99 mentions is to just depend on beta and lock the specific beta version via the yarn.lock file

**Comment by qfox** [comment]
If nothing else we should make sure our CI testing checks with node 6.

Beyond that we could lock down the version of babel to what it is when we bump. Especially while Babel 7 is still in beta.

Beyond that, these things are going to happen. We're in the process of migrating to Babel 7 so it's not going to go away :)

**Comment by rafeca** [comment]
We already run all the tests on node v6, I wonder why no test fails there...
