### ISSUE TITLE
Unable to import module from outside react native folder even with a symlink

### ISSUE THREAD

**Issue by Alphapage** [facebook/metro#159]
Issue related to https://github.com/facebook/react-native/issues/18725

- [ x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: Windows 10
  Node: 8.11.1
  Yarn: Not Found
  npm: 5.8.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4670197

Packages: (wanted => installed)
  react: ^16.3.1 => 16.3.1
  react-native: ^0.55.1 => 0.55.1

## Steps to Reproduce
In App.js, `import something from '../AnotherProject` . 
Execute `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/`

## Expected Behavior
react native should be able to import the index.js file

## Actual Behavior
Error: unable to find the module

Thank you in advance for your answers.

**Comment by tedtang77** [comment]
I have the same issue with the similar environment

**Comment by Alphapage** [comment]
Any news ?
It is impossible to develop a native module library using Windows 10 because of this symlink bug.

**Comment by Oblongmana** [comment]
Not sure on the situation around importing without a symlink, but metro has failed to follow symlinks since day 1 unfortunately - https://github.com/facebook/metro/issues/1. I'm currently trying to deal with similar issues :(
