### ISSUE TITLE
Slow packager loading on hard drive

### ISSUE THREAD

**Issue by lXSPandora** [facebook/metro#169]
When I run `yarn start -reset-cache` on my mac the metro-bundler takes a long time to make the Javascript bundle like more than 6 minutes

**Do you want to request a *feature* or report a *bug*?**

Im reporting a bug

**What is the current behavior?**

Packager takes too much time to make the Javascript Bundle

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

On a hard drive mac: 
react-native init Test
yarn install
react-native run-ios
yarn start --reset-cache

**What is the expected behavior?**

Load faster

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

Im using the default config that comes with react-native
yarn version 1.6.0
Mac OS High Sierra
16GB RAM i5
1TB Hard Drive

**Comment by cpojer** [comment]
This issue is not actionable. Please come back with a repository with code samples that we can yarn install and run that exhibits the problems you are outlining. Thanks!

**Comment by Gp2mv3** [comment]
I've the exact same problem. The build is taking ages. Even on a tiny project (create-react-native-app).
