### ISSUE TITLE
Metro Bundler ready.  Loading dependency graph... 

### ISSUE THREAD

**Issue by harish-madugula** [facebook/metro#172]
Metro Bundler ready.

Loading dependency graph...
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)
 i get this but no error.....the screen shows nothing but "Loading from 10.0.2.2:8081"
 and nothing else...
can anyone help me what the issue is about?
![screenshot_1526553174](https://user-images.githubusercontent.com/28500085/40235564-4fc4aa20-5ac8-11e8-97b0-a6acb445ed96.png)

**Comment by itti** [comment]
I get the same when using storybook.js

**Comment by sheghun** [comment]
Delete and create a new project from start

**Comment by robhogan** [comment]
Sorry we didn't get to this - closing as stale. If anyone else runs into it please open a new issue.
