### ISSUE TITLE
Import from parent directories

### ISSUE THREAD

**Issue by blaesus** [facebook/metro#179]
I'm trying to add React Native to a web project built with React+Redux, started with RN in mind, where reducers and assets were expected to be shared between web and mobile:

```
src
-- client
---- assets
---- reducers
---- web
---- mobile
-- definitions
-- server
```

`mobile` is the root directory of React Native, where I like to keep the mobile components. It is initialized with found instructions here: https://facebook.github.io/react-native/blog/2018/05/07/using-typescript-with-react-native.html

The problem I face is that I cannot import from source code in sibling or parent directories to `mobile` (for example, `client/reducers`).

I got the error that
```
bundling failed: Error: Unable to resolve module `../reducers` from `projects/materia/src/client/mobile/App.tsx`: The module `../reducers` could not be found from `projects/materia/src/client/mobile/App.tsx`.
```

I think the path string is correct because TypeScript check passes.

Importing from children directories of `mobile` works perfectly fine.

Is there any way I can isolate mobile configurations in a deep directory like this? Or is my only option initializing RN on the source root? 

I tried to consult [instruction for configuration of Metro](https://facebook.github.io/metro/docs/en/configuration.html#content), but couldn't find relevant information.

**Comment by rafeca** [comment]
Hey @blaesus !

When you run metro, you should see a message saying:

```
Looking for JS files in
   /pathA/
   /pathB/
   ...
```

Is the `reducers/` folder in that list? If it isn't, you should add it as a projectRoot. To do so, you should modify (or add, if it does not exist) a `getProjectRoots()` param in your `rn-cli.config.js` file.

Let me know if this helps

**Comment by blaesus** [comment]
@rafeca Sorry I've got other features blocking further diagnosis of this issue. I think your solution might work and I'll try it when I have the bandwidth. Thank you very much for the help. I'll close this issue for now.
