### ISSUE TITLE
How to decode sourcemap when use metro

### ISSUE THREAD

**Issue by mactive** [facebook/metro#184]
**Do you want to request a *feature* or report a *bug*?**

I want to resolve the problem.

**What is the current behavior?**

react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/ --sourcemap-output ./sourcemap/sourcemap.android.js

the sourcemap.android.js is more 11MB large . and json struct is very different with RN 0.45.1 sourcemap.

when i use  RN 0.45.1 the sourcemap.android.js file is just 2.7 MB large. and I can use npm  source-map to decode. after i update to 0.53.3 which use metro bundler. i can't decode the sourcemap.

here is my code 

how i use 
`node decodeSourceMap.js android crash.txt`

```
var sourceMap = require('source-map');
var fs = require('fs');
var readline = require('readline');
var filename = process.argv[3];
var platform = process.argv[2];

fs.readFile('./sourcemap.'+platform+'.js', 'utf8', function (err, data) {
  // var smc = new sourceMap.SourceMapConsumer(data);
  const consumer = new sourceMap.SourceMapConsumer(data);


  readline.createInterface({
    input: fs.createReadStream(filename),
    terminal: false
  }).on('line', function (line) {
    var regex = /.*@(\d+):(\d+)/g;
    var match = regex.exec(line);
    console.log(line);
    var realStack = consumer.originalPositionFor({
      line: match[1],
      column: match[2]
    });
    var filename = realStack.source.split('waimai_mfe_bee')[1]
    console.log(filename, realStack.line, realStack.column, realStack.name);
    console.log('\n');
  });
});
```

**Comment by mactive** [comment]
this is what I expected
![screen shot 2018-06-21 at 5 06 29 pm](https://user-images.githubusercontent.com/265410/41709343-86e8efda-7575-11e8-9a09-c03eb8781908.png)

**Comment by rafeca** [comment]
Hi @mactive ! We've done some recent fixes to the sourcemap generation in Metro, which should fix this issue. I'm gonna close it but feel free to reopen it if you still have some sort of issue with the latest Metro version
