### ISSUE TITLE
[META] conditional babel transpile

### ISSUE THREAD

**Issue by dulmandakh** [facebook/metro#190]
In version 0.56, iOS 9 is now the minimum required version. And on iOS 9, Webkit and JSC partially supports ES6 (https://webkit.org/blog/4054/es6-in-webkit/).

So it might be better to not transpile natively supported ES6 features to have native performance, smaller bundle size. Especially for release builds.

Relevant blog posts:

https://webkit.org/blog/4054/es6-in-webkit/
https://webkit.org/blog/6756/es6-feature-complete/
https://webkit.org/blog/7536/jsc-loves-es6/

**Comment by gengjiawen** [comment]
Also in andoid, the js engine maybe will support all es6 feature when use new jsc from https://github.com/react-community/jsc-android-buildscripts.

**Comment by rafeca** [comment]
Hey! You can already configure Babel to use the plugins/presets that you desire by creating a `.babelrc` file with the desired config (more info: https://babeljs.io/docs/en/babelrc).

We haven't planned yet to get rid of some of the ES6 transforms/polyfills on the default config, but it's something worth exploring. I'll update this task whenever I have time to check it

**Comment by gengjiawen** [comment]
@rafeca How do I enable different rules for iOS and Android ?

**Comment by satya164** [comment]
Maybe we could user Babel’s caller option for this? When metro uses Babel to transpile code, it could pass some info about the platform etc. and then we could conditionally return different configs: https://babeljs.io/docs/en/config-files#apicallercb

Implementation should be straightforward:

```js
babel.transformSync(code, {
    caller: { name: 'metro', platform },
    filename: this.filename,
    ...
})
```

**Comment by gengjiawen** [comment]
The api I want is that metro can know platform, so I can pass something like this in `.babelrc.js`
```
"ios": "10.3",
"android": {
    "plugins": [
        "@babel/plugin-transform-react-jsx",
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-transform-flow-strip-types",
        "@babel/plugin-transform-modules-commonjs"
    ]
}
```

**Comment by satya164** [comment]
@gengjiawen I think you can do the following with `caller`:

```js
module.exports = function(api) {
  const platform = api.caller(caller => caller.platform);

  if (platform === 'android') {
    // return config for Android
  }

  // return config for everything else
}
```

I think it's better to use existing Babel API instead of creating a new API for this

**Comment by gengjiawen** [comment]
@satya164 is working on new solution. Previous works due to some metro cache.
