### ISSUE TITLE
Transform Module Path documentation

### ISSUE THREAD

**Issue by yordis** [facebook/metro#191]
I have this config

```js
module.exports = {
  getTransformModulePath() {
    require.resolve("react-native-typescript-transformer");
    require.resolve("react-native-graphql-transformer");
  },
  getSourceExts() {
    return ["ts", "tsx", "graphql"];
  }
};
```

Basically I want to add Typescript and GraphQL transform from those packages.

I tried to find any information about transform because the issue I am facing right now is that I can only return a single transform so basically either Typescript or GraphQL but not both.

I don't know what to do because I dont understand what is the idea about this function, there is not documentation about it and every link on the internet either point me to something else or just using a single transformer.

**Comment by kristerkari** [comment]
@yordis You can do this:

rn-cli.config.js:

```js
module.exports = {
  getTransformModulePath() {
    require.resolve("./transformer.js");
  },
  getSourceExts() {
    return ["ts", "tsx", "graphql", "gql"];
  }
};
```
transformer.js:
```js
// For React Native version 0.56 or later
var upstreamTransformer = require("metro/src/reactNativeTransformer");

// For React Native version 0.52-0.55
// var upstreamTransformer = require("metro/src/transformer");

// For React Native version 0.47-0.51
// var upstreamTransformer = require("metro-bundler/src/transformer");

// For React Native version 0.46
// var upstreamTransformer = require("metro-bundler/build/transformer");

var typescriptTransformer = require("react-native-typescript-transformer");
var graphqlTransformer = require("react-native-graphql-transformer");

module.exports.transform = function({ src, filename, options }) {
  if (filename.endsWith('.gql') || filename.endsWith('.graphql')) {
    return graphqlTransformer.transform({ src, filename, options });
  } else if (filename.endsWith('.ts') || filename.endsWith('.tsx')) {
    return typescriptTransformer.transform({ src, filename, options });
  }
  return upstreamTransformer.transform({ src, filename, options });
};
```

**Comment by yordis** [comment]
@kristerkari is there any way this could be avoided?

I see what you are doing there but ... I would prefer to hide this complexity.

In any case, thank you very much for the details!

**Comment by kristerkari** [comment]
That's at least the only way I'm aware of. It would indeed be nice to do it in a simpler way.

**Comment by rafeca** [comment]
The current way to do this is how @kristerkari mentions, so unfortunately at the moment there's no easier way to do that.

We're at the moment improving the Metro APIs (we've just changed the config params format and added [some docs](https://facebook.github.io/metro/docs/en/configuration) for them), and we're considering better ways to configure the transformers.

BTW, the latest version of Metro has builtin typescript support 😄

**Comment by rafeca** [comment]
Closing this issue, since there is no action items atm

**Comment by yordis** [comment]
@rafeca good to know about the Typescript support, since React Native was shipped with Flow I had some problem with it.

Worth to say that @kristerkari example should be in the official documentation. That example shows how you could reason about the resolver and probably avoid issues like mine in the future, I totally encourage you to add to the documentation because from the current documentation I couldn't figure this out either.

Thanks a lot for the help!

**Comment by rafeca** [comment]
Thanks for the feedback! we are going to add soon more specific documentation around transformers, adding an example similar to the one in this issue

**Comment by ScreamZ** [comment]
Hey @rafeca,

I'm currently migrating to 0.57.3, I see the new metro syntax is available, but I'm having issue translating this:

```JS
module.exports = {
  getTransformModulePath() {
    return require.resolve("react-native-typescript-transformer");
  },
  getSourceExts() {
    return ["ts", "tsx"];
  }
};
```

to something like this : (I figured out for resolver ext but not for transform module path)

```js
module.exports = {
  resolver: {
    sourceExts: ['ts', 'tsx']
  }// …
}
```

Could you light me up about this ?

Regards

**Comment by rafeca** [comment]
Hey @ScreamZ ! right now [we have some docs](https://facebook.github.io/metro/docs/en/configuration) about the config params. 

In this case, this corresponds to `transformer.babelTransformerPath`. BTW v0.57 has typescript support out of the box, so you may be able to avoid redefining the transformer 😃

**Comment by kristerkari** [comment]
> BTW v0.57 has typescript support out of the box, so you may be able to avoid redefining the transformer

Yup @ScreamZ, Typescript is supported out-of-the-box in React Native since v0.57. You don't need the `react-native-typescript-transformer` and you can remove the `rn-cli.config.js` file.

**Comment by ScreamZ** [comment]
@rafeca @kristerkari Thank you very much ! 
Oh yeah, I missed about the babel plugin. Nice one.

However, do I need to do these steps (.babelrc and additionnal libs) ? To get a full support of Typescript ?
<img src="https://preview.ibb.co/gUxdDA/Screenshot-2018-10-23-at-14-52-19.png" alt="Screenshot-2018-10-23-at-14-52-19" border="0">

Here is my .tsconfig

```json
{
  "compilerOptions": {
    "target": "es6",
    "jsx": "react-native",
    "noEmit": true,
    "moduleResolution": "node",
    "allowJs": true,
    "importHelpers": true,

    "lib": ["esnext"],

    "removeComments": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strictFunctionTypes": true,

    "baseUrl": "app",
    "paths": {
      "@components/*": ["Components/*"],
      "@navigation/*": ["Navigation/*"],
      "@containers/*": ["Containers/*"],
      "@config/*": ["config/*"],
      "@redux/*": ["redux/*"],
      "@services/*": ["services/*"],
      "@themes/*": ["themes/*"]
    }
  },
  "exclude": ["node_modules"]
}
```

Regards :)

**Comment by kristerkari** [comment]
Yeah probably you do, as the docs seem to suggest that you get the full Typescript support that way.
