### ISSUE TITLE
Babel preset: Please bump to >=beta.54

### ISSUE THREAD

**Issue by haggholm** [facebook/metro#202]
Importing both the default symbol *and* wildcard named exports from a module breaks in the current Babel version: See https://github.com/facebook/react-native/issues/20083

The issue has already been resolved upstream (https://github.com/babel/babel/issues/8306) and published in `babel@7.0.0-beta.54`.

**Comment by rafeca** [comment]
Hey! We've updated `metro` [to use beta.54](https://github.com/facebook/metro/blob/master/packages/metro/package.json#L16), which is available from `metro@0.42.2`.

Hope that fixes your issue 😄
