### ISSUE TITLE
`verboseName` in dev-mode modules is no longer verbose

### ISSUE THREAD

**Issue by jamesreggio** [facebook/metro#204]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In order to perform manual code-splitting with React Native's 'unbundle' command, it's necessary to collect and transform the names of modules that have loaded after app startup. (The process is described in detail in the RN docs [here](https://facebook.github.io/react-native/docs/performance#investigating-the-loaded-modules).)

In RN v0.56.0, the module objects returned by `require.getModules()` no longer contain a full path in the `verboseName` field. Instead, they contain just the file name, which is insufficient for transforming back to module paths, as described [here](https://facebook.github.io/react-native/docs/performance#transforming-to-module-paths).

**What is the expected behavior?**

The expected behavior is that `verboseName` contains the path used to require the module.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

React Native v0.56.0
Metro v0.38.3

**Comment by rafeca** [comment]
Thanks for the report! This is indeed an incorrect behaviour: I'm going to fix it to display the relative path based on the project root instead.

**Comment by jamesreggio** [comment]
<3 Thank you for the quick acknowledgement — unbundling is a super complicated feature, and I was afraid I was going to have to go into much more detail.

Given that this breaks the production packaging workflow in RN, I think it probably justifies a patch release in the 0.56 line. If you have any power over that (or know the right people to ask within FB), I'd appreciate you doing so when it's fixed. Otherwise, I'll be happy to prod from the outside.

**Comment by rafeca** [comment]
Hey! I can try to cherry-pick the change on the v0.38.x branch, but it's a non trivial commit and I'm afraid is going to lead to conflicts. If it doesn't I'll do it and release a new v0.38.x version which will be picked up by RN 0.56

**Comment by jamesreggio** [comment]
Sounds great. Could you report back on whether that succeeds?

**Comment by rafeca** [comment]
I've had a few conflicts while cherry picking the change into the v0.38.x branch, but after solving them the tests are passing so I'm going to be able to publish a new release.

@mjesun can you check if you can also cherry pick the fix for https://github.com/facebook/metro/issues/208 in the `0.38.x` branch so we can include both fixes in the hotfix?

**Comment by rafeca** [comment]
Just published `v0.38.4` with this fix, let me know if it helps

**Comment by jamesreggio** [comment]
Thanks for the fix, @rafeca.

Just so you know, the format of the `verboseName` changed with your implementation. Previously, it would return a mixture of Haste module names (e.g., the not-fully-qualified names that seem to work for modules within the `react-native` package, like `ViewPropTypes`) as well as package-name relative paths (e.g., if my module is called `MyApp`, it would include paths like `MyApp/components/Root.js`).

Honestly, the past implementation was a total mess, and it required a lot of boilerplate code to heuristically convert the package names into relative paths which could be understood by Metro's unbundling feature. (See [here](https://facebook.github.io/react-native/docs/performance#transforming-to-module-paths) for said boilerplate.)

_However_, it's worth pointing out that this _is_ a breaking change (for build workflows), and the React Native unbundling docs are now out of date. It didn't take me long to rejigger our code to work the new `verbodyName`s, but I suspect there will be a number of people who run into problems.

(As much as I would like to help out here, I don't have time to make all of the necessary adjustments to those docs myself.)

**Comment by jamesreggio** [comment]
Awesome. Left a single comment, but generally LGTM. I don't know how changes are flagged as breaking for the release notes, but that's the only other thing I'd request that you do.

Many, many thanks for the quick turnaround on this!
