### ISSUE TITLE
PNGs are being included in the source map

### ISSUE THREAD

**Issue by rt2zz** [facebook/metro#222]
**Do you want to request a *feature* or report a *bug*?**
bug (?)

**What is the current behavior?**
My bundle source map contains 15mb of pngs. My assumption was that metro bundler would package any png's with my apk/ipa but that these resources would not affect my js bundle. In fact they are not in the bundle, just the bundle source map.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
react-native@0.56, metro-core 0.38.3, osx 10.14

**Comment by rafeca** [comment]
Thanks for the report and apologies for the late reply, I've been able to reproduce the issue and I'm going to prepare a fix for this 😃

**Comment by rafeca** [comment]
This has been fixed in https://github.com/facebook/metro/commit/beb7da85ef12d237363f77279a826556084de460 and will be included in the next release of Metro.

Thanks again! 🎉
