### ISSUE TITLE
Tree shaking while bundling

### ISSUE THREAD

**Issue by adnaan1703** [facebook/metro#227]
Is it possible anyhow to implement **tree shaking** during bundling.

Suppose I have a file say `greetings.js`:

```javascript
export const sayHi = (name) => {return `Jarvis says hi to ${name}`};
export const sayBye = (name) => {return `Jarvis says bye to ${name}`};
```

Now if in my project I am only using `sayHi` then I want `sayBye` to be removed from the final bundle which is currently not the case. 
Is it possible anyhow to implement this (even if I had to do changes in the config file for the metro bundler).

**Comment by rafeca** [comment]
Metro currently does not support tree shaking based on module import/export. @mjesun is currently adding first-class support for Metro to understand them and this will eventually allow us to do tree shaking.

Stayed tuned! 😃

**Comment by ruyadelaosan** [comment]
any outcome on tree-shaking ? Looking forward to that.

**Comment by karanjthakkar** [comment]
@rafeca Now that we have [experimental support for import/export](https://github.com/facebook/metro/releases/tag/v0.45.1) inside metro, is tree shaking now available out of the box or is there work going on to support it? Anything that we can help with to make this possible?

**Comment by rafeca** [comment]
@karanjthakkar : we're planning to implement some sort of tree shaking (or better said, minification of code based on the es6 module information) during H1 2019.

Based on our internal tests, the most impactful minification in terms of bundle size that can be done is to minify the import/export names, so for example:

```js
// bar.js
export const ANY_VARIABLE_NAME = 'value';
```

```js
// foo.js
import {ANY_VARIABLE_NAME} from './bar';
console.log(ANY_VARIABLE_NAME);
```

would get minified to:

```js
// bar.js
exports.a = 'value';
```

```js
// foo.js
console.log(r('./bar').a);
```

Afterwards, we're going to be able to do dead code elimination based on the exported values that are not being used anywhere

**Comment by camdagr8** [comment]
Any movement or resolution on this?

**Comment by aleclarson** [comment]
Is this still slated for H1 2019?

**Comment by sunnylqm** [comment]
<img src="https://user-images.githubusercontent.com/615282/57971722-3dddae80-79c4-11e9-8a6c-0fec70d5e2b1.png" width="320">

**Comment by Jeevan-Kishore** [comment]
Is it supported yet?

**Comment by Mitsichury** [comment]
Hi ! Any news ?

**Comment by vrgimael** [comment]
Seems that's rather late

**Comment by neiker** [comment]
Its february 2020, brexit happened but not this.

**Comment by cpojer** [comment]
@rafeca and @mjesun have since left Facebook. We are not actively working on tree shaking at Facebook and are exploring other more promising ways to keep our app size small.

If you are using Metro for React Native, it is unlikely that tree shaking will have a major impact on your applications size or behavior. If you are looking for size improvements, consider compressing the JS bundle that you ship with your app. If you are looking for performance improvements, there are likely many other things (like shipping Hermes and bytecode) that will have a large impact.

I'll close this as wontfix now but we will accept contributions towards tree shaking – and I'm accepting your job applications if you wanna work on this kinda stuff at Facebook London :)

**Comment by TheEhsanSarshar** [comment]
I think `https://github.com/callstack/repack` supports tree shaking. you can it instead of metor
what is repak:
> A Webpack-based toolkit to build your React Native application with full support of Webpack ecosystem.

**Comment by matthew-dean** [comment]
It's disappointing that Facebook's position is essentially, "bundling the entire import probably won't _that_ much bloat, or add _that_ much performance degradation to your app".

True (maybe), but why not just... not add things that aren't needed? Tree-shaking is an expected feature of any JS bundler, and not having tree shaking violates the Law of Least Surprise. If we use 1 function in, say, a giant hooks library with 1,000 hooks, we expect only that 1 function to show up in our app. If Metro can't provide this, then IMO Metro should not be in the business of bundling and should pair with Vite, Webpack, or other such bundlers to find a solution for React Native devs.

**Comment by adnaan1703** [comment]
Totally agree. The smaller bundle can still be valid even though we performed compression and backed it with Hermes. Currently, we are sending the bundle over HTTP with brotli compression and the underlying engine is Hermes for better performance but that doesn't rule out the use case for tree shaking. Also, I believe folks here undermine the improvement one can get with tree shaking.

At the time when I raised this issue, Haul (predecessor of repack) solved this issue by using webpack. At that time we saw an improvement of around ~49.64% improvement of bundle size.

- bundle size via metro: 505.84KB
- bundle size via haul without tree shaking: 537.75KB
- bundle size via haul with tree shaking: 254.74KB
Bundle size improvement: haul w/ tree shaking vs metro -> 49.64% gain.
* This was 2018. 

We couldn't go to production with Haul because of a lack of community support and also the bundle it splits breaks our internal system. Our internal diffing logic would have needed overall changes.

But now I think we have multiple solutions out there:
- eslint with custom tree-shaking plugin
- repack

Since these tools are now available, it is bound that users with advanced bundling needs will move away from Metro.

**Comment by kelset** [comment]
btw for those of you using Metro and wanting tree shaking, over at MSFT we have developed a plugin for Metro to basically rely on esbuild for treeshaking: https://microsoft.github.io/rnx-kit/docs/guides/bundling#tree-shaking

We already use it in prod on a couple projects and saw good bundle size improvements

**Comment by mannoeu** [comment]
Too bad... Ignoring real cases where Tree Shaking is necessary

**Comment by johnculviner** [comment]
Facebook went ahead and wrote their own JavaScript engine (hermes) to try to optimize startup behavior and in my own testing simply having less JavaScript goes a long way in improving startup performance... and dare I say is a lot simpler than writing your own JS engine from scratch 🤯

**Comment by EvanBacon** [comment]
Went ahead and wrote a version of tree shaking in Expo CLI to get the ball rolling. It can be added to any React Native project by adopting `expo/metro-config`, `babel-preset-expo`, and Expo CLI (requires E2E bundler integration). 

The implementation is landed on main and it'll ship experimentally in SDK 52 (October 2024). Here are the docs: [Tree Shaking in Expo CLI](https://docs.expo.dev/guides/tree-shaking/#remove-unused-imports-and-exports)

**Comment by aleksamrakovic** [comment]
Any way to remove .git folder from bundle? Is there any reason why metro do that?

**Comment by trip8971** [comment]
Run a webpack bundle command before the metro bundler's work to achieve the tree-shaking effect. It's worthing noting that you should config webpack external properly.
You can have a try.

**Comment by BoBoooooo** [comment]
It’s 2025 now. Unfortunately, there is still no metro treeShaking solution. ESBuild & Webpack support treeShaking, but the bundle split solution is different from metro. It’s a one-track mindset. My existing environment is strongly dependent on the Metro ecosystem, and migrating to other bundle solutions will have a high cost. So an official Metro(bundle split) + treeShaking ecosystem is very urgent needed !
