### ISSUE TITLE
Switch minifier from uglify-es to terser

### ISSUE THREAD

**Issue by haggholm** [facebook/metro#230]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Currently, `metro-minify-uglify` uses `uglify-es`, a branch of `uglify-js`. Unfortunately, `uglify-es` is not particularly well maintained and contains various bugs. Cf.

* https://github.com/mishoo/UglifyJS2/issues/3205
* https://github.com/mishoo/UglifyJS2/issues/3202
* https://github.com/mishoo/UglifyJS2/issues/3196
* https://github.com/mishoo/UglifyJS2/issues/3191

and others.

**What is the expected behavior?**

`metro-minify-uglify` could switch to `terser`. Its API is identical to `uglify-es` (except maybe some option index name? that might just be the Webpack plugin, though), so the effort should be negligible.

**Comment by rafeca** [comment]
Hi! Thanks for posting the issue! The minifier is configurable in Metro so you can use anything different already.

If you want, feel free to create a PR to add a small compatibility package called metro-minify-terser, to make it super easy to switch from one to the other. I’ll be happy to merge that 😃

After that we can consider making it the default (we’ll need to do some tests internally to check that it does not regress the bundle size or build times)

**Comment by rafeca** [comment]
Closing this issue, since your commit has landed and will be available in next Metro version
