### ISSUE TITLE
[Bug] metro-memory-fs not working as expected on windows

### ISSUE THREAD

**Issue by gengjiawen** [facebook/metro#235]
## Repro repo: 
react native master branch, run `npm run test`.
## What's the behavior
Many test falure due to `metro-memory-fs`
```
Error: On a win32 FS, the options' `cwd()` must return a valid win32 absolute path. This happened while trying to resolve: `c:\empty`

      33 |       continue;
      34 |     }
    > 35 |     fs.mkdirSync(entPath);
         |        ^
      36 |     mockDir(entPath, ent);
      37 |   }
      38 | }

      at MemoryFs._resolve (node_modules/metro-memory-fs/src/index.js:830:15)
      at MemoryFs.mkdirSync (node_modules/metro-memory-fs/src/index.js:994:5448)
      at mockDir (local-cli/__mocks__/fs.js:35:8)
      at MemoryFs.setMockFilesystem [as __setMockFilesystem] (local-cli/__mocks__/fs.js:17:3)
      at Object.<anonymous> (local-cli/core/__tests__/android/getDependencyConfig.spec.js:23:19)
```
## Related issue
https://github.com/facebook/react-native/issues/20260#issuecomment-417906514

**Comment by jeanlauliac** [comment]
I think the error message is incorrect, it doesn't take into account some edge case. I think the problem is that the Memory FS instance is in "posix" mode so in cannot parse the win32-style absolute path (so the contrary of what the error message says; I'll send a fix specifically for that).

In `react-native/local-cli/__mocks__/fs.js` it sets up the `cwd` function:

```js
const fs = new (require('metro-memory-fs'))({cwd: process.cwd});
```

To fix the problem, I believe you can simply set up the platform alongside:

```js
const fs = new (require('metro-memory-fs'))({
  cwd: process.cwd,
  platform: process.platform,
});
```

And it should then be able to parse the paths properly. Ideally, though, we should refactor the tests so that both win32 and posix are being tested in the test, without any dependency on the host platform. Memory FS allows to do such thing since it doesn't do any actual I/O.

**Comment by gengjiawen** [comment]
After set up the platform, run into other issues, looks like need to do more.
```cmd
Error: EINVAL: `\flat\android\app`: path is invalid because it cannot start with a separator

      21 |   const nested = path.join('android', 'app');
      22 | 
    > 23 |   if (fs.existsSync(path.join(folder, nested))) {
         |                     ^
      24 |     return nested;
      25 |   }
      26 | 
```
or 
```cmd
Expected: "string"
Received: "object"
Expected :string
Actual   :object
 <Click to see difference>


      31 | 
      32 |   it('returns manifest content if file exists in the folder', () => {
    > 33 |     expect(typeof findPackageClassName('/flatJava')).toBe('string');
         |                                                                               ^
      34 |   });
      35 | 
      36 |   it('returns the name of the java class implementing ReactPackage', () => {

      at Object.<anonymous> (local-cli/core/__tests__/android/findPackageClassName.spec.js:33:79)
```

**Comment by gengjiawen** [comment]
I debug some test code, find the `findPackageClassName('/flatJava') output is null `. So we may need to rewrite the test case to support windows.

**Comment by gengjiawen** [comment]
@jeanlauliac Anything thought we can do to get those test cases fixed in `react-native` ?

**Comment by jeanlauliac** [comment]
I'll try to look into it now. `metro-memory-fs` allows to test `win32` even from a `posix` system, so ideally both platforms should be tested all the time, no matter the host platform.

**Comment by gengjiawen** [comment]
If you find the cause, please update the test case if you can.

**Comment by jeanlauliac** [comment]
Yup, I've got a fix, will send soon. As I expected, there is no bug in `metro-memory-fs`, it is entirely a problem of how the test are set up in `react-native`. Notably, all the paths are hardcoded with leading slashes.

**Comment by gengjiawen** [comment]
@jeanlauliac The react native ci remains one failure on windows, do you know it's related to this issue ?
```
 FAIL  local-cli/link/__tests__/ios/writePlist.spec.js
  ● Test suite failed to run

    TypeError: require(...).join is not a function

      24 | const writePlist = require('../../ios/writePlist');
      25 | 
    > 26 | const projectPath = path.join(__dirname, '../../__fixtures__/project.pbxproj');
         |                                   ^
      27 | const infoPlistPath = path.join(__dirname, '../../__fixtures__/Info.plist');
      28 | 
      29 | fs.readFileSync = jest.fn(() => readFileSync(projectPath).toString());
```

**Comment by gengjiawen** [comment]
close it since most case are fixed.
