### ISSUE TITLE
Dead code elimination 

### ISSUE THREAD

**Issue by torkelrogstad** [facebook/metro#236]
I'm trying to share some code between a RN project and a Node.js project. In the Node.js specific code I'm importing modules which RN lacks. I'm therefore trying to do dynamically imports, only importing/requiring the Node.js modules in a if/else branch which RN will never hit. However, Metro tries to bundle the modules, and therefore throws errors. 

Is it possible for Metro to detect unreachable code and avoid bundling those branches? Kinda like `NODE_ENV === "production"/"development"` in Webpack and similar tools.

**Comment by Salakar** [comment]
@torkelrogstad you can configure metro with a custom `metro.config.js` file in your root to get rid of these.

For example, with a bit of meta programming you can redirect specific dependencies by name to instead require an empty JS file:

```js
// <PROJECT_ROOT>/metro.config.js
const { join } = require('path');
const NODEJS_ONLY = ['expressjs', 'koa'];

module.exports = {
  resolver: {
    extraNodeModules: new Proxy(
      {},
      {
        get: (target, name) => {
          if (NODEJS_ONLY.includes(name)) {
            // <PROJECT_ROOT>/noop.js
            return join(process.cwd(), `noop.js`);
          }
          // <PROJECT_ROOT>/node_modules/${name}
          return join(process.cwd(), `node_modules/${name}`);
        },
      }
    ),
  }
};
```

```js
// <PROJECT_ROOT>/noop.js
module.exports = {};
```

You can see the rest of the config options here: https://facebook.github.io/metro/docs/en/configuration

Hope that helps!

**Comment by torkelrogstad** [comment]
That seems to solve my problem quite well. Thank you!

**Comment by Salakar** [comment]
@torkelrogstad you're welcome!
