### ISSUE TITLE
Cannot read property 'bindings' of null at Scope.moveBindingTo at BlockScoping.updateScopeInfo

### ISSUE THREAD

**Issue by TSHHOL** [facebook/metro#274]
I really don't know what to do with this error. Please tell me what's wrong, it took too much my time. Thanks very much

**Comment by davidaurelio** [comment]
Hey @thanhsonhuehuynh, we will need more context. This looks like an error thrown from babel.

**Comment by rafeca** [comment]
Closing this issue since there's no clear repro steps, please reopen if you can provide more information
