### ISSUE TITLE
loading a module from a folder outside the root folder is failing with : unable to resolve module 'react'

### ISSUE THREAD

**Issue by faisalil** [facebook/metro#275]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
/rnproject1
has a react native project with the following rn-cli.config.js

var path = require('path');
module.exports = {
    watchFolders: [
        path.resolve(__dirname),
        path.resolve(__dirname, '../rnshared')
    ]
}

/rnshared
has a library that has some react-native components I want to consume from /rnproject1

When I start the packager, it fails saying it starts to load module "react" from the directory above  /rnshared 

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

steps above. 

**What is the expected behavior?**
be able to load common components fine. Why is the metro bundler trying to resolve the "React" module from another location where it already has it loaded in rnproject1

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

node: v8.9.4
    "react": "16.5.0",
    "react-native": "0.57.0",

**Comment by RomualdPercereau** [comment]
I got the same issue

**Comment by mmazzarolo** [comment]
I'm experiencing the same issue on `react-native@^0.57.2`.  
It was working fine on `react-native@0.56.0`. 

**package.json**
```json
{
 "dependencies": {
    "react": "^16.5.0",
    "react-native": "^0.57.2"
  },
  "devDependencies": {
    "babel-jest": "23.4.2",
    "babel-preset-react-native": "^5",
    "jest": "23.5.0",
    "react-test-renderer": "16.4.1"
  }
}
```

**.babelrc**
```json
{
  "presets": ["module:metro-react-native-babel-preset"]
}
```

**rn-cli.config.js**
```javascript
/**
 * This overrides the default metro bundler settings allowing us to resolve
 * directories outside of this example project.
 */
const path = require('path');
const metro = require('metro');

module.exports = {
  // Make sure the react and react-native packages are resolved from the example
  // folder (since for the module they will be defined as peerDependencies)
  extraNodeModules: {
    react: path.resolve(__dirname, 'node_modules/react'),
    'react-native': path.resolve(__dirname, 'node_modules/react-native')
  },
  // To avoid naming collisions, blacklist the react-native package used in the module
  getBlacklistRE() {
    return metro.createBlacklist([
      /my-external-module\/node_modules\/react-native\/.*/
    ]);
  },
  getProjectRoots() {
    return [
      // Resolve the example project directory & its node_modules
      path.resolve(__dirname),
      path.resolve(__dirname, 'node_modules'),
      // Resolve the module directory
      path.join(__dirname, '..', 'my-external-module')
    ];
  }
};
```

**Comment by mroswald** [comment]
In case you did not find a solution yet or anybody else finds this issue: With metro 0.40 `getProjectRoots` was changed to `getProjectRoot` and `getWatchFolders`. For more information, read https://github.com/facebook/metro/commit/45366056dfb8bec38faaf0ea22c01d80da261287
