### ISSUE TITLE
Metro opens ReactNativeRenderer-dev.js with the default editor while running in the console

### ISSUE THREAD

**Issue by sylv3r** [facebook/metro#284]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

First I tried to google about this issue and I didn't find anything, even on stackoverflow, so maybe I did something wrong, but I don't clearly see where.

While running metro, it keeps opening a file with the exact mention : 

> Opening *[my absolute path]*/node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js with /usr/bin/vim

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

I just started a new project, running metro immediately did that. Whatever I do, it keeps popping up. I cleaned everything, removed `build` folders, `node_modules`, launched it with `--reset-cache`.

**What is the expected behavior?**

Not launching vim while running in the console to edit whatever file.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

Didn't configure anything on metro (don't even know where its conf is).
macOS high sierra 10.13.6
yarn 1.9.4
npm 6.4.1

dependencies : 
```
  "dependencies": {
    "react": "16.5.0",
    "react-native": "0.57.2",
    "react-native-vector-icons": "^6.0.1",
    "react-navigation": "^2.17.0"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "babel-jest": "23.6.0",
    "eslint": "^5.6.1",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-babel": "^5.2.1",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsdoc": "^3.8.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-react": "^7.11.1",
    "eslint-plugin-react-native": "^3.3.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.0",
    "react-test-renderer": "16.5.0"
  },
```

**Comment by sylv3r** [comment]
Nevermind, it seems it was my simulator triggering some edits by itself...

**Comment by mathieutu** [comment]
@sylv3r Hey. 
I've the same issue with other files. How did you managed that?

Thanks.

**Comment by flybayer** [comment]
@sylv3r @mathieutu I'm having the same weird issue where metro opens a file with vim. How did you fix it?

**Comment by sylv3r** [comment]
@flybayer @mathieutu well, that’s embarrassing ... but after giving it some thoughts later, I’m pretty sure in my case it was because I was clicking on links in the stacktrace displayed on the simulator (red screen) when I actually wanted only to focus on it.

A hard reminder to only use the keyboard and stop clicking around.

**Comment by flybayer** [comment]
Ok, yeah that's what I was just realizing. This happens in `node_modules/react-native/local-cli/server/util/launchEditor.js`.

Apparently, my device screen keeps going dim and I touch the screen (with a stack trace) to wake it back up.
