### ISSUE TITLE
node_modules in subdirectories clobber node_modules in root directory

### ISSUE THREAD

**Issue by nicbarker** [facebook/metro#300]
**Do you want to request a *feature* or report a *bug*?**
I'm not sure, I can't find enough information to tell if this is by design or not

**What is the current behavior?**
Note that this is just a generic example.
Given a react-native respository with the following structure
```
foo/
    - node_modules/
        - react@0.2
    - bar/
        node_modules/
            - react@0.1
```
Running `node_modules/react-native/local-cli/cli.js start --reset-cache` then using `require('react')` you'll get `react@0.1` from the `bar/node_modules/react@0.1` directory
rather than `react@0.2` from the `node_modules/react@0.2 directory.`

It appears like the metro bundler will traverse down into subdirectories and preferentially use the `node_modules` that it finds there, before the ones in the root directory.

This is not the same behaviour as the default node `require`. Testing the same thing with the `node` command in the root `foo/` directory will grab the `react@0.2` module preferentially.

This seems strange to me - can someone confirm is this is intended behaviour or not?

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

**What is the expected behavior?**

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

This is on OS X High Sierra, RN 0.57.0.

**Comment by rafeca** [comment]
Hi @nicbarker! `metro` resolution algorithm should follow the same constrains as the Node.js one.

In your example, `require('react');` will resolve to `react@0.1` from any file inside the `bar/` folder, since it starts looking for `node_modules` folders from the file that has the require statement.

We have some unit tests to verify this behaviour ([like this one](https://github.com/facebook/metro/blob/master/packages/metro/src/DeltaBundler/__tests__/traverseDependencies-integration-test.js#L1883)), but it could be possible that there's some edge case that's not covered.

Can you can come up with a failing test with an expected behaviour? (or some repro steps)

**Comment by nicbarker** [comment]
Hey @rafeca, thanks a lot for the reply. I'm having trouble replicating this at the moment, perhaps it's related to https://github.com/facebook/metro/issues/97 ? I'm having it reliably happen in my (complex) main monorepo, but I can't seem to reproduce with a simple test case. I also haven't tested using the react-native cli commands, only with `metro` itself so far. I'll get back to you if I manage to figure out how to replicate it in a smaller test case.

**Comment by nicbarker** [comment]
Unfortunately I haven't been able to pinpoint exactly what causes this, but I can still reliably get it to happen inside my repository. It's possible that as with #97 there are some symlinks in my node modules that are causing traversal problems, I'll try using the blacklist and see if I can get it to work. Also just a heads up @rafeca, the link in your previous comment to the unit test 404s. I'll close this issue for now.

**Comment by rafeca** [comment]
@nicbarker : thanks for the notice about the link, I've updated it (I refactored recently the dependency resolution unit tests to make them more clear).
