### ISSUE TITLE
Mangle parameters not taken into account when bundling release

### ISSUE THREAD

**Issue by aaska** [facebook/metro#301]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When setting the transformer.minifierOption.mangle = false this is not taken into account when bundling the project. Since some libraries don't work in react-native with mangle on, I need to have it disabled

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

https://github.com/aaska/metromangle.git

just run yarn test. it does a full cleanup and build the bundle in the bundle/ directory. The package.json contains the metro config I want to apply, and I've patched the react-native local-cli to ensure that mangle was passed with the false flag (check the patch folder to review the modification, it's just a console.log).

**What is the expected behavior?**
I'm expecting to have a file similar that what is available in the bundle/index.android.output.not-mangled.0.57.2

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

Metro configuration is in the package.json : 

```
 "metro": {
    "transformer": {
      "minifierConfig": {
        "output": {
          "ascii_only": true,
          "quote_style": 3,
          "wrap_iife": true
        },
        "sourceMap": {
          "includeSources": false
        },
        "toplevel": false,
        "compress": {
          "reduce_funcs": false
        },
        "mangle": false
      }
    }
  }
```

Configuration : 
```
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-7287U CPU @ 3.30GHz
      Memory: 64.38 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.0 => 16.6.0
      react-native: ^0.57.3 => 0.57.3
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-ci-tools: 1.1.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7


```

**Comment by rafeca** [comment]
Hi @aaska, thanks for reporting!

The issue comes from the fact that we're destructuring the `mangle` property that we receive from the config (we expect it to be an object).

You can see the two places where we do that: [here](https://github.com/facebook/metro/blob/master/packages/metro-minify-terser/src/minifier.js#L42-L45) and [here](https://github.com/facebook/metro/blob/master/packages/metro-minify-uglify/src/minifier.js#L42-L44).

Instead, there should be some logic to check if `config.mangle` is false and in that case just set it to that value.

Are you interested in sending a PR with a fix for that?

**Comment by mfbx9da4** [comment]
This issue still isn't fixed!
