### ISSUE TITLE
Google Closure Advanced build fails when disabling dev mode

### ISSUE THREAD

**Issue by vikeri** [facebook/metro#317]
**Do you want to request a *feature* or report a *bug*?**
Regression bug

**What is the current behavior?**
My minified app will not run if I set dev to false (RN 0.57) and enable Google Closure's advanced compilation (uglifying+dead code elimination). Wit Google Closure optimizations simple it works. In previous versions (0.56) it worked with advanced and dev set to false.
The error it throws is `Can't find variable: a `

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
I'm not asking for a fix, just wondering what dev mode does and if something has changed with it since the last release of RN (0.56)?

**What is the expected behavior?**
That the code should run without errors.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

**Comment by chpill** [comment]
This is a duplicate of https://github.com/facebook/metro/issues/291

As for why the `if` statement is there, my guess is that these optimizations make producing the JS bundle a lot longer, which is not a pleasant development experience.

**Comment by vikeri** [comment]
Closing this since it's a duplicate
