### ISSUE TITLE
Option for stable module Ids?

### ISSUE THREAD

**Issue by lelandrichardson** [facebook/metro#35]
**Do you want to request a *feature* or report a *bug*?**
Feature

i’m working on OTA updates for RN at airbnb, and one of the things that i’m looking to do is to ensure that we can push just the code that’s changed and not the whole bundle to the clients. since the RN packager uses unstable module ids after bundling code (ie, `require(123)` might need to turn into `require(124)` after a relatively trivial change in module loading order).

I was thinking about submitting a PR to metro-bundler that would add in an option to use "stable ids" for the require algorithm. This would probably end up using the `localPath` of the module, as opposed to the auto-incrementing module id.

I'm still considering strategies, but I'm thinking that in the situation where the user is using `unbundle`, a map of `localPath => moduleId` could be added to a global variable or something, which the `require.js` polyfill could utilize.

If I made such a PR, would FB be willing to accept it? It would be done in such a way that it would be completely opt-in.

cc @jeanlauliac @cpojer

**Comment by mc-zone** [comment]
Also need this feature. There is also an issue #6 I opened earlier to discuss about it.

**Comment by rafeca** [comment]
Hey @lelandrichardson! this was added in f347e4ff470ca858cdb8af5a80d409cc5061e9ee and is available on 0.24.1

**Comment by lelandrichardson** [comment]
@rafeca awesome, thanks!
