### ISSUE TITLE
How to run metro-visualizer

### ISSUE THREAD

**Issue by cihati** [facebook/metro#366]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

**What is the expected behavior?**

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

I came across [metro-visualizer](https://github.com/facebook/metro/tree/master/packages/metro-visualizer) by chance. I have never dealt with Metro by itself, only through the [React Native CLI](https://facebook.github.io/react-native/docs/understanding-cli)

For someone who only uses `react-native run-ios` and `react-native start`, how does one use this useful tool?

I use react-native 0.58.5 and metro-react-native-babel-preset 0.52.0

**Comment by cpojer** [comment]
Check out the README: https://github.com/facebook/metro/tree/master/packages/metro-visualizer#setup

cc @simonpfish

**Comment by cihati** [comment]
@cpojer Thanks for your reply. I have already read that before opening this ticket, but as I said I only use `react-native run-ios` and `react-native start`. I do not have any metro config, and I don't know how to have one and got it recognized by these commands. This might be a quite noob question, sorry about that!

**Comment by cpojer** [comment]
@cihati you can create a `metro.config.js` in the root of your project and then continue with the instructions from the README. That should work :)

**Comment by iwikal** [comment]
running metro by itself gets me here:
![2019-05-29-181122_619x567_scrot](https://user-images.githubusercontent.com/13943374/58573037-2e205e80-823d-11e9-85b3-67fd83249fc3.png)

Not really sure where to go from there, I tried to specify `index.js` as my entry point. That gives me this error toast:

![2019-05-29-180951_619x567_scrot](https://user-images.githubusercontent.com/13943374/58572973-029d7400-823d-11e9-998a-1612d0e7299e.png)

If I instead run `react-native start` to start the metro server like I normally do during development, and visit `localhost:8081/visualizer`, I'm presented with the same page, but when I enter `index.js` and press `Build`, the loading spinners will briefly flash and then disappear again, returning to the initial state like nothing happened. If I look in the Network tab in chrome devtools, I see a request for `http://localhost:8081/index.js?platform=ios&dev=false&minify=true&excludeSource=false&inlineSourceMap=false&runModule=true` which only returns this:
```js
/**
 * @format
 */

import { AppRegistry } from 'react-native'
import App from './App'
import { name as appName } from './app.json'

AppRegistry.registerComponent(appName, () => App)
```

Me, and I'm assuming the majority of metro users, are coming from one of the guides on this page: https://facebook.github.io/react-native/docs/getting-started.html
I would really like the readme to presuppose only what's in those guides.
