### ISSUE TITLE
Example of metro.config.js > resolver.resolveRequest(context, moduleName, platform)

### ISSUE THREAD

**Issue by shawnthye** [facebook/metro#385]
Hi guys,
Sorry to trouble u.

Is there a working example for this?

Thanks in advance.

**Comment by 3rd-Eden** [comment]
The `metro-resolver` is working example of this. See it's `resolve` method; https://github.com/facebook/metro/blob/master/packages/metro-resolver/src/resolve.js

**Comment by vlad-dewitt** [comment]
Documentation for Metro is just disgusting, no examples, absolutely nothing.......
"Do you need examples? ahaha... NO, to hell with it, guess yourself!".
Documentation level: `{ something: well... this is something, the end. }`
