### ISSUE TITLE
Windows Defender flags this package as a Trojan virus

### ISSUE THREAD

**Issue by ThijmenMaus** [facebook/metro#439]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
It's being reported as a Trojan

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
Just set up and Expo project with Native Base

**What is the expected behavior?**
To not have it flagged as a Trojan

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
I deleted it already out of procaution, I just did expo init <project-name> and installed Native-base. After that I got a message from windows defender saying a folder called metro-cache contained a Trojan. (C:\%user%\AppData\Local\Temp\metro-cache). I believe it was the latest version.

You can see the notifcation here:
https://i.imgur.com/6h3uHaX.jpg

**Comment by Haroenv** [comment]
Technical details seem not to be available for the vulnerability: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Program:Script/Oneeva.A!ml&ThreatID=245719
