### ISSUE TITLE
i have local javascript library How do i config metro.config.js

### ISSUE THREAD

**Issue by vtn-dev2016** [facebook/metro#447]
bundling failed: Error: Unable to resolve module `apptify-lib/lib` from `react native project path`: Module `local/lib` does not exist in the Haste module map or in these directories:

**Comment by veerjainATgmail** [comment]
need to configure projectRoot and watchFolders.

Try,
https://facebook.github.io/metro/docs/en/configuration
https://callstack.com/blog/adding-an-example-app-to-your-react-native-library/

**Comment by zmefz** [comment]
Install plugin [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver)
```npm i babel-plugin-module-resolver --save-dev```

Given:
- **local-lib-alias-name** - import module name
- **../relative/path/to/local/lib** - relative module path

Add module-resolver plugin to babel config (`babel.config.js` in my case)
```javascript
// babel.config.js
module.exports = {
  //...
  plugins: [
    ['module-resolver',
      {
        alias: {
          'local-lib-alias-name': '../relative/path/to/local/lib',
        },
      },
    ],
  ],
}
```
_Note:_ it will change your js module imports to right path

Edit metro config (`metro.config.js` in my case)
```javascript
// metro.config.js
const path = require('path')

module.exports = {
  // ...
  watchFolders: [
    path.resolve(__dirname, '../relative/path/to/local/lib'),
  ],
  resolver: {
    extraNodeModules: new Proxy(
      {},
      {
        get: (target, name) => {
          if (target.hasOwnProperty(name)) {
            return target[name]
          }
          return path.join(process.cwd(), `node_modules/${name}`)
        },
      },
    ),
  },
}
```
_Note:_
- [watchFolders](https://facebook.github.io/metro/docs/en/configuration#watchfolders) addition will let your code import module from new locations and watch changes at this locations
- [extraNodeModules](https://facebook.github.io/metro/docs/en/configuration#extranodemodules) redirects dependencies referenced from shared folders (new location/your library) to local node_modules

Links:
1. https://callstack.com/blog/adding-an-example-app-to-your-react-native-library/
Notes: getProvidesModuleNodeModules did not work for me so I used solution from Link 2: added extraNodeModules.

2. https://github.com/facebook/react-native/issues/21310#issuecomment-540227031

**Comment by ajsmth** [comment]
@zmefz you are a life saver, thank you!

**Comment by MichaReiser** [comment]
It seams that the question was answered. Closing. Feel free to re-open if this isn't the case.
