### ISSUE TITLE
Configure babel config

### ISSUE THREAD

**Issue by pturchik** [facebook/metro#463]
How I can use different babel config for debug and release builds?

I generated base project using `npx react-native init MyApp` and then replace default `babel.config.js` content to

```javascript
module.exports = {
  env: {
    development: {
      presets: ['module:metro-react-native-babel-preset']
    },
    production: {
      presets: ['module:metro-react-native-babel-preset']
    }
  }
}
```

Debug build works fine, but release build (`yarn ios --configuration=Release`) throw an error something like this 
`Error: Import statement may only appear at top level in file node_modules/react-native/Libraries/NewAppScreen/index.js` (it's happens for new generated project).

In my old projects this error
![image](https://user-images.githubusercontent.com/53335451/67044165-59481380-f134-11e9-82a2-9782663206c6.png).

In build process the `process.env.BABEL_ENV` variable take the values `production` or `undefined` (I don't know why the variable move from `production` to `undefined` in build process on some steps, [BABEL_ENV setup](https://github.com/facebook/metro/blob/master/packages/metro-react-native-babel-transformer/src/index.js#L153)) and when `BABEL_ENV` is undefined then babel does not use right config.

Also release build works if I pass `BABEL_ENV` manually (`BABEL_ENV=production yarn ios --configuration=Release`).

Does anyone know what is the problem with release build ? Why release build does not work by default when I have configured `babel.config.js`?

**Comment by pturchik** [comment]
Fixed in v0.57.0.

**Comment by bgneu** [comment]
@pturchik Did you find a solution to your question aside from passing `BABEL_ENV` manually?

**Comment by pturchik** [comment]
@bgneu You can use `NODE_ENV` in your babel.config.js.

```js
module.exports = function (api, opts) {
   api.cache(true);
   return configs.env[process.envNODE_ENV]
}
```
