### ISSUE TITLE
[bug]ReactNative not work on Windows, error when starting JS server.

### ISSUE THREAD

**Issue by finntenzor** [facebook/metro#483]
Probably a bug.
OS: Windows 10

Behavifor:
When I create a new react-native project and run it, no JS server start.
When I run the command `react-native start`, found error at `node_modules\metro-config\src\defaults\blacklist.js` line 34.

Steps:
react-native init ABC
cd ABC
react-native start

Expected:
Runs OK.

Actual:
Got an error.

Other:
I modified the `node_modules\metro-config\src\defaults\blacklist.js` at line 23, making it`return pattern.source;` and everything runs OK.
I think thats because the `/` character was convert to `\` character and make en error regular expression at windows platform.
However, I have no idea to fix it.

**Comment by tad3j** [comment]
Bug has been fixed in metro-config package: https://github.com/facebook/metro/commit/7c6f30b592b2fb23cee55b54f1aa4b7a522dec18

Could you please bump metro-config version to 0.57.0 to fix this issue?

**Comment by tad3j** [comment]
I think this has been fixed with https://github.com/facebook/metro/commit/7c6f30b592b2fb23cee55b54f1aa4b7a522dec18, but they need to bump metro package to v0.57. I've opened a bug report here: https://github.com/react-native-community/cli/issues/853

**Comment by tad3j** [comment]
I think this has been fixed by https://github.com/facebook/metro/commit/7c6f30b592b2fb23cee55b54f1aa4b7a522dec18, but react-native-community/cli needs to bump metro version to 0.57.0. I've opened a bug report here: https://github.com/react-native-community/cli/issues/853

**Comment by finntenzor** [comment]
That seems to be the reason.
I'm using react-native-cli 2.0.1 and react-native 0.60.5.
And in my lock file, I found:
    metro "^0.54.1"
    metro-config "^0.54.1"
    metro-core "^0.54.1"
    metro-react-native-babel-transformer "^0.54.1"

**Comment by MichaReiser** [comment]
This issue should be fixed in the latest version  #604
