### ISSUE TITLE
Disable logging to the terminal

### ISSUE THREAD

**Issue by Esemesek** [facebook/metro#484]
> This issue was originally posted in React Native CLI repo: https://github.com/react-native-community/cli/issues/794

### Issue

`Logging` user logs to the terminal can get quite messy and we should provide a way to disable them on demand. Currently, `metro` doesn't provide any reliable way to disable such logs. I tried to override `metro`'s reporter in the CLI, but it didn't have any effect on the user logs.

### Workaround

I managed to disable logging by removing `logToConsole` entirely using `patch-package` (https://gist.github.com/Esemesek/00b49e8041bb27b6215c2cc8dafb2378).

### Expected

Provide a configuration flag to disable user logs.

cc @cpojer

**Comment by paulbargaoanu** [comment]
Did anyone find at least a workaround for this? It really frustrates me that I cannot disable logging to the terminal, especially when when I am debugging in Chrome or VS Code. It's redundant, slow and completely pollutes Metro's output. I don't want to come across rude, I'm just trying to find a solution. Any kind of help towards solving this would be greatly appreciated.

**Comment by Esemesek** [comment]
@paulbargaoanu https://github.com/react-native-community/cli/issues/794#issuecomment-552925016

**Comment by QSuraj** [comment]
This would be super helpful if we had a flag to disable the logs.

**Comment by huntie** [comment]
This is something we want to (eventually) disable by default once we stabilise our [new debugger experience](https://github.com/react-native-community/discussions-and-proposals/discussions/733). Seeing that there's demand right now to manually opt-out of this behaviour, I think we're happy to implement this option 👍🏻.

**Comment by antoniopresto** [comment]
```js
// metro.config.js
// [...]
config.server = {
  ...config.server,
  forwardClientLogs: false, // 👈🏽
};


```

**Comment by antoniopresto** [comment]
As above: [Add server.forwardClientLogs config option](https://github.com/huntie/metro/commit/dd88bc3a978331af9e05fcbd53cba4b27f4fdd1e)

```js
// metro.config.js
// [...]
config.server = {
  ...config.server,
  forwardClientLogs: false, // 👈🏽
};

```
