### ISSUE TITLE
JSON files from project and `node_modules` dependencies are duplicate to the js bundle and to android resources `res/raw`

### ISSUE THREAD

**Issue by kasl** [facebook/metro#487]
**What is the current behavior?**
When building android bundle, JSON files from project and `node_modules` dependencies are duplicate to the js bundle and to android resources `res/raw`. 
![bundle](https://user-images.githubusercontent.com/3302886/69315638-8cb51b00-0c69-11ea-94d0-1f6df3b1ba13.jpg)

**What is the expected behavior?**
My project have big JSON data ~13MB (compressed) `PROJECT_ROOT/src/assets/words.json`, which are needed only in JS. When duplicating the size of the bundle increases several times.
Faced this issue after updating from RN 0.59 to RN 0.61. 

I think the problem became relevant after this commit https://github.com/facebook/metro/commit/dcb41e39f0df6ae1e0b3dfeff9ef5a69128830d5#diff-235a3e5d21175615e1cc254dd8b17eb2 , because if i override `assetExts` option and remove `json` everything works well and as before.

Is this problem general or mine? It does not seem to me a good idea to copy all json from all dependencies to android resources. If this is normal behavior, is it possible to exclude json files from my project?

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
- Ubuntu 18.04.3 LTS
- node v10.17.0
- npm@6.12.1
- yarn@1.19.1
- metro@0.56.3
- metro-config@0.56.3
- RN@0.61.4

**Comment by belemaire** [comment]
Same question here. 
Ran into same problem, the imported `.json` files are already backed inside the JS bundle at bundling time (at the difference of image assets for example that are dynamically loaded at runtime) so we don't need them copied over to target asset directory.
We had to override `assetExts` as well through custom `metro.config.js` rather than rely on the default config.

**Comment by AleksandrZhukov** [comment]
Got the same problem, will be nice to fix it
