### ISSUE TITLE
Add Readme for metro-memory-fs

### ISSUE THREAD

**Issue by rkennel** [facebook/metro#492]
**What am I asking for?**
Quick readme file for metro-memory-fs displaying basic usage scenarios

**Why am I asking for it**
I was looking for a way to be able to use a test double for node's fs module.  metro-memory-fs was suggested but when I looked in npmjs and github it took a lot of digging to find common usage example.

**Comment by robhogan** [comment]
Sorry this never got a response - PRs always welcome but `metro-memory-fs` isn't really designed for public consumption and documenting isn't likely to be a priority in the foreseeable future.

[`memfs`](https://www.npmjs.com/package/memfs) is a good choice for this purpose, afaik.
