### ISSUE TITLE
metro-config sharedBlacklist regexp without scape "\"

### ISSUE THREAD

**Issue by micnguyen** [facebook/metro#513]
This re-opens https://github.com/facebook/metro/issues/453 as the issue is still prevalent despite it being closed.

**Comment by alifarukm** [comment]
Yes same issue for me #453 . I can solve with [stackoverflow](https://stackoverflow.com/questions/58120990/how-to-resolve-the-error-on-react-native-start/58122821#58122821). Is it possible solve permanently ?

**Comment by brentvatne** [comment]
this can occur if you are using an old version of metro. if you provide a reproducible example then it will be possible to help, but otherwise there isn't much we can do.

**Comment by MichaReiser** [comment]
This is a duplicate of #578 which contains more information. We're happy to merge a PR with the fix.
