### ISSUE TITLE
[Feature Request] Converting document to Docsaurus 2

### ISSUE THREAD

**Issue by Naturalclar** [facebook/metro#525]
**Do you want to request a *feature* or report a *bug*?**

This is a feature request

## Overview

I saw this Issue https://github.com/facebook/docusaurus/issues/1834 that was migrating many of the fb document to docsaurus 2-alpha.

Would it be better for metro to have its document in docsaurus 2?
If so, I'd like to help migrating the document, but I just wanted to make sure if that is ok before I start working on it.

**What is the current behavior?**

Metro document is made with docsaurus 1

**What is the expected behavior?**

write Metro document in docsaurus 2 (alpha)

**Comment by fanny** [comment]
Hi @Naturalclar, Do you can assign me on this task?

**Comment by JoelMarcey** [comment]
@Naturalclar Hi! Are you interested in doing the actual conversion? Or would you just like to see the conversion done? I am just wanting to see if this should be assigned to you or @fanny, who is also interested. Thanks.

**Comment by Naturalclar** [comment]
@JoelMarcey I'm interested in doing the actual conversion as well!
@fanny If there is a way we could collaborate, that would be awesome. From looking at examples of other migration, it seems a little difficult to split the task though.

**Comment by fanny** [comment]
No worries @Naturalclar, I'll take another. :laughing:
