### ISSUE TITLE
TypeScript 3.8 "import type" is not supported

### ISSUE THREAD

**Issue by WhippetsAintDogs** [facebook/metro#537]
**Do you want to request a *feature* or report a *bug*?**

Feature request.

**What is the current behavior?**

*Import type* are not recognized by metro's babel version (it uses 7.8.4 instead of 7.9 which supports them).

![image](https://user-images.githubusercontent.com/9271409/77437287-dac66080-6dba-11ea-8fce-131c9dd49305.png)

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

**What is the expected behavior?**

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

Using npm to install metro-react-native-babel-preset (version: 0.59.0).

**Comment by t-ricci-enhancers** [comment]
I'm having a similar issue but with the opposite `export type {A} from './A';`

**Comment by t-ricci-enhancers** [comment]
I solved updating metro-react-native-babel-preset, typescript and all babel-related packages to the latest version @WhippetsAintDogs

**Comment by WhippetsAintDogs** [comment]
@t-ricci-enhancers, thanks, but yeah I was already using all these latest versions and the `export type` was working fine. It is really only the `import type` inside the code bundled by metro that doesn't work yet on my side.

**Comment by Grohden** [comment]
@WhippetsAintDogs thx for your comment:
> it uses 7.8.4 instead of 7.9 which supports them

I was trying to find out on the repo where metro declares this specific babel version, but it seems that it doesn't.

It uses `^7.0.0`, which probably means that any 7.x.y works. So after updating my own `package.json` with:
```json
    "@babel/core": "7.9.6",
    "@babel/runtime": "7.9.6",
```

It worked without any problems... till now 🤔

**Comment by WhippetsAintDogs** [comment]
@Grohden, you're right. Regenerating metro's part in my package-lock fixed it. 

Thanks !
