### ISSUE TITLE
What is the equivalent of webpack loader in the metro bundler?

### ISSUE THREAD

**Issue by wood1986** [facebook/metro#538]
**Do you want to request a *feature* or report a *bug*?**

I guess feature if metro does not have.

**What is the current behavior?**

In webpack, I can do something like this

```
import config from 'my-loader!./config.js';
```

It will preprocess my config.js at build time before bundling it. If metro has this functionality, what is the equivalent of this. If it does not have, could you support this?

**Comment by rickhanlonii** [comment]
Hey @wood1986, thanks for the question.

Metro doesn't have loaders. Depending on the loader you want to replicated, you'll need to configure a resolver, transformer, or serializer.  See [Metro Concepts](https://facebook.github.io/metro/docs/concepts) for more info.
