### ISSUE TITLE
Support for asynchronous iterators (async for of)

### ISSUE THREAD

**Issue by raffaeler** [facebook/metro#551]
Asynchronous iterators and generators (aka `await for ... of`) are available as part of ES2018.
How can I use it in a react-native app? Currently there is no metro support for them.

Example:
``` 
// generator
 async function* gen() {
     yield 'a';
     yield 'b';
     return 2;
 }

// consumer
try {
    for await (const t of gen()) {
        console.log(t)
    }
}
catch(err) {
    console.log("err", err);
}
```

Any suggestion to workaround the issue is welcome. I could not find anything for using them.

Thanks

**Comment by ls-andrew-goodale** [comment]
JavaScriptCore in iOS 12+ supports them natively, as does JavaScriptCore bundled for Android. Can you set your minimum required iOS to 12?

**Comment by berdyshev** [comment]
any updates on this? I have also issues with getting this to work with the following error: 
```
TypeError: Invalid attempt to iterate non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
```

**Comment by newyankeecodeshop** [comment]
@berdyshev I was able to figure out what was going wrong. That error is due to an error in the `@babel/plugin-transform-for-of` plugin. It (mistakenly) tries to convert `for await of` statements with the same code as `for of`, and uses the wrong iterator property accessor.

I was able to workaround the problem by adding `@babel/plugin-proposal-async-generator-functiions` to my `babel.config.js`.

**Comment by JSonicV** [comment]
> JavaScriptCore in iOS 12+ supports them natively, as does JavaScriptCore bundled for Android. Can you set your minimum required iOS to 12?

@ls-andrew-goodale, do you know the minimum requirements for Android? Thx

**Comment by ls-andrew-goodale** [comment]
@JSonicV I use a very similar Babel config and don't have that error. Unfortunately, even though the Android JavaScriptCore supports async iteration, we have to use the Babel config to workaround the bug in `@babel/plugin-transform-for-of` which tries to process `for async ()` loops as synchronous iterator loops.

Is your type error coming from using a Generator or a custom Iterable?

**Comment by JSonicV** [comment]
@ls-andrew-goodale It is from Generators, which are massively used in SocketCluster to listen and consume events.
Mixing all the solutions here proposed, I solved the problem for IOS. For Android, instead, it persits and I can't figure out why

**Comment by sohan-dutta** [comment]
> @JSonicV I use a very similar Babel config and don't have that error. Unfortunately, even though the Android JavaScriptCore supports async iteration, we have to use the Babel config to workaround the bug in `@babel/plugin-transform-for-of` which tries to process `for async ()` loops as synchronous iterator loops.
> 
> Is your type error coming from using a Generator or a custom Iterable?

Hi @JSonicV have found any solution to this? I'm also facing this issue when implementing Socket Cluster in React Native in Android

**Comment by robhogan** [comment]
Hi @sohan-dutta, would you be able to open a new issue describing the behaviour you’re seeing with your Babel and Metro config? I don’t think this bug is on our radar at the moment.

**Comment by haakonnessjoen** [comment]
I have the same problem trying to implement Socket Cluster in react native on ios/android. Did anyone figure this out? The babel config didn't help at all.

**Comment by sohan-dutta** [comment]
> 

I was able to solve using this polyfill [@azure/core-asynciterator-polyfill](https://www.npmjs.com/package/@azure/core-asynciterator-polyfill)
