### ISSUE TITLE
Broken regular expression in Windows exclusionList.js path separator replacement 

### ISSUE THREAD

**Issue by sparebytes** [facebook/metro#578]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

On Windows, I get an error when running `react-native start`:

```
Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.
SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
```

**The Fix**

```patch
 function escapeRegExp(pattern) {
   if (Object.prototype.toString.call(pattern) === '[object RegExp]') {
-    return pattern.source.replace(/\//g, path.sep);
+    return pattern.source.replace(/\//g, '\\' + path.sep);
   } else if (typeof pattern === 'string') {
     var escaped = pattern.replace(/[\-\[\]\{\}\(\)\*\+\?\.\\\^\$\|]/g, '\\$&');
     // convert the '/' into an escaped local file separator
     return escaped.replace(/\//g, '\\' + path.sep);
#-----------------------------------^ The replace method above should also escape `path.sep`
 ```

If you look at [line 22 of exclusionList.js](https://github.com/facebook/metro/blob/94c0b541b4bfa17aee4efa0f1969565522ce830d/packages/metro-config/src/defaults/exclusionList.js#L22) you'll see it replaces `/` with `"\\" + path.sep` but on [line 18](https://github.com/facebook/metro/blob/94c0b541b4bfa17aee4efa0f1969565522ce830d/packages/metro-config/src/defaults/exclusionList.js#L18) it replaces the source with only `path.sep`. Instead it should also replace it with `"\\" + path.sep`.

**Comment by cpojer** [comment]
Can you send a PR?

**Comment by Slapbox** [comment]
Anybody working on this? What will or will not work in Metro on Windows is so finicky.

**Comment by Slapbox** [comment]
@saurabhbh21 patterns like below work for us, but I'm not sure how to make this library you mentioned work for you.

I define all of our regex patterns as strings in an array and then map over them to make the actual regexps.


```js

const exclusionList = require('metro-config/src/defaults/exclusionList');

const regexStrings = [
  '.*[\\\\]android[\\\\]ReactAndroid[\\\\].*',
  '.*[\\\\]versioned-react-native[\\\\].*',
  'node_modules[\\\\]react[\\\\]dist[\\\\].*',
  'node_modules[\\\\].cache[\\\\].*',
  'packages[\\\\]electron[\\\\].*',
  'node_modules[\\\\]electron.*',
  'website[\\\\]node_modules[\\\\].*',
  'heapCapture[\\\\]bundle.js',
  '.*[\\\\]__tests__[\\\\].*',
  `.*[\\\\]\.git[\\\\].*`, //  NOTE: Must be in backticks or ES-Lint removes "useless" escape\ character, which isn't useless, even if you disable the rule or the line
  `\\.git[\\\\].*`, //  NOTE: Must be in backticks or ES-Lint removes "useless" escape\ character, which isn't useless, even if you disable the rule or the line
  'node_modules[\\\\]webpack.*',
  'webpack_config[\\\\].*',
];

const constructBlocklist = () => {
  // return new RegExp(`${regexStart}${regexStrings.join('|')}${regexEnd}`);
  const formedRegexes = regexStrings.map(piece => new RegExp(piece));
  console.warn('The following is NOT an error:');
  console.warn(formedRegexes);
  console.warn('The preceeding is NOT an error');
  return exclusionList([...formedRegexes]);
};


```

**Comment by saurabhbh21** [comment]
@Slapbox Thanks for the response. But I'm not sure if this approach will for us. 
We're passing a text to the Microsoft-Recognizer-Text (https://www.npmjs.com/package/@microsoft/recognizers-text-suite) and getting the resolution for text into relevant entity as json. 
This library has too many files filled with regex and it need a great deal of re-write into the library (open-source project) code since the regex are being resolved into relevant entity within the library. I'm looking for some scalable solution for this.

**Comment by Slapbox** [comment]
@saurabhbh21 the Regex in the `node_modules` files is not relevant to this issue unless they're being loaded directly into your Metro configuration, like in the `blacklist/blocklist`. I think you're facing some other problem.
