### ISSUE TITLE
[Doc]Need clarify dynamic import

### ISSUE THREAD

**Issue by NE-SmallTown** [facebook/metro#580]
I notice that the [doc](https://facebook.github.io/metro/docs/bundling) says:

> meaning no dynamic requires are supported

But I tested that something like below is supported(just like we do in Web/Webpack)

```javascript
componentDidMount() {
  import('./components/Header').then(res => {
    this.setState({
      Header: res.default,
    })
  })
}
```

And from the [implementation](https://github.com/facebook/metro/blob/0.56.x/packages/metro/src/lib/bundle-modules/asyncRequire.js) seems it **supports** dynamic import too

So I'm a little confuse why the doc says "no dynamic requires are supported"?

I guees maybe it wants to say "Yes, we support dynamic import, but a little different with Webpack does. On Metro, we will not bundle the module separately and so will not fetch(by network) the module which be import dynamically because all modules must be bundled to one js file. Besides, everything else works same like Webpack"?

If I'm wrong, please let me know, thanks!

**Comment by NE-SmallTown** [comment]
@motiz88 @cpojer @MichaReiser Hi, would you mind take a look about this, thanks~

**Comment by MichaReiser** [comment]
@NE-SmallTown Dynamic imports are require or import calls with a dynamic module name, e.g. `require('./myModule' + index)`. The same applies for dynamic imports ([`collectDependencies`](https://github.com/facebook/metro/blob/master/packages/metro/src/ModuleGraph/worker/collectDependencies.js#L272-L274) throws for these). This is different to WebPack that supports limited support for dynamic expressions in imports [source](https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import).

Your example uses `async` dependencies that are supported by metro.

**Comment by NE-SmallTown** [comment]
Thanks, it's clear now
