### ISSUE TITLE
Running 2 metro servers in the same machine

### ISSUE THREAD

**Issue by ThinhVu** [facebook/metro#586]
Metro version: 0.58.0
React Native version: 0.62.2

I currently develop 2 react-native apps in the same machine (I need to run both of them at the same time).

To run 2 metro servers at the same time, I leave metro.config.js of one project as default, and change metro.config.js of the other.

I added server object with { port: 8082 } and connect corresponding app to this host.
```
module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig();

  return {
    transformer: {
      babelTransformerPath: require.resolve("react-native-svg-transformer")
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== "svg"),
      sourceExts: [...sourceExts, "svg"]
    },
    server: {
      port: 8082
    }
  };
})();
```

Then I run "react-native run-android" on each device.
The app which connected to 8081 (default metro port) working correctly.
But the app which connected to port 8082 sometime show an error: "Could not connect to development server."

Do you guys know how to fix this issue?

**Comment by vasani-arpit** [comment]
@ThinhVu How did you resolved this?

**Comment by chakrihacker** [comment]
Open debug menu and try changing the port

**Comment by ThinhVu** [comment]
> @ThinhVu How did you resolved this?
I bundled the react code to native assets then run it directly.

This is an example for Android application:
`npx react-native bundle --dev false --platform android --entry-file index.js --bundle-output ./android/app/src/main/assets/index.android.bundle --assets-dest ./android/app/src/main/res`

Hope it help.

**Comment by ThinhVu** [comment]
> Open debug menu and try changing the port

As the RN version I worked on, changing the port doens't help. It's the reason why I made this issue.

**Comment by vasani-arpit** [comment]
Thanks will try it.
