### ISSUE TITLE
How to enabled the new JSX transform of react 17.0?

### ISSUE THREAD

**Issue by pke** [facebook/metro#613]
I wonder if its already possible to use the [new JSX transform of react 17.0](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) in react-native projects.

I have updated the TS compiler to 4.1.2 but it seems more changes are required. Something needs to be added to the `metro.config.js`?

**Comment by pke** [comment]
Nevermind, I see that RN 0.64 has this already scheduled.

**Comment by wojtekmaj** [comment]
Hmmmm, just updated to RN 0.64 with no luck, getting:

```
ERROR  ReferenceError: Property 'React' doesn't exist

This error is located at:
    in App (at renderApplication.js:47)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:107)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:134)
    in AppContainer (at renderApplication.js:40), js engine: hermes
```

Were you able to enable it somehow?

**Comment by pke** [comment]
Yeah. Would be nice to read some instructions. Getting started is not updated yet

**Comment by cesargdm** [comment]
@pke Your .babelrc should look like this:

```js
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    ['@babel/plugin-transform-react-jsx', { runtime: 'automatic' }],
  ],
}
```

> Reference: https://github.com/facebook/metro/issues/646

**Comment by yfunk** [comment]
@cesargdm I was just about to hit send on the same answer 😄

@pke Also make sure to change the compiler option `jsx` to `'react-jsx'` in `tsconfig.json` and disable `'react/jsx-uses-react'` and `'react/react-in-jsx-scope'` if you are using ESLint.

**Comment by cesargdm** [comment]
@yfunk Oh the odds 😅

I would also comment that I had to reset my metro cache by doing `npm start -- --reset-cache`

👍🏽 happy coding!

**Comment by pke** [comment]
Thanks all, I'll give it a try
