### ISSUE TITLE
Error: Unable to resolve module `./http://localhost:8081/index` from ``

### ISSUE THREAD

**Issue by ajp8164** [facebook/metro#621]
**Do you want to request a *feature* or report a *bug*?**

QUESTION - Why does this error occur? My app is using Sentry and when Sentry.captureException() is included I get this error. When I remove the call to Sentry.captureException, no error. Sentry correctly receives the log and the app works as expected. This might be a Sentry issue but I don't understand why metro is complaining.

**What is the current behavior?**

```
Error: Unable to resolve module `./http://localhost:8081/index` from ``: 

None of these files exist:
  * http:/localhost:8081/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
  * http:/localhost:8081/index/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
    at ModuleResolver.resolveDependency (/Users/aphillipso/Development/driver-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/aphillipso/Development/driver-app/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/aphillipso/Development/driver-app/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at /Users/aphillipso/Development/driver-app/node_modules/metro/src/lib/transformHelpers.js:267:42
    at Server.<anonymous> (/Users/aphillipso/Development/driver-app/node_modules/metro/src/Server.js:841:41)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/aphillipso/Development/driver-app/node_modules/metro/src/Server.js:99:24)
    at _next (/Users/aphillipso/Development/driver-app/node_modules/metro/src/Server.js:119:9)
```
**What is the expected behavior?**

No error output.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

"metro-react-native-babel-preset": "^0.64.0",
"react-native": "^0.63.4",

nvm ls
->      v15.3.0
         system
default -> node (-> v15.3.0)
iojs -> N/A (default)
unstable -> N/A (default)
node -> stable (-> v15.3.0) (default)
stable -> 15.3 (-> v15.3.0) (default)
lts/* -> lts/fermium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.23.0 (-> N/A)
lts/erbium -> v12.20.0 (-> N/A)
lts/fermium -> v14.15.1 (-> N/A)

yarn --version
1.22.5

MacOS version 10.15.7

**Comment by klever34** [comment]
@ajp8164 did you find any solution to this?

**Comment by ajp8164** [comment]
No. Still an open issue for me.

**Comment by jamesjara** [comment]
I have the same issue, it's happening only in the latest version, let me figure out for a fix

**Comment by club9822** [comment]
I have this issue in ios , rn 0.64.0, android works perfectly.
By using a differnet Network (Cellphone hotspo)  ,ios works too.

typing local ip ,port address in ios app dev server dosen't help.

**Comment by markstreich** [comment]
Did you find a fix @ajp8164? I'm seeing this error today after upgrading expo 43 to 45 (RN 0.64.3 to 0.68.2)

**Comment by JameFreshket** [comment]
any update from this case?
