### ISSUE TITLE
[Feature TreeShaking]: module level tree-shaking

### ISSUE THREAD

**Issue by chang-ke** [facebook/metro#623]
Now i'm implemantation treeshaking on metro，but flowjs caused very bad experience to me😑

**Comment by kelset** [comment]
hey @chang-ke are you working on treeshaking directly in Metro, as a PR? Do you have a work in progress branch where I could check the progress - or maybe even you could open a draft PR to showcase how you are implementing it?

I'm also interested in having treeshaking in Metro :)

**Comment by chang-ke** [comment]
@kelset see here https://github.com/chang-ke/metro/pull/1

**Comment by chang-ke** [comment]
@kelset you can check process in here https://github.com/chang-ke/metro/pull/1, hope for some suggestions;

**Comment by chang-ke** [comment]
@kelset when to release experimentalImportSupport transform options for es module？

**Comment by kelset** [comment]
hey @chang-ke I don't know the answer to that question because I'm not a maintainer of Metro :)

**Comment by chang-ke** [comment]
> hey @chang-ke I don't know the answer to that question because I'm not a maintainer of Metro :)

ok，thanks
