### ISSUE TITLE
Filename in babel plugins wrong in metro server

### ISSUE THREAD

**Issue by imownbey** [facebook/metro#625]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When using a custom --projectRoot or --entry-file babel plugins have a different path for `state.file.opts.filename` with the one passed in when running `start` being incorrect, missing the entire path of whatever was passed in with `projectRoot`. I made a simple test repo [here](https://github.com/imownbey/babelwrongpath) and you can see my babel plugin [here](https://github.com/imownbey/babelwrongpath/blob/master/babel.config.js) it just outputs `state.file.opts.filename` to console.

The resulting console log is:
`yarn react-native start --projectRoot src/packages/app --reset-cache` results in:
```
transform[stdout]: /Users/ianownbey/src/babelPathWRong/index.js
```

`npx react-native bundle --entry-file src/packages/app/index.js --platform ios --bundle-output foo` results in:
```
transform[stdout]: /Users/ianownbey/src/babelPathWRong/src/packages/app/index.js
```

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
```
git clone git@github.com:imownbey/babelwrongpath.git
cd babelwrongpath
npx react-native start --projectRoot src/packages/app --reset-cache
npx react-native run-ios --project-path src/packages/app/ios
# Look at console logs to see wrong path passed to babel plugin
npx react-native bundle --entry-file src/packages/app/index.js --platform ios --bundle-output foo
# Look at console logs to see correct path passed to babel plugin
```
 
**What is the expected behavior?**
Both of them should have hte same path and ideally both be correct.
**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
https://github.com/imownbey/babelwrongpath/blob/master/metro.config.js
https://github.com/imownbey/babelwrongpath/blob/master/babel.config.js
https://github.com/imownbey/babelwrongpath/blob/master/react-native.config.js
```
ianownbey@Ian-Ownbey babelPathWRong % node --version
v15.4.0
ianownbey@Ian-Ownbey babelPathWRong % npx react-native --version
4.13.1
ianownbey@Ian-Ownbey babelPathWRong % yarn --version
1.22.10
```

**Comment by asherLZR** [comment]
Applied the following and it seems to resolve our issues.
```
diff --git a/node_modules/metro-react-native-babel-transformer/src/index.js b/node_modules/metro-react-native-babel-transformer/src/index.js
index c34c047..9c9348a 100644
--- a/node_modules/metro-react-native-babel-transformer/src/index.js
+++ b/node_modules/metro-react-native-babel-transformer/src/index.js
@@ -170,8 +170,9 @@ function buildBabelConfig(
     ...config,
   };
 }
-function transform({ filename, options, src, plugins }) {
+function transform({ filename: relativeFileName, options, src, plugins }) {
   const OLD_BABEL_ENV = process.env.BABEL_ENV;
+  const filename = path.join(options.projectRoot, relativeFileName)
   process.env.BABEL_ENV = options.dev
     ? "development"
     : process.env.BABEL_ENV || "production";
```

**Comment by robhogan** [comment]
I hadn’t seen this issue but it looks like the one fixed in https://github.com/facebook/metro/commit/de19bbd33f239de1b29aac5db290ffffe26ec468 (Metro 0.76.1 / RN 72). Thanks @asherLZR for the pointer for folks on previous versions.

I’m going to close this as fixed, but please open a new issue if anyone sees this in RN 0.72+
