### ISSUE TITLE
Cannot package Android APK after adding expo to the project

### ISSUE THREAD

**Issue by CatsNipYummy** [facebook/metro#626]
I recently integrated expo into my react-native application. When I try to package the Android application I get the following error:

**Current Behavior:**

cd android
./gradlew bundleReleaseJsAndAssets command results in the following

error index.js: (intermediate value).eachMapping is not a function. Run CLI with --verbose flag for more details.
TypeError: (intermediate value).eachMapping is not a function
    at toBabelSegments (/Users/user/testing_app/node_modules/metro/node_modules/metro-source-map/src/source-map.js:168:46)
    at /Users/user/testing_app/node_modules/metro/src/JSTransformer/worker.js:425:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/user/testing_app/node_modules/metro/src/JSTransformer/worker.js:75:24)
    at _next (/Users/user/testing_app/node_modules/metro/src/JSTransformer/worker.js:95:9)
    at /Users/user/testing_app/node_modules/metro/src/JSTransformer/worker.js: 100: 7
    at new Promise (<anonymous>)
    at /Users/user/testing_app/node_modules/metro/src/JSTransformer/worker.js:92:12
    at JsTransformer._minifyCode (/Users/user/testing_app/node_modules/metro/src/JSTransformer/worker.js:437:7)

This issue does not exist while running the debug build using 'react-native run-android'

This is what my sourceMap looks like (printed inside source-map.js inside function toBabelSegments(sourceMap))

```
{
	"version": 3,
	"sources": ["index.js"],
	"names": ["_reactNative", "r", "d", "_App", "_interopRequireDefault", "_app", "AppRegistry", "registerComponent", "appName", "App"],
	"mappings": "0CAIAA,EAAAC,EAAAC,EAAA,IACAC,EAAAC,EAAAH,EAAAC,EAAA,KACAG,EAAAJ,EAAAC,EAAA,IAEAI,EAAAA,YAAYC,kBAAkBC,EAAAA,KAAS,WAAA,OAAMC,EAAAA",
	"sourcesContent": ["/**\n * @format\n */\n\nimport {AppRegistry} from 'react-native';\nimport App from './App';\nimport {name as appName} from './app.json';\n\nAppRegistry.registerComponent(appName, () => App);\n"]
}
```

**Expected Behavior:**

The build should be completed successfully.

Metro version : 0.58.0
node : v12.16.1
npm : 7.3.0
OS : Mac OSX Big Sur (11.1)

**Comment by aufa-dot** [comment]
i have experienced the same issue, what's the solution?
