### ISSUE TITLE
Please reopen #1 issue (follow symlinks)

### ISSUE THREAD

**Issue by Strate** [facebook/metro#627]
Please reopen #1. I think people still want to share their workarounds

**Comment by chang-ke** [comment]
> Please reopen #1. I think people still want to share their workarounds

you can add symlink's parent path into watchFolders(metro.config.js)，it will helps you

**Comment by cheese-git** [comment]
> > Please reopen #1. I think people still want to share their workarounds
> 
> you can add symlink's parent path into watchFolders(metro.config.js)，it will helps you

it works for me, thanks a lot 👍🏻

**Comment by micnguyen** [comment]
Yes please. This will enable federated development (where teams may develop multiple modules locally without needing to publish packages).
