### ISSUE TITLE
How to use a different entry file?

### ISSUE THREAD

**Issue by omonk** [facebook/metro#628]
I'm using `react-native start` to run my app, I'm adding storybook-native to the app and would like to start the app but with a different entry file so I don't have to do conditional importing of storybook or the main app in the root index.js

I've not been able to find anything in the metro repo where the root `./index.js` is defined as the main entry file.

Is it possible to pick the entry file instead of defaulting to `./index.js`?

metro.config.js
```javascript
const path = require("path");
const { getDefaultValues } = require("metro-config/src/defaults");
const {
  resolver: { sourceExts }
} = getDefaultValues();

/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

const extraNodeModules = {
  assets: path.resolve(__dirname + "/src/assets/")
};

module.exports = {
  resolver: {
    extraNodeModules,
    sourceExts: [...sourceExts, "cjs"]
  },
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: true,
        inlineRequires: true
      }
    })
  }
};

```

**Comment by chang-ke** [comment]
metro does not support entry config. but you can change pathname to use different entry. for example

`http://localhost:8081/index.bundle?platform=android&dev=true&minify=false` entry is index
`http://localhost:8081/app.bundle?platform=android&dev=true&minify=false` entry is app

used server.port for different server

**Comment by pjivers-bom** [comment]
I'm having the same issue. I'm building a react-native component library using storybook, but want to reserve `index.js` for the main file of the library when publishing to npm.

**Comment by omonk** [comment]
@pjivers-bom - check out this issue thread https://github.com/storybookjs/react-native/issues/147

It's how we achieved exactly what you're trying to do

**Comment by vivex** [comment]
@omonk  wont it increase main bundle size ? as now metro will include storybook code in bundle.

**Comment by mahcloud** [comment]
@omonk please reopen this issue
