### ISSUE TITLE
document is not defined with v0.65.0

### ISSUE THREAD

**Issue by mikevercoelen** [facebook/metro#633]
When upgrading from v0.64.0 to v0.65.0 my react-native bundle is no longer compiling and getting an error:

```
document is not defined
```

What's going on here? Do more people have this?

**Comment by MichaReiser** [comment]
Thanks @mikevercoelen  for reporting this issue. Could you share a small repo or a full stack trace? I had a short look at all the changes but it's not clear to me where the issue is coming from without more information.
