### ISSUE TITLE
Replace `uglify-es` with `uglify-js`

### ISSUE THREAD

**Issue by SimenB** [facebook/metro#644]
**Do you want to request a *feature* or report a *bug*?**

Bug? Dunno 😅 

**What is the current behavior?**

https://github.com/facebook/metro/blob/e473e938c95fca9b3c6c6df54d435a1ff400fb95/packages/metro-minify-uglify/package.json#L16

``uglify-es@npm:3.3.10 is deprecated: support for ECMAScript is superseded by `uglify-js` as of v3.13.0``

https://www.npmjs.com/package/uglify-es

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

Just do `yarn install metro`

**What is the expected behavior?**

No deprecation warning when installing

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

N/A

**Comment by SakuOtonashi** [comment]
[replace uglify-es with terser](https://github.com/facebook/metro/pull/256#issuecomment-1028905778)

**Comment by robhogan** [comment]
Effectively closed by https://github.com/facebook/metro/pull/871 - we've now changed the default to `terser` instead.
