### ISSUE TITLE
[Apple M1] Don't compile on IOS metro-hermes-compiler too many open files

### ISSUE THREAD

**Issue by alexanderoskin** [facebook/metro#668]
# Bug Description

- Hermes version: 0.7.2
- React Native version: 0.64.0
- OS version: macOS 11.2.3
- Platform: arm64 (Apple M1)

# Steps To Reproduce

1. Update existing project from 0.63.4 to 0.64.0
2. Compile with Xcode

# The Expected Behavior
Pre-version compiles fine

# Error Message

```

Showing All Messages
+ PACKAGER_SOURCEMAP_FILE=

+ [[ '' == true ]]

+ /Users/alexander/Code/Sputnik/sputnik-app/node_modules/@sentry/cli/sentry-cli /Users/alexander/Code/Sputnik/sputnik-app/node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/alexander/Library/Developer/Xcode/DerivedData/SputnikApp-fjypaeaptflxsubdwkhkfnnxdzqv/Build/Products/Release-iphonesimulator/main.jsbundle --assets-dest $'/Users/alexander/Library/Developer/Xcode/DerivedData/SputnikApp-fjypaeaptflxsubdwkhkfnnxdzqv/Build/Products/Release-iphonesimulator/\320\241\320\277\321\203\321\202\320\275\320\270\320\272.app' --sourcemap-output /Users/alexander/Library/Developer/Xcode/DerivedData/SputnikApp-fjypaeaptflxsubdwkhkfnnxdzqv/Build/Intermediates.noindex/SputnikApp.build/Release-iphonesimulator/SputnikApp.build/DerivedSources/main.jsbundle.map

                    Welcome to Metro!

              Fast - Scalable - Integrated

/Users/alexander/Code/Sputnik/sputnik-app/node_modules/metro-hermes-compiler/src/emhermesc.js:81
          throw ex;
          ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:204:21)
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (/Users/alexander/Code/Sputnik/sputnik-app/node_modules/sane/src/node_watcher.js:143:12)
    at FSWatcher.emit (node:events:369:20)
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:210:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
the transform cache was reset.
Command PhaseScriptExecution failed with a nonzero exit code
```

# Additional Info

Newly created React Native project is being compiled successfully. The issue only with a existing project.

**Comment by gedeagas** [comment]
+1 i also get this error on M1 

```
warning: the transform cache was reset.
                    Welcome to Metro!
              Fast - Scalable - Integrated


/Users/gedeagas/Work/Kumparan/kumparan-mobile-app/node_modules/metro-hermes-compiler/src/emhermesc.js:81
          throw ex;
          ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:204:21)
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (/Users/gedeagas/Work/Kumparan/kumparan-mobile-app/node_modules/sane/src/node_watcher.js:143:12)
    at FSWatcher.emit (node:events:378:20)
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:210:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
```

**Comment by ddevilcore** [comment]
Same problem

**Comment by owinter86** [comment]
try deleting the yarn.lock file and peforming `yarn install`

**Comment by JonnyBurger** [comment]
`fsevents` is the module that causes it to break. Upgrade fsevents to fix it:

```diff
// yarn.lock
fsevents@^2.1.2:
-  version "2.1.3"
-  resolved "https://registry.yarnpkg.com/fsevents/-/fsevents-2.1.3.tgz#fb738703ae8d2f9fe900c33836ddebee8b97f23e"
-  integrity sha512-Auw9a4AxqWpa9GUfj370BMPzzyncfBABW8Mab7BGWBYDj4Isgq+cDKtx0i6u9jcX9pQDnswsaaOTgTmA5pEjuQ==
+  version "2.3.2"
+  resolved "https://registry.yarnpkg.com/fsevents/-/fsevents-2.3.2.tgz#8a526f78b8fdf4623b709e0b975c52c24c02fd1a"
+  integrity sha512-xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==
```

**Comment by alexanderoskin** [comment]
@JonnyBurger @owinter86 fsevents upgrade to 2.1.3 works like a charm, many thanks.

**Comment by majirosstefan** [comment]
only doing this does not always help

**Comment by endkeyCoder** [comment]
> `fsevents` is the module that causes it to break. Upgrade fsevents to fix it:
> 
> ```diff
> // yarn.lock
> fsevents@^2.1.2:
> -  version "2.1.3"
> -  resolved "https://registry.yarnpkg.com/fsevents/-/fsevents-2.1.3.tgz#fb738703ae8d2f9fe900c33836ddebee8b97f23e"
> -  integrity sha512-Auw9a4AxqWpa9GUfj370BMPzzyncfBABW8Mab7BGWBYDj4Isgq+cDKtx0i6u9jcX9pQDnswsaaOTgTmA5pEjuQ==
> +  version "2.3.2"
> +  resolved "https://registry.yarnpkg.com/fsevents/-/fsevents-2.3.2.tgz#8a526f78b8fdf4623b709e0b975c52c24c02fd1a"
> +  integrity sha512-xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==
> ```

you save me, tks bro!

**Comment by skanger** [comment]
> `fsevents` is the module that causes it to break. Upgrade fsevents to fix it:
> 
> ```diff
> // yarn.lock
> fsevents@^2.1.2:
> -  version "2.1.3"
> -  resolved "https://registry.yarnpkg.com/fsevents/-/fsevents-2.1.3.tgz#fb738703ae8d2f9fe900c33836ddebee8b97f23e"
> -  integrity sha512-Auw9a4AxqWpa9GUfj370BMPzzyncfBABW8Mab7BGWBYDj4Isgq+cDKtx0i6u9jcX9pQDnswsaaOTgTmA5pEjuQ==
> +  version "2.3.2"
> +  resolved "https://registry.yarnpkg.com/fsevents/-/fsevents-2.3.2.tgz#8a526f78b8fdf4623b709e0b975c52c24c02fd1a"
> +  integrity sha512-xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==
> ```

not working, after reinstall 'watchman', upgrade fsevent.

it can be debug on  simulator, but not archive.

any solution?

**Comment by skanger** [comment]
Failed to construct transformer:  TypeError: fsevents is not a function
    at new FSEventsWatcher (/Users/boywus/easyspark/f/node_modules/metro/node_modules/jest-haste-map/build/lib/FSEventsWatcher.js:162:20)
    at createWatcher (/Users/boywus/easyspark/f/node_modules/metro/node_modules/jest-haste-map/build/index.js:1052:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/boywus/easyspark/f/node_modules/metro/node_modules/jest-haste-map/build/index.js:1230:44)
    at /Users/boywus/easyspark/f/node_modules/metro/node_modules/jest-haste-map/build/index.js:517:21
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/boywus/easyspark/f/node_modules/metro/node_modules/jest-haste-map/build/index.js:193:24)
    at _next (/Users/boywus/easyspark/f/node_modules/metro/node_modules/jest-haste-map/build/index.js:213:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by JuxhinB** [comment]
upgrading `fsevent` didn't helped me either

my output is 

``` node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:204:21)
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (/Users/juxhinbleta/Projects/openbar_frontend/node_modules/sane/src/node_watcher.js:143:12)
    at FSWatcher.emit (node:events:513:28)
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:210:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}```

**Comment by DanielT777** [comment]
`warning: the transform cache was reset.
                 Welcome to React Native!
                Learn once, write anywhere


node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSWatcher._handle.onchange (node:internal/fs/watchers:204:21)
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (/Users/danieltirrier/Desktop/APPSPANEL/azap-react/node_modules/sane/src/node_watcher.js:143:12)
    at FSWatcher.emit (node:events:513:28)
    at FSWatcher._handle.onchange (node:internal/fs/watchers:210:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}

Node.js v18.12.1
main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
`

Same here, on M1 Pro, Ventura 13, XCode 14.1
already: upgraded watchman, fsevent.

**Comment by robhogan** [comment]
The "too many open files" error sounds like you're coming up against the limits of the macOS "FSEvents" API, which is used under the hood by `fsevents`, Watchman, and Node itself.

Newer versions of Watchman allow the use of a combined FSEvents + kqueue watch strategy to reduce the load on FSEvents (similar to newer versions of Node's `fs.watch`). You can try that mode by installing the latest version of Watchman from Homebrew and adding this line to your `.watchmanconfig` (create it in your project root if it doesn't exist already):

```json
{
  "watcher": "kqueue+fsevents"
}
```

Verify that you're using this watcher backend with `watchman watch-project /absolute/path/to/your/project/root` on the command line. You should see `watcher: "kqueue+fsevents"` in the output. Ensure you don't have `useWatchman: false` in your Metro config, and hopefully this will help - do let us know either way.

**Comment by eliot-ye** [comment]
> 

I have the same problem. Have you solved it?

**Comment by eliot-ye** [comment]
> ```
>                  Welcome to React Native!
>                 Learn once, write anywhere
> 
> 
> node:events:491
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: EMFILE: too many open files, watch
>     at FSWatcher._handle.onchange (node:internal/fs/watchers:204:21)
> Emitted 'error' event on NodeWatcher instance at:
>     at NodeWatcher.checkedEmitError (/Users/danieltirrier/Desktop/APPSPANEL/azap-react/node_modules/sane/src/node_watcher.js:143:12)
>     at FSWatcher.emit (node:events:513:28)
>     at FSWatcher._handle.onchange (node:internal/fs/watchers:210:12) {
>   errno: -24,
>   syscall: 'watch',
>   code: 'EMFILE',
>   filename: null
> }
> 
> Node.js v18.12.1
> main.jsbundle does not exist. This must be a bug with
> + echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
> ```
> 
> Same here, on M1 Pro, Ventura 13, XCode 14.1 already: upgraded watchman, fsevent.

I have the same problem. Have you solved it?

**Comment by dalbeer22g** [comment]
> ```diff
> 2.1.3
> ```

any success?

**Comment by dalbeer22g** [comment]
> > `fsevents` is the module that causes it to break. Upgrade fsevents to fix it:
> > ```diff
> > // yarn.lock
> > fsevents@^2.1.2:
> > -  version "2.1.3"
> > -  resolved "https://registry.yarnpkg.com/fsevents/-/fsevents-2.1.3.tgz#fb738703ae8d2f9fe900c33836ddebee8b97f23e"
> > -  integrity sha512-Auw9a4AxqWpa9GUfj370BMPzzyncfBABW8Mab7BGWBYDj4Isgq+cDKtx0i6u9jcX9pQDnswsaaOTgTmA5pEjuQ==
> > +  version "2.3.2"
> > +  resolved "https://registry.yarnpkg.com/fsevents/-/fsevents-2.3.2.tgz#8a526f78b8fdf4623b709e0b975c52c24c02fd1a"
> > +  integrity sha512-xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==
> > ```
> 
> not working, after reinstall 'watchman', upgrade fsevent.
> 
> it can be debug on simulator, but not archive.
> 
> any solution?

@skanger did you find any solution?

**Comment by michalnatkanski** [comment]
Thanks, it works for me on rn v.0.74 and node 18.14.2

**Comment by codinsonn** [comment]
Running into this again on node 20, any new fix in 2024?

**Comment by maxlxq** [comment]
Thanks, it works for me on rn v.0.75.3 and node 20.17.0.

**Comment by grandwaterman** [comment]
npm install fsevents fixed mine, RN team, this problem still exist now Dec 2024.

**Comment by Propulse1** [comment]
What worked for me, I changed my node version to `18.17.0` then I deleted the node_modules folder then re-install using `npm i`
