### ISSUE TITLE
There is no blacklistRE option in docs. But it works.

### ISSUE THREAD

**Issue by CavidM** [facebook/metro#672]
I need to exclude npm workspaces folder from metro runner config. The given method in docs `blockList` does not work.
But I found another method `blacklistRE ` on stackoverflow.  It works. But it does not present in metro documention.
Here is my current metro configuration. 
npm -v: 7.6.0
expo -V 4.4.4
OS: windows 10

`const blacklist = require('metro-config/src/defaults/blacklist');

module.exports = {

    resolver: {
        blacklistRE: blacklist([
            new RegExp(/packages\/common1\/.*/)
            ]),
    },
};
`

**Comment by motiz88** [comment]
Which version of Metro are you using? We added `blockList` and deprecated `blacklistRE` in https://github.com/facebook/metro/commit/94c0b541b4bfa17aee4efa0f1969565522ce830d  (released in [v0.61.0](https://github.com/facebook/metro/releases/tag/v0.61.0))

**Comment by CavidM** [comment]
Metro version is 0.59.0
Expo used it under the hood.
Then we need to wait for expo updates.

**Comment by aleksamrakovic** [comment]
I didnt want to open new issue, but seems that blockList doesnt actually work.

resolver: {
    blockList: new RegExp(/\/__mocks__\/.*/),
  },
  
  i want to exclude my mocks folder, but it gets bundled i can access localhost:xxxx/__mocks__/config.ts for example
  
  Am i doing something wrong here? TY
