### ISSUE TITLE
Watch changes in json files

### ISSUE THREAD

**Issue by RWOverdijk** [facebook/metro#673]
I'm using @expo/metro-config and I'd like to watch changes in my project's json files. Right now I have a metro config in which I set up watchman myself just so I can watch changes in json files (add, update and delete) and respond to that.

That's fine because I use watchman, but metro doesn't require watchman so it's not ideal. I need to bundle json files together when one of them changes (watchman `subscription` event) and I'd like to be able to do so without requiring watchman to be installed.

Besides watching, I also need an initial list of json files (which I now do with the watchman `query` command).

I tried the docs as well as google and going through the issues for this repo but couldn't find a solution. Is this simply a missing feature? Or am I just bad at reading?

**Comment by motiz88** [comment]
Is this issue unique to JSON files? What are you trying to achieve at a high level? (e.g. Fast Refresh when some JSON source file is updated?)

**Comment by RWOverdijk** [comment]
Yes. But also I don't care anymore. Also also it's a year old now so... 🤷‍♂️
