### ISSUE TITLE
Upgrade ws package to 5.2.3

### ISSUE THREAD

**Issue by Flavyoo** [facebook/metro#674]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
There is a security vulnerability with the current version of ws, that requires it to be upgraded to 5.2.3.
This is also an issue for any packages in metro that use a ws version before than 5.2.3

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

Please see: https://github.com/websockets/ws/security/advisories/GHSA-6fc8-4gx4-v693

**What is the expected behavior?**

No security vulnerability

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

**Comment by jonthysell** [comment]
We were in the process of updating our versions in react-native-windows of ws to clear the vulnerability alerts but trying to force this with a yarn resolution breaks web debugging.

**Comment by motiz88** [comment]
Looks like we need to go through 4 major versions' worth of breaking changes to get to `ws` v5.x.

https://github.com/websockets/ws/releases/tag/5.0.0
https://github.com/websockets/ws/releases/tag/4.0.0
https://github.com/websockets/ws/releases/tag/3.0.0
https://github.com/websockets/ws/releases/tag/2.0.0

At a glance, we're affected by at least https://github.com/websockets/ws/pull/1099 in v3.x ([here](https://github.com/facebook/metro/blob/af23a1b27bcaaff2e43cb795744b003e145e78dd/packages/metro/src/lib/attachWebsocketServer.js#L61)) and https://github.com/websockets/ws/commit/63e275e75f8ab8f4385e7ef104a74c582cd0c793 in v4.x ([here](https://github.com/facebook/metro/blob/af23a1b27bcaaff2e43cb795744b003e145e78dd/packages/metro/src/lib/attachWebsocketServer.js#L22)). Probably a few other changes as well.

**Comment by kelset** [comment]
@motiz88 anything we can do to help bumping ws? As far as I can see the main react-native repo is already on 6.1.4 https://github.com/facebook/react-native/blob/ca440b91000530e0f9d7cbb4109f25cdd9d135a5/package.json#L121

(ps: maybe worth closing this issue and redirect here? https://github.com/facebook/metro/issues/413)
