### ISSUE TITLE
watch

### ISSUE THREAD

**Issue by tingtien** [facebook/metro#692]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

**What is the expected behavior?**

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

**Comment by chrisbobbe** [comment]
This issue is basically empty; the description is just template text. Was there more information you wanted to add, @tingtien? Otherwise, I think it should be closed.
