### ISSUE TITLE
SyntaxError: Unexpected token = after upgrading to RN 65

### ISSUE THREAD

**Issue by cparello** [facebook/metro#703]
I just upgraded from 64.1 to 65.1 by following the upgrade helper.

But I started getting this error and have not been able to fix it.

I have upgraded node/npm to 14.17 and done everything else I can think of. Is this a bug?

22:55:32 > Task :react-native-community_masked-view:compileReleaseLibraryResources
22:55:32 
22:55:32 > Task :app:bundleReleaseJsAndAssets FAILED
22:55:32 error Unexpected token =.
22:55:32 /node_modules/metro/src/Server.js:350
22:55:32   processRequest = (req, res, next) => {
22:55:32                  ^
22:55:32 
22:55:32 SyntaxError: Unexpected token =
22:55:32     at new Script (vm.js:79:7)
22:55:32     at createScript (vm.js:251:10)
22:55:32     at Object.runInThisContext (vm.js:303:10)
22:55:32     at Module._compile (internal/modules/cjs/loader.js:656:28)
22:55:32     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
22:55:32     at Module.load (internal/modules/cjs/loader.js:598:32)
22:55:32     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
22:55:32     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
22:55:32     at Module.require (internal/modules/cjs/loader.js:636:17)
22:55:32     at require (internal/modules/cjs/helpers.js:20:18)
22:55:32 info Run CLI with --verbose flag for more details.
22:55:33

**Comment by Sasha411** [comment]
Facing same issue tried different node version still not working

**Comment by xploSEoF** [comment]
This is a clear syntax bug.

It seems that whatever unpacks the class from the library into the src directory is clearly not working correctly as I'm seeing quite a few functions badly defined on the JS class. For example, `processRequest` here is clearly wrong, but fixing it only highlights more functions that are incorrect.

```
  }

  processRequest = (req, res, next) => {
    this._processRequest(req, res, next).catch(next);
  };

  _parseOptions(url) {
  ```

**Comment by xploSEoF** [comment]
Further investigation revealed that this is caused by using an outdated version of Node. This typically occurs if you have installed node separately to NVM.

Ordinarily, NVM isn't supported by React Native, but that just asks for more problems. Instead. I'm modified the "Bundle React Native code and images" phase, adding in a bit to load NVM if it has been installed at the start of the script:

```JS
# Fix for machines using nvm
if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
. "$HOME/.nvm/nvm.sh"
elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
. "$(brew --prefix nvm)/nvm.sh"
fi```

**Comment by vivekvardhanadepu** [comment]
I know it's a hack. But, this helped me
- install react-native-cli globally
   `npm install -g react-native-cli`
- now init the project
    `npx react-native init awesomeProject`
- After successful init, remove the global cli
    `npm uninstall -g react-native-cli`

**Comment by bolingsun** [comment]
this reason is node vesion too low probably!  

RN 0.66 metro/src/Server.js is like this (line 350)  :
  processRequest = (req, res, next) => {
    this._processRequest(req, res, next).catch(next);
  };

but RN0.64 metro/src/Server.js is  : 
 _processRequest(req, res, next) {
    var _this7 = this;

first, i use node 10.13.0 version , this Problem is happen。

so. i change node version to 12.10.0 , amazing,   is ok!

**Comment by AdamSarach** [comment]
I had similar problem when upgrading RN. I use Ubuntu 20.04 with Android Studio and NVM. I solved it by linking node location in .nvm directory with location that Android Studio searches.

`ln -s $(which node) /usr/local/bin/node` solved my problem

**Comment by Z1hgq** [comment]
run `nvm alias default xxx` to make the node version of metro terminal same as your project building terminal, node version is 14.17.0 for me

**Comment by Z1hgq** [comment]
> run `nvm alias default xxx` to make the node version of metro terminal same as your project building terminal, node version is 14.17.0 for me

https://stackoverflow.com/questions/69192815/metro-builder-syntaxerror-unexpected-token-after-upgrading-to-react-native-0

**Comment by zichengbohan** [comment]
> run `nvm alias default xxx` to make the node version of metro terminal same as your project building terminal, node version is 14.17.0 for me

it's work.

**Comment by bobrom** [comment]
None of nvm aliases worked in my case. I was only able to resolve it with upgrading my system node version:
```
brew install node@14
brew unlink node
brew link --overwrite node@14
```

**Comment by Z1hgq** [comment]
You can try to set the default node version of nvm to 14.

Roman ***@***.***>于2022年11月13日 周日01:15写道：
