### ISSUE TITLE
got ERR_OSSL_EVP_UNSUPPORTED when using node 17 and react 17 on expo

### ISSUE THREAD

**Issue by rafipiccolo** [facebook/metro#722]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
the error is coming from metro.
one way to get it is to run "expo start".
it returns a qrcode and then shows this error : ERR_OSSL_EVP_UNSUPPORTED

im sorry i dont know how to acces metro config/parameters.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
```
# npm install -g expo-cli
# expo init my-app
# cd my-app
# expo start
Logs for your project will appear below.
Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at stableHash (/root/docker/gextrareact/node_modules/metro-cache/src/stableHash.js:19:8)
    at Object.getCacheKey (/root/docker/gextrareact/node_modules/metro-transform-worker/src/index.js:647:7)
    at getTransformCacheKey (/root/docker/gextrareact/node_modules/metro/src/DeltaBundler/getTransformCacheKey.js:32:19)
    at new Transformer (/root/docker/gextrareact/node_modules/metro/src/DeltaBundler/Transformer.js:180:28)
    at /root/docker/gextrareact/node_modules/metro/src/Bundler.js:58:29 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**What is the expected behavior?**
working

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

metro : 0.64.0

System:
OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
Shell: 5.0.17 - /bin/bash
Binaries:
Node: 17.0.1 - /usr/local/bin/node
Yarn: 1.22.15 - /usr/local/bin/yarn
npm: 8.1.1 - /usr/local/bin/npm
npmPackages:
expo: ^43.0.0 => 43.0.0
react: 17.0.1 => 17.0.1
react-dom: 17.0.1 => 17.0.1
react-native: 0.64.2 => 0.64.2
npmGlobalPackages:
expo-cli: 4.12.10
Expo Workflow: managed

**Comment by madandrija** [comment]
> Encountered the same error after upgrading to node `v17.0.1`. The error seems to originate from the `transformFile` method in the `Bundler` class. I suspect that the dependency graph is failing to load which results in an undefined transformer instance. I'm using `react-native-cli` so I doubt the error has any relation to Expo. Took all the necessary steps to reset metro's cache which didn't help. Perhaps there's a transformer option that can be added to the configuration file that I'm not aware of? The only solution I can think of for now is to downgrade node and wait for a patch.
> 
> The screenshot of my error stack. ![digital-envelope-routines-initialization-error](https://user-images.githubusercontent.com/76426609/138879460-56f6d5ee-461b-41c5-bd89-6616f717b71b.png)

I have the same issue with my non-expo application, the only thing that worked for me was also:

> Resolved the issue by running the application with the latest LTS version of node (`16.13.0`). The new major release has most likely introduced a breaking change within metro.
