### ISSUE TITLE
Security risk

### ISSUE THREAD

**Issue by KennyGoi** [facebook/metro#748]
**Affected files**:
metro/src/Server.js
`932: .split("-"),`

metro/src/Server.js
`930: const _req$headers$range$re = req.headers.range`

metro/src/Server.js
`933: _req$headers$range$re2 = _slicedToArray(_req$headers$range$re, 2),`

metro/src/Server.js
`12: function _slicedToArray(arr, i) {`

metro/src/Server.js
`16: _unsupportedIterableToArray(arr, i) ||`

metro/src/Server.js
`117: function _unsupportedIterableToArray(o, minLen) {`

metro/src/Server.js
`119: if (typeof o === "string") return _arrayLikeToArray(o, minLen);`

metro/src/Server.js
`136: function _arrayLikeToArray(arr, len) {`

metro/src/Server.js
`137: if (len == null || len > arr.length) len = arr.length;`

metro/src/Server.js
`139: for (var i = 0, arr2 = new Array(len); i < len; i++) arr2[i] = arr[i];`

metro/src/Server.js
`1012: const host = req.headers.host;`

metro/src/Server.js
`1022: host,`

metro/src/Server.js
`78: function _objectSpread(target) {`

metro/src/Server.js
`79: for (var i = 1; i < arguments.length; i++) {`

metro/src/Server.js
`1011: const urlObj = url.parse(req.url, true);`

metro/src/Server.js
`1019: _objectSpread({}, urlObj),`

metro/src/Server.js
`78: function _objectSpread(target) {`

metro/src/Server.js
`79: for (var i = 1; i < arguments.length; i++) {`

**Risks**:
An attacker could provide a very high loop iteration count, causing the loop to go on for prolonged periods of time, potentially causing the application to stop responding. Additionally, if the operation inside the loop is tied to some exhaustible functionality, it may cause bloat elsewhere; For example - if file writes occur inside the loop, then an attacker can cause that file to bloat by simply engaging this file writing capability a very high amount of times.

The application relied on a user-provided value to determine the number of iterations performed by a loop, without enforcing a limited range for this value.

**Comment by rh389** [comment]
Thanks, but given this is a development server I don't think these concerns are applicable. The server shouldn't be reachable by attackers at all.
