### ISSUE TITLE
error attachToServer is not a function

### ISSUE THREAD

**Issue by ViktorVojtek** [facebook/metro#777]
Hello,

I've encounter a following issue with metro bundler.

Everytime I want to start metro server it throw the following error:

error attachToServer is not a function.
TypeError: attachToServer is not a function
    at Object.runServer [as func] (/Users/viktorvojtek/Projects/Room/app/node_modules/@react-native-community/cli-plugin-metro/build/commands/start/runServer.js:131:7)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.handleAction (/Users/viktorvojtek/Projects/Room/app/node_modules/@react-native-community/cli/build/index.js:192:9)

My situation is following:

I've created a new github branch  and upgraded the RN version from 0.65.1 to 0.67.2. everything works fine for few days.

After some work on project I've decided to go back to RN version 0.65.1 because of some performance issues in part of my project.
I wanted to check if it's because of newer version of RN or it's because of something else. I've done this several times before with no similar issue...

I changed branches in project, removed node_modules, removed Pods and all .lock files.

I install back all node_modules with yarn.

I've start metro with --reset-cache flag.

It always throw the error above.
<img width="568" alt="Screenshot 2022-02-18 at 15 23 40" src="https://user-images.githubusercontent.com/13499872/154702057-0db5dc55-bb4d-40e9-9ed9-89fd0230dfcf.png">

**Comment by ViktorVojtek** [comment]
@caiorrs I've try to switch to branch where I have RN 0.67.2 what work before downgrade, removed node_modules, pods and everything, installed everything back again and still the same issue with "attachToServer is not a function"...

So I have two branches with two versions of RN but none of it works...

But new assembled RN project works.

**Comment by caiorrs** [comment]
> 

I have just tried to create a new project, it does not work either

**Comment by ddeschenes-lacapitale** [comment]
Same for me, starting this morning.

**Comment by thymikee** [comment]
Fix published. Please test by invalidating the lock file and this issue can be closed.

**Comment by kmart999** [comment]
Works on our end. Thank you very much.

**Comment by caiorrs** [comment]
10min ago it was not working, but now it is, thanks =D

**Comment by ddeschenes-lacapitale** [comment]
Fastest fix ever. Thanks @ViktorVojtek for your proactivity !

**Comment by rh389** [comment]
Thanks for the quick fix @thymikee 🙏
