### ISSUE TITLE
Missing dependency on metro-transform-worker

### ISSUE THREAD

**Issue by jcreamer898** [facebook/metro#805]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When requiring metro-config directly, there is a usage of an undeclared dependency in the following:
https://github.com/facebook/metro/blob/main/packages/metro-config/src/defaults/index.js#L141

The metro-config [package.json](https://github.com/facebook/metro/blob/main/packages/metro-config/package.json) lacks a dependency on "metro-transform-worker", and therefore that require.resolve will fail.

In particular, the @react-native-community/cli requires metro-config...

https://github.com/react-native-community/cli/blob/e84a9a6f965aa9f35cea797f02f57186f482bd36/packages/cli-plugin-metro/src/tools/loadMetroConfig.ts#L6

This is where the problem comes from. Because they require metro-config directly, the cli fails to run and pickup metro-transform-worker.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

**What is the expected behavior?**
It's expected that the defaults work when required directly.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
any version of metro, node 16, linux

**Comment by Stuart-Wilcox** [comment]
+1 on this

**Comment by robhogan** [comment]
Thanks for the report, opened #817 to fix.
