### ISSUE TITLE
[docs] question: any possible read about `getTransformOptions` more in detail?

### ISSUE THREAD

**Issue by donni106** [facebook/metro#845]
At https://facebook.github.io/metro/docs/configuration/#transformer-options there is only mentioned that there are `getTransformOptions` but not in detail. I would like to know more about:

```js
getTransformOptions: async () => ({
  transform: {
    experimentalImportSupport: false,
    inlineRequires: true
  }
})
```

Especially these to keys are used in my project but I do not know why. It was auto included.
I would like to know more in detail what these are for.
Thanks.

**Comment by danilobuerger** [comment]
Inline Requires: https://reactnative.dev/docs/ram-bundles-inline-requires#inline-requires
