### ISSUE TITLE
Defining a metro bundler cache server

### ISSUE THREAD

**Issue by daniel-azu** [facebook/metro#851]
Maybe someone can help me with defining a metro bundler cache server?
I tried understand how to do that by the [docs](https://facebook.github.io/metro/docs/caching/) but I'm not sure how should I do that

**Comment by huntie** [comment]
Hi @daniel-azu,

We've not yet included examples for this in our docs but I will note it as an area for expansion.

In the meantime you can check out the type interface for a `CacheStore` here: https://github.com/facebook/metro/blob/main/packages/metro-cache/src/types.flow.js#L13-L17. The basic idea is the class instances you provide will be consulted by Metro in order and need to implement each of those 3 member functions.
