### ISSUE TITLE
MergeConfig doesn't merge babelTransformerPath properly

### ISSUE THREAD

**Issue by Maclay74** [facebook/metro#852]
Something is totally wrong with the function.

Take a look, I'm trying to merge two configurations:

```js 
module.exports = (async () => {
  const { resolver: { sourceExts, assetExts } } = await getDefaultConfig();

  // First config
  const sassTransformer = {
    transformer: {
      babelTransformerPath: require.resolve("react-native-sass-transformer"),
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== "svg"),
      sourceExts: [...sourceExts, "svg",  "scss", "sass"]
    },
  }
 
  // Second config
  const svgTransformer = {
    transformer: {
      babelTransformerPath: require.resolve("react-native-svg-transformer"),
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== "svg"),
      sourceExts: [...sourceExts, "svg",  "scss", "sass"]
    },
  }

  // Total config
  return mergeConfig(sassTransformer, svgTransformer);
})();
```

But mergeConfig returns next: 
```js
{
  transformer: {
    babelTransformerPath: 'app\\node_modules\\react-native-svg-transformer\\index.js'
  },
  resolver: {
    assetExts: [
      'bmp',  'gif',  'jpg',  'jpeg',
      'png',  'psd',  'webp', 'm4v',
      'mov',  'mp4',  'mpeg', 'mpg',
      'webm', 'aac',  'aiff', 'caf',
      'm4a',  'mp3',  'wav',  'html',
      'pdf',  'yaml', 'yml',  'otf',
      'ttf',  'zip'
    ],
    sourceExts: [
      'js',   'jsx',
      'json', 'ts',
      'tsx',  'svg',
      'scss', 'sass'
    ],
    dependencyExtractor: undefined,
    hasteImplModulePath: undefined
  },
  cacheStores: undefined,
  serializer: {},
  server: {},
  symbolicator: {},
  watcher: { watchman: {} }
}
```

So only the last `babelTransformerPath` gets into the configuration. Therefore, I can't use sass transformer, it doesn't work:
```js
error: SyntaxError: app\src\components\screen\styles.scss: Unexpected token (2:0)

  1 |
> 2 | .screen {
    | ^
  3 |   background: #292C2E;
  4 |   flex: 1;
  5 |   //align-items: center;
```

I tried to understand this behaviour from the source code, and I see that it does override instead of merging. 

Maybe I don't understand the way it should work, but I was looking at examples from [here](https://stackoverflow.com/a/69045068/5306567), and they supposed to work.

Thanks.

**Comment by huntie** [comment]
Hi @Maclay74,

`mergeConfig` is behaving correctly above — but it looks like that StackOverflow answer may be incomplete. Here's why:

1. The `transformer.babelTransformerPath` config option ([docs](https://facebook.github.io/metro/docs/configuration/#babeltransformerpath)) only accepts a `string` value, and therefore it would not be possible to assign two strings in any case.
2. `mergeConfig` is correctly overriding the common `transformer.babelTransformerPath` key as they are present in both objects, and the second one takes precedence. Note also that any `Array` or `Function` options similarly will be overridden — this is intended behaviour.
<img width="985" alt="image" src="https://user-images.githubusercontent.com/2547783/183381454-cacd23b6-9ebb-41d2-bac1-9f7c440520db.png">

I think the significant part in the answer given is the implementation in the `"./transformer"` module which is not provided. This module could contain a transform function that runs the input through two transform steps, which is a solution.

```js
let config2 = {
    transformer: {
      babelTransformerPath: require.resolve("./transformer"), // react-native-obfuscating-transformer
```

In that example, the `'react-native-svg-transformer'` value supplied in `config1` is overridden and never read by Metro, so the implementation of `react-native-obfuscating-transformer` is presumed to provide the correct behaviour on its own.
