### ISSUE TITLE
Error: Cannot find module 'metro-core' (but module exist)

### ISSUE THREAD

**Issue by vladbraiko** [facebook/metro#853]
after upgrading expo to last version I get `Error: Cannot find module 'metro-core'` when running `expo start`

reinstalling packages doesn't work

```
"expo": "^46.0.0"
"metro": "^0.72.0"
"metro-core": "^0.72.0"
"react-native": "0.69.4"
```

<img width="991" alt="Screenshot 2022-08-10 at 23 33 36" src="https://user-images.githubusercontent.com/55985065/184014949-e769d2a9-23da-47db-a43e-929e866bf836.png">

**Comment by robhogan** [comment]
Hi, thanks for the report. Can I ask what package manager you're using to install dependencies?

**Comment by vladbraiko** [comment]
> Hi, thanks for the report. Can I ask what package manager you're using to install dependencies?

tried both npm and yarn

**Comment by robhogan** [comment]
This looks like an issue with the way `@expo/cli` is installed or being executed - the paths look like it's running from a global location and unfortunately as I'm no Expo expert I'm not sure if that's correct, or how it's designed to pick up your project's Metro dependencies. I'd recommend opening an issue over on [`expo/expo`](https://github.com/expo/expo) if this is still causing problems.
