### ISSUE TITLE
metro-resolver bug: resolve logic assumes fromModule name does not have a path separator

### ISSUE THREAD

**Issue by SlyryD** [facebook/metro#860]
metro-resolver bug: resolve logic assumes fromModule name does not have a path separator (e.g., @foo/bar)

expected behavior: resolve logic works regardless of whether fromModule has a path separator

Example package.json:
`{ "name": "@foo/bar", "browser": { "util": "./lib/polyfills/util.js" } }`

Say the @foo/bar package is in /path/to/node_modules/@foo/bar, then `resolve()` will check /path/to/node_modules/@foo for ./lib/polyfills/util.js instead of /path/to/node_modules/@foo/bar. This is because https://github.com/facebook/metro/blob/main/packages/metro-resolver/src/resolve.js#L73 slices the `originModulePath` at the next path separator after node_modules. This does not work for modules with a path separator in the name.

**Comment by robhogan** [comment]
> slices the `originModulePath` at the next path separator after node_modules.

That's true, but it then joins with `realModuleName`, which can itself contain path separators. Metro does support scoped packages in general. However, the non-standard object `browser` field isn't something Metro supports at all.

As noted on the PR, I'm going to close this as I don't think it identifies a concrete issue in Metro - if this resolution is meant to be supported in [`microsoft/rnx-kit`](https://github.com/microsoft/rnx-kit) (presuming from the PR that's what you're using) there might be an issue there, or there might be an issue with Metro's `resolveRequest` mechanism, but unless you can narrow it down to a repro without the use of `rnx-kit` the best bet is to open an issue there first.

**Comment by tido64** [comment]
FWIW, I can reproduce this issue with minimal Metro config:

```js
module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: true,
        inlineRequires: true,
      },
    }),
  },
};
```

Symlinks don't work, so I had to manually copy `@foo/bar` into `packages/car/node_modules`.

Steps:

```
yarn
cd packages/car
mkdir -p node_modules/@foo
cp -R ../bar node_modules/@foo
yarn bundle
```

**Comment by SlyryD** [comment]
I realized this is a feature request for ["aliasFields"](https://webpack.js.org/configuration/resolve/#resolvealiasfields) in the metro-config. I want to be able to supply paths to polyfills in my package.json, which we currently do with the "browser" field. I would be happy to change the name of the field to "react-native" or something similar if "aliasFields" were available in the metro-config.

**Comment by SlyryD** [comment]
https://github.com/microsoft/rnx-kit/issues/1935#issuecomment-1292828661

**Comment by SlyryD** [comment]
Ah "browser" is supposed to be supported! https://github.com/facebook/metro/blob/623b55d54874c77ee51bca6424fca9c3156678ae/docs/Resolution.md#redirectmodulepath-string--string--false
