### ISSUE TITLE
Cannot GET /json/ (React Native)

### ISSUE THREAD

**Issue by Aleksandern** [facebook/metro#867]
Hello.

`http://localhost:8081/json` returns error `Cannot GET /json/`

`http://localhost:8081` works fine.

What can be the problem?

System:
OS: macOS 12.4
CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
Memory: 29.08 MB / 32.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
Yarn: 1.22.11 - ~/.nvm/versions/node/v16.13.2/bin/yarn
npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
Watchman: 2022.07.04.00 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.11.3 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
Android SDK:
Android NDK: 21.3.6528147
IDEs:
Android Studio: 2021.2 AI-212.5712.43.2112.8609683
Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
Languages:
Java: 11.0.15 - /usr/bin/javac
npmPackages:
@react-native-community/cli: 7.0.3 => 7.0.3
react: 18.1.0 => 18.1.0
react-native: 0.68.2 => 0.68.2
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

 "metro": "0.71.1",
 "metro-babel-register": "0.71.1",
 "metro-react-native-babel-preset": "0.71.1",
 "metro-resolver": "0.71.1",

**Comment by robhogan** [comment]
It looks like you or whatever tool you're using is incorrectly adding a trailing `/`. 

Metro's inspector proxy has a `/json` endpoint and various endpoints under that, but **not** `/json/`.

### `/json`
```sh
$ curl http://localhost:8081/json
[]
```

### `/json/version`
```sh
$ curl http://localhost:8081/json/version
{
  "Browser": "Mobile JavaScript",
  "Protocol-Version": "1.1"
}
```

### `/json/`
```sh
$ curl http://localhost:8081/json/
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /json/</pre>
</body>
</html>
```



If you're seeing this from some tool or workflow, could you reopen with a bit more context? Thanks!

**Comment by robhogan** [comment]
Maybe unrelated, but this looks odd:

```
react: 18.1.0 => 18.1.0
react-native: 0.68.2 => 0.68.2
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

"metro": "0.71.1",
```

With React Native 0.68.2 you'd normally be using React 17 and Metro 0.67.

**Comment by Aleksandern** [comment]
@robhogan 
Thanks for your response.
It's "react-native": "0.68.2", "react": "18.1.0", "metro": "0.71.1",

>$ curl http://localhost:8081/json

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Redirecting</title>
</head>
<body>
<pre>Redirecting to <a href="/json/">/json/</a></pre>
</body>
</html>
```

That worked okay and then stop working. I don't know why.
