### ISSUE TITLE
Running metro in parallel

### ISSUE THREAD

**Issue by daniel-azu** [facebook/metro#869]
We need to run several `metro bundle` in parallel, does it supported?

**Comment by robhogan** [comment]
I'm not quite sure what you have in mind, but I think the answer is "yes". We support:

 - Running multiple `metro build` CLI commands in parallel (eg, the React Native release bundling step)
 - Running a Metro server and sending it multiple HTTP requests for JS bundles in parallel 
 - Running multiple Metro server instances simultaneously (on different ports)
 
 If you run in to a problem feel free to open an issue
