### ISSUE TITLE
Support for Typescript 4.9.x

### ISSUE THREAD

**Issue by alicenoknow** [facebook/metro#899]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

No support for Typescript 4.9.x and new operator `satisifes`.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
\- 

**What is the expected behavior?**

Support for new TS, especially new operator `satisfies`. Metro uses older version of Babel which doesn't support new TS, Babel supports TS 4.9.x from version 7.20.x.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

**Comment by robhogan** [comment]
Hi @alicenoknow, we'll be bumping our *minimum* Babel version in the next release, but in the meantime - Metro's Babel dependencies are all specified with a range like "^7.x.y", so your package manager (Yarn?) should resolve to 7.20 (the latest in the semver range) in any new project, or in an existing project by deleting your `yarn.lock` and re-running `yarn`. 

As far as we know, Metro is fully compatible with 7.20.

**Comment by robrechtme** [comment]
Deleting the lock file and reinstalling node modules worked for me. Thanks @robhogan! Also make sure your ESLint and Prettier are up to date, if you use those.  

I think this issue can be closed.
