### ISSUE TITLE
Failed to construct transformer:  Error: Cannot parse /Path/package.json as JSON: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Arnav7501** [facebook/metro#900]
Tried many solutions, but when I run npm start , I get
Failed to construct transformer:  Error: Cannot parse /Users/arnavchowdhry/Downloads/Facebook-main/.nvm/test/fast/Unit tests/mocks/project_dirs/no-nesting-both/package.json as JSON: Unexpected end of JSON input
    at Object.worker (/Users/arnavchowdhry/Downloads/Facebook-main/node_modules/jest-haste-map/build/worker.js:146:13)
    at execFunction (/Users/arnavchowdhry/Downloads/Facebook-main/node_modules/jest-worker/build/workers/processChild.js:137:17)
    at execHelper (/Users/arnavchowdhry/Downloads/Facebook-main/node_modules/jest-worker/build/workers/processChild.js:116:5)
    at execMethod (/Users/arnavchowdhry/Downloads/Facebook-main/node_modules/jest-worker/build/workers/processChild.js:120:5)
    at process.messageListener (/Users/arnavchowdhry/Downloads/Facebook-main/node_modules/jest-worker/build/workers/processChild.js:38:7)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:939:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  type: 'Error'
}

I'm using Expo/vscode, on a m1 mac, 
node version: v16.17.0
npm version: 8.15.0

Any help would be greatly appreciated

**Comment by huntie** [comment]
Please provide more info — for instance, the Expo and Metro versions which you are running against, and the contents of the JSON file which cannot be parsed.

At first glance:
- `jest-haste-map` is a renamed package and indicates you're using an older release of Metro.
- The minimum Node.js version in support for Metro is 14.x (and was 12.x previously). Expo requires a recent LTS release: **please try under `nvm use 16`** (or 18).

**Comment by Arnav7501** [comment]
My expo version is 5.4.11, unsure how to my Metro version however.
this is the contents of the questionable file: 
'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});
exports.getSha1 = getSha1;
exports.worker = worker;

function _crypto() {
  const data = require('crypto');

  _crypto = function () {
    return data;
  };

  return data;
}

function path() {
  const data = _interopRequireWildcard(require('path'));

  path = function () {
    return data;
  };

  return data;
}

function fs() {
  const data = _interopRequireWildcard(require('graceful-fs'));

  fs = function () {
    return data;
  };

  return data;
}

var _blacklist = _interopRequireDefault(require('./blacklist'));

var _constants = _interopRequireDefault(require('./constants'));

var dependencyExtractor = _interopRequireWildcard(
  require('./lib/dependencyExtractor')
);

function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : {default: obj};
}

function _getRequireWildcardCache(nodeInterop) {
  if (typeof WeakMap !== 'function') return null;
  var cacheBabelInterop = new WeakMap();
  var cacheNodeInterop = new WeakMap();
  return (_getRequireWildcardCache = function (nodeInterop) {
    return nodeInterop ? cacheNodeInterop : cacheBabelInterop;
  })(nodeInterop);
}

function _interopRequireWildcard(obj, nodeInterop) {
  if (!nodeInterop && obj && obj.__esModule) {
    return obj;
  }
  if (obj === null || (typeof obj !== 'object' && typeof obj !== 'function')) {
    return {default: obj};
  }
  var cache = _getRequireWildcardCache(nodeInterop);
  if (cache && cache.has(obj)) {
    return cache.get(obj);
  }
  var newObj = {};
  var hasPropertyDescriptor =
    Object.defineProperty && Object.getOwnPropertyDescriptor;
  for (var key in obj) {
    if (key !== 'default' && Object.prototype.hasOwnProperty.call(obj, key)) {
      var desc = hasPropertyDescriptor
        ? Object.getOwnPropertyDescriptor(obj, key)
        : null;
      if (desc && (desc.get || desc.set)) {
        Object.defineProperty(newObj, key, desc);
      } else {
        newObj[key] = obj[key];
      }
    }
  }
  newObj.default = obj;
  if (cache) {
    cache.set(obj, newObj);
  }
  return newObj;
}

/**
 * Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
const PACKAGE_JSON = path().sep + 'package.json';
let hasteImpl = null;
let hasteImplModulePath = null;

function sha1hex(content) {
  return (0, _crypto().createHash)('sha1').update(content).digest('hex');
}

async function worker(data) {
  if (
    data.hasteImplModulePath &&
    data.hasteImplModulePath !== hasteImplModulePath
  ) {
    if (hasteImpl) {
      throw new Error('jest-haste-map: hasteImplModulePath changed');
    }

    hasteImplModulePath = data.hasteImplModulePath;
    hasteImpl = require(hasteImplModulePath);
  }

  let content;
  let dependencies;
  let id;
  let module;
  let sha1;
  const {computeDependencies, computeSha1, rootDir, filePath} = data;

  const getContent = () => {
    if (content === undefined) {
      content = fs().readFileSync(filePath, 'utf8');
    }

    return content;
  };

  if (filePath.endsWith(PACKAGE_JSON)) {
    // Process a package.json that is returned as a PACKAGE type with its name.
    try {
      const fileData = JSON.parse(getContent());

      if (fileData.name) {
        const relativeFilePath = path().relative(rootDir, filePath);
        id = fileData.name;
        module = [relativeFilePath, _constants.default.PACKAGE];
      }
    } catch (err) {
      throw new Error(`Cannot parse ${filePath} as JSON: ${err.message}`);
    }
  } else if (
    !_blacklist.default.has(filePath.substring(filePath.lastIndexOf('.')))
  ) {
    // Process a random file that is returned as a MODULE.
    if (hasteImpl) {
      id = hasteImpl.getHasteName(filePath);
    }

    if (computeDependencies) {
      const content = getContent();
      dependencies = Array.from(
        data.dependencyExtractor
          ? require(data.dependencyExtractor).extract(
              content,
              filePath,
              dependencyExtractor.extract
            )
          : dependencyExtractor.extract(content)
      );
    }

    if (id) {
      const relativeFilePath = path().relative(rootDir, filePath);
      module = [relativeFilePath, _constants.default.MODULE];
    }
  } // If a SHA-1 is requested on update, compute it.

  if (computeSha1) {
    sha1 = sha1hex(getContent() || fs().readFileSync(filePath));
  }

  return {
    dependencies,
    id,
    module,
    sha1
  };
}

async function getSha1(data) {
  const sha1 = data.computeSha1
    ? sha1hex(fs().readFileSync(data.filePath))
    : null;
  return {
    dependencies: undefined,
    id: undefined,
    module: undefined,
    sha1
  };
}

**Comment by Arnav7501** [comment]
i realized i just seriously messed up my system, so i made a new project and transferred the files, and its fine now
