### ISSUE TITLE
package.json "homepage" is not read by Metro Web

### ISSUE THREAD

**Issue by erisvaldojunior** [facebook/metro#908]
Summary

Our CD serves the website in a subfolder like myurl.com/main/version/.

Before, when using Webpack, we set it on package.json "homepage": "/main/version", as said here https://docs.expo.dev/distribution/publishing-websites/

Now, after migrating to Metro Web, seems like this is not read anymore, and when the page is opened console shows an error because it is looking for /bundles/web-...js instead of /main/version/bundles/web-...js.

How should I set the path to metro web?

Minimal reproducible example

Distribute the website to a subfolder. Opening the page should show a 404 not found error on console when looking for /bundles/web-...js.

**Comment by huntie** [comment]
Interesting. I believe this is a feature of Expo CLI (although I can't find any relevant code references to `homepage` in that repo), and may not been reimplemented when adding Metro support to the `export` command (from browsing the history of [exportApp.js](https://github.com/expo/expo/blame/main/packages/%40expo/cli/src/export/exportApp.ts#L38)). cc @EvanBacon

@erisvaldojunior In the meantime, I wonder if you can configure the [`--output-dir` flag](https://docs.expo.dev/workflow/expo-cli/#exporting) ([this appears to be passed to `writeBundlesAsync`](https://github.com/expo/expo/blob/65f9c67385928e28fd05d61fc5896bdf0637969d/packages/%40expo/cli/src/export/exportApp.ts#L38)).

**Comment by erisvaldojunior** [comment]
@huntie thanks for the reply. I did try using --output-dir /main/version on the export but seems like it only move files to the destination folder, the web page still looking for /bundles/web-...js (ignoring the output-dir I set).

**Comment by erisvaldojunior** [comment]
Any additional feedback on this? cc @huntie @EvanBacon

**Comment by erisvaldojunior** [comment]
Hi guys,

Any news regarding this issue? It is quite important for our use case (ability to use Metro Web deploying to subfolders and have expo router working properly).

**Comment by huntie** [comment]
Hi @erisvaldojunior, it looks like the `"homepage"` field is a feature of Expo Web with Webpack that remains unimplemented under Expo Router. Please pursue this with the Expo team in your existing issue https://github.com/expo/expo/issues/20562 (perhaps including "Expo Router" in the title).

One more thing to try could be including the subpath in the `origin` Expo Router plugin option, [documented here (experimental)](https://expo.github.io/router/docs/lab/runtime-location/#native).
