### ISSUE TITLE
New React Native Project Not Reloading Changes

### ISSUE THREAD

**Issue by kirbyjs** [facebook/metro#917]
### Description

Hello!

I just got a new Mac M1 Pro, and I setup a new repo. When I go to make a source change in the repo, nothing changes. If I hit `CMD + R`, it reloads in the terminal, but it doesn't reflect in the simulator. Been running into this issue since the new year started. Any help is appreciated! Thanks!

### Version

0.71.0

### Output of `npx react-native info`

System:
    OS: macOS 12.6.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 393.22 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/Library/Caches/fnm_multishells/37022_1673898850933/bin/node
    Yarn: Not Found
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/37022_1673898850933/bin/npm
    Watchman: 2023.01.09.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Electric Eel 2022.1.1 Electric Eel 2022.1.1
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.0 => 0.71.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. npx react-native init MyTestApp
2. npx react-native start
3. npx react-native run-ios

### Snack, code example, screenshot, or link to a repository

![Kapture 2023-01-16 at 14 36 25](https://user-images.githubusercontent.com/13893942/212762627-12abf78f-d413-42d9-9309-e21346cfe13b.gif)

**Comment by cortinico** [comment]
Moving this to metro so folks over there can help you further

**Comment by kirbyjs** [comment]
I spent some more debugging today in the metro code, but I didn't find anything really relevant. 

I logged https://github.com/facebook/metro/blob/main/packages/metro/src/Server.js#L1022-L1027 and `numModifiedFiles` was coming back as 0 and the date was unchanged, even tho I clearly updated the file.

**Comment by robhogan** [comment]
Hi @kirbyjs - could you try running Metro with `DEBUG=Metro:* yarn start`, and then try running your app, make some file changes, and let us know the console output here? 

There should be more verbose logging, and in particular it’ll tell us which watcher Metro is using and whether it has picked up any events from the OS, and whether the app has requested any updates. Much appreciated, and thanks for the report.

**Comment by kirbyjs** [comment]
These are the logs when I pretty much do what I did in that gif in the PR description:
```
  Metro:Watcher Beginning crawl with "watchman". +0ms
  Metro:Watcher Crawler "watchman" returned 0 added/modified, 0 removed, 1 clock(s). +73ms
  Metro:InspectorProxy Got new connection: device=iPhone 14, app=org.reactjs.native.example.MyTestApp +0ms
  Metro:InspectorProxy (Debugger)    (Proxy) <- (Device), getPages ping has changed: {"event":"getPages","payload":[{"app":"org.reactjs.native.example.MyTestApp","id":"3","title":"Hermes React Native","vm":"Hermes","isLastBundleDownloadSuccess":null,"bundleUpdateTimestamp":null}]} +1s
  Metro:InspectorProxy React Native page updated to 3 +0ms
info Opening the app on iOS...
info Found Xcode workspace "MyTestApp.xcworkspace"
info Building (using "xcodebuild -workspace MyTestApp.xcworkspace -configuration Debug -scheme MyTestApp -destination id=131A7BAB-CE00-4948-93A0-AE7049F0EE5D")
success Successfully built the app
info Installing "/Users/ksimmons/Library/Developer/Xcode/DerivedData/MyTestApp-clilkqghfrlrhnfflrhfamtpqvsl/Build/Products/Debug-iphonesimulator/MyTestApp.app"
  Metro:InspectorProxy Device iPhone 14 disconnected. +17s
info Launching "org.reactjs.native.example.MyTestApp"
success Successfully launched the app on the simulator
  Metro:Server Handling request: http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.MyTestApp +0ms
 BUNDLE  ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)  Metro:InspectorProxy Got new connection: device=iPhone 14, app=org.reactjs.native.example.MyTestApp +961ms
 BUNDLE  ./index.js 

 LOG  Running "MyTestApp" with {"rootTag":1,"initialProps":{}}
  Metro:Server Handling request: http://localhost:8081/assets/node_modules/react-native/Libraries/NewAppScreen/components/logo.png?platform=ios&hash=3cf817075ffdc798cf13c457bf4c3bc5 +966ms
  Metro:InspectorProxy (Debugger)    (Proxy) <- (Device), getPages ping has changed: {"event":"getPages","payload":[{"app":"org.reactjs.native.example.MyTestApp","id":"1","title":"Hermes React Native","vm":"Hermes","isLastBundleDownloadSuccess":null,"bundleUpdateTimestamp":null}]} +1s
  Metro:InspectorProxy React Native page updated to 1 +0ms
  Metro:Server Handling request: http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.MyTestApp +41s
 BUNDLE  ./index.js 

 LOG  Running "MyTestApp" with {"rootTag":11,"initialProps":{}}
  Metro:Server Handling request: http://localhost:8081/assets/node_modules/react-native/Libraries/NewAppScreen/components/logo.png?platform=ios&hash=3cf817075ffdc798cf13c457bf4c3bc5 +305ms
  Metro:InspectorProxy (Debugger)    (Proxy) <- (Device), getPages ping has changed: {"event":"getPages","payload":[{"app":"org.reactjs.native.example.MyTestApp","id":"2","title":"Hermes React Native","vm":"Hermes","isLastBundleDownloadSuccess":null,"bundleUpdateTimestamp":null}]} +42s
  Metro:InspectorProxy React Native page updated to 2 +1ms
  Metro:Server Handling request: http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.MyTestApp +10s
 BUNDLE  ./index.js 

  Metro:InspectorProxy (Debugger)    (Proxy) <- (Device), getPages ping has changed: {"event":"getPages","payload":[{"app":"org.reactjs.native.example.MyTestApp","id":"3","title":"Hermes React Native","vm":"Hermes","isLastBundleDownloadSuccess":null,"bundleUpdateTimestamp":null}]} +10s
  Metro:InspectorProxy React Native page updated to 3 +0ms
 LOG  Running "MyTestApp" with {"rootTag":21,"initialProps":{}}
  Metro:Server Handling request: http://localhost:8081/assets/node_modules/react-native/Libraries/NewAppScreen/components/logo.png?platform=ios&hash=3cf817075ffdc798cf13c457bf4c3bc5 +288ms
```

**Comment by kirbyjs** [comment]
If I do:
1. make the change
2. kill the server
3. restart the server
4. hit `i` to connect ios

watchman logs are:
```
Metro:Watcher Beginning crawl with "watchman". +0ms
Metro:Watcher Crawler "watchman" returned 1 added/modified, 0 removed, 1 clock(s). +83ms
```

but that's a pretty painful loop to get an update from 😅

**Comment by robhogan** [comment]
Hmm, it looks like no Watcher is being initialised - you should normally see [`Metro:Watcher Using watcher "watchman"`](https://github.com/facebook/metro/blob/v0.73.5/packages/metro-file-map/src/Watcher.js#L183), immediately after `Crawler "watchman" returned...`

That suggests watching is disabled when `metro-file-map` is constructed. Assuming you're not passing `watch: false` somewhere, one possibly is that CI environment is incorrectly detected? (Metro doesn't watch in CI). You could try debugging this file to see what's passed as the value of `watch`, and why?

https://github.com/facebook/metro/blob/b3f57c236a4af3c4e68c7eb555f339551a4e0225/packages/metro/src/node-haste/DependencyGraph/createHasteMap.js#L93

If a CI is being detected due to some odd environment variable, running this from your project root might show some clues:
```
node -p "require('ci-info')"
```

**Comment by kirbyjs** [comment]
@robhogan knew right away what the issue was when you said that it's detecting a CI environment 🤦🏼‍♂️ 

I had `CODEBUILD_BUILD_ARN` to ignore one of our internal processes, but didn't realize that it would accidentally break the `metro's` reloading. Thanks so much for your help!
