### ISSUE TITLE
`metro-react-native-babel-preset` npm `latest` tag is wrong

### ISSUE THREAD

**Issue by simon-abbott** [facebook/metro#952]
The newest version of `metro-react-native-babel-preset` is `0.76.0`, but the `latest` tag is pointing to `0.73.9`.

**Comment by TomCorvus** [comment]
Seems to be fixed:
https://www.npmjs.com/package/metro-react-native-babel-preset?activeTab=versions

**Comment by robhogan** [comment]
Apologies, this was briefly wrong after we released 0.73.9 with a backported fix yesterday, until I manually re-tagged 0.76.0. 

Glitch of the release process and NPM's auto-tagging behaviour, we'll try to address that for next time.
