### ISSUE TITLE
Builds failing with 0.76.4

### ISSUE THREAD

**Issue by erquhart** [facebook/metro#979]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Using Expo managed workflow and Expo router, latest versions. But this seems metro specific.

Production builds fail with the following unhandled error:
```
TypeError: this._config.serializer.isThirdPartyModule is not a function
    at Server._shouldAddModuleToIgnoreList (/private/var/folders/l9/djwyz_ps65v_s9y4vx8jnpmm0000gn/T/eas-build-local-nodejs/b4549fe4-3088-46a1-a593-c5c16e07d6d7/build/node_modules/metro/src/Server.js:1077:31)
```

The code producing this error was released in 0.76.4, and was added in this commit:
https://github.com/facebook/metro/commit/82bd64a9720174a9e2a02fb73bbef292153e20f1

Reverting to 0.76.3 resolves the issue.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
Getting this reproduced in isolation would be a pretty complex task as I'm using Metro via EAS build. If nothing else I'm hoping this issue can corroborate with anyone else experiencing the same, as I'm not finding any mention of it anywhere.

**What is the expected behavior?**
Build succeeds.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
- metro 0.76.3
- metro-resolver 0.76.3
- node 18.15.0
- npm 9.5.0
- macOS 13.3.1

Metro versions pinned via npm overrides and confirmed via `npm ls`.

**Comment by robhogan** [comment]
Hi @erquhart - thanks for the report and investigation. As a first thought, if you're overriding Metro versions, could we rule out mismatched `metro-` package versions? This sounds like something that could be caused by an out-of-sync `metro-config` or `metro-transform-worker`.

**Comment by erquhart** [comment]
Ah I wasn't aware of those, looks I may need to override a few more packages. The overrides are based on requirements from `expo-router`: https://expo.github.io/router/docs/

I'll try overriding `metro-config` and `metro-transform-worker` to 0.76.4 as well, I do see they're mismatched.

**Comment by erquhart** [comment]
That fixed it - I'll give a heads up on the expo-router repo, thanks for the tip!
