### ISSUE TITLE
Replace deprecated `uglify-es` dependency

### ISSUE THREAD

**Issue by TimJentzsch** [facebook/metro#980]
**Do you want to request a *feature* or report a *bug*?**

"bug", deprecation

**What is the current behavior?**

During installation, I get the following warning:

```
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
```

This is a dependency of `metro-minify-uglify`:

<https://github.com/facebook/metro/blob/a3c5b261779e6ba257411b16dec6c72b17cbfd99/packages/metro-minify-uglify/package.json#L16>

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

Run `npm ci` on a project using `metro` with `metro-minify-uglify`.

**What is the expected behavior?**

`metro` does not use any deprecated dependencies.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

- `metro@0.73.9`
- `node@18.15.0`
- `npm@9.6.4`

**Comment by robhogan** [comment]
Closed by https://github.com/facebook/metro/pull/1013

**Comment by ahmadsyed** [comment]
Still getting this npx react-native init .

**Comment by drgnmsr** [comment]
If "the warning is safe to ignore", then why is npx react-native init not installing react-native?

**Comment by ElSguidge** [comment]
Issue seemed to occur for me when trying to install React-Native 0.72.0. Try @latest
