### ISSUE TITLE
nullthrows invariant hit when bundling intl/lib/core

### ISSUE THREAD

**Issue by janicduplessis** [facebook/metro#99]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Errors with `/Users/janic/Developer/metrobug/node_modules/intl/lib/core.js: Got unexpected null or undefined` when generating a prod bundle for the file intl/lib/core.js. It used to work before updating to the latest metro published version. The intl package hasn't changed since.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
https://github.com/janicduplessis/metrobug

**What is the expected behavior?**
Generates a valid js bundle.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
No special config
Metro: 0.22.1
Yarn:  1.3.2
Node: 8.9.0

**Comment by rafeca** [comment]
Thanks for reporting! We recently changed the way transformers work, forcing them to output AST, but it turns out that by default babel does not transform files inside node_modules, causing the AST to be null.

I'm going to send a patch to fix that.
